#!/usr/bin/env python3
"""Commit locally approved PR worktrees before pushing."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


APPROVED_STATES = {"approved", "local_approved"}
FORBIDDEN_MESSAGE_TOKENS = ["Co-authored-by", "Co-authored by", "Generated-by", "Generated by"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Commit approved PR worktrees.")
    parser.add_argument("--run-dir", required=True)
    parser.add_argument("--worktree-root", default="/root/pr_worktrees")
    parser.add_argument("--worktree-template", default="")
    parser.add_argument("--pr", type=int, action="append", default=[], help="Only consider this PR number. Repeatable.")
    parser.add_argument("--message", default="fix: address PR review comments")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def run(cmd: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, text=True, capture_output=True)


def load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: object) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def load_tasks(run_dir: Path) -> list[dict[str, object]]:
    tasks: list[dict[str, object]] = []
    with (run_dir / "tasks.jsonl").open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                tasks.append(json.loads(line))
    return tasks


def task_status_path(run_dir: Path, task: dict[str, object]) -> Path:
    task_id = str(task["task_id"])
    pr_num = int(task["pr_num"])
    pr_dir = run_dir / "runs" / f"pr-{pr_num}"
    for candidate in pr_dir.glob("*/task.json"):
        data = load_json(candidate)
        if isinstance(data, dict) and data.get("task_id") == task_id:
            return candidate.parent / "status.json"
    raise FileNotFoundError(f"status not found for {task_id}")


def external_status_paths(run_dir: Path) -> list[Path]:
    paths: list[Path] = []
    runs_root = run_dir / "runs"
    for pattern in ["pr-*/ci-fix-*/status.json", "pr-*/rebase-conflict-*/status.json"]:
        paths.extend(sorted(runs_root.glob(pattern)))
    return paths


def worktree_for(args: argparse.Namespace, pr_num: int) -> Path:
    if args.worktree_template:
        return Path(args.worktree_template.format(pr_num=pr_num))
    return Path(args.worktree_root) / f"pr{pr_num}"


def approved_normal_prs(run_dir: Path, tasks: list[dict[str, object]]) -> dict[int, list[Path]]:
    tasks_by_pr: dict[int, list[dict[str, object]]] = {}
    for task in tasks:
        if task.get("decision") in {"must_fix", "should_reply"}:
            tasks_by_pr.setdefault(int(task["pr_num"]), []).append(task)

    result: dict[int, list[Path]] = {}
    for pr_num, pr_tasks in tasks_by_pr.items():
        paths: list[Path] = []
        all_approved = True
        for task in pr_tasks:
            status_path = task_status_path(run_dir, task)
            paths.append(status_path)
            status = load_json(status_path)
            if not isinstance(status, dict) or status.get("state") not in APPROVED_STATES:
                all_approved = False
        if all_approved and paths:
            result[pr_num] = paths
    return result


def approved_external_prs(run_dir: Path) -> dict[int, list[Path]]:
    result: dict[int, list[Path]] = {}
    for status_path in external_status_paths(run_dir):
        status = load_json(status_path)
        if not isinstance(status, dict) or status.get("state") not in APPROVED_STATES:
            continue
        pr_num = int(status.get("pr_num", 0) or 0)
        if pr_num:
            result.setdefault(pr_num, []).append(status_path)
    return result


def candidate_status_paths(run_dir: Path, tasks: list[dict[str, object]]) -> dict[int, list[Path]]:
    candidates = approved_normal_prs(run_dir, tasks)
    for pr_num, paths in approved_external_prs(run_dir).items():
        candidates.setdefault(pr_num, []).extend(paths)
    return candidates


def forbidden_message(message: str) -> str:
    for token in FORBIDDEN_MESSAGE_TOKENS:
        if token.lower() in message.lower():
            return token
    return ""


def update_status_paths(paths: list[Path], row: dict[str, object]) -> None:
    for status_path in paths:
        status = load_json(status_path)
        if not isinstance(status, dict):
            continue
        commit_status = status.setdefault("commit", {})
        if isinstance(commit_status, dict):
            commit_status["state"] = row["state"]
            commit_status["last_exit_code"] = row.get("exit_code")
            if row.get("old_head"):
                commit_status["old_head"] = row["old_head"]
            if row.get("new_head"):
                commit_status["new_head"] = row["new_head"]
            if row.get("message"):
                commit_status["message"] = row["message"]
            if row.get("error"):
                commit_status["error"] = row["error"]
            else:
                commit_status.pop("error", None)
        write_json(status_path, status)


def commit_one(args: argparse.Namespace, pr_num: int) -> dict[str, object]:
    worktree = worktree_for(args, pr_num)
    if not worktree.exists():
        raise FileNotFoundError(f"missing worktree for PR #{pr_num}: {worktree}")
    token = forbidden_message(args.message)
    if token:
        raise ValueError(f"commit message contains forbidden token: {token}")

    old_head_result = run(["git", "rev-parse", "HEAD"], worktree)
    if old_head_result.returncode != 0:
        raise RuntimeError(old_head_result.stderr)
    old_head = old_head_result.stdout.strip()

    status = run(["git", "status", "--porcelain"], worktree)
    if status.returncode != 0:
        raise RuntimeError(status.stderr)
    if not status.stdout.strip():
        return {
            "pr_num": pr_num,
            "state": "no_changes",
            "worktree": str(worktree),
            "old_head": old_head,
            "new_head": old_head,
        }

    if args.dry_run:
        return {
            "pr_num": pr_num,
            "state": "dry_run",
            "worktree": str(worktree),
            "old_head": old_head,
            "message": args.message,
            "status": status.stdout,
        }

    add = run(["git", "add", "-A"], worktree)
    if add.returncode != 0:
        raise RuntimeError(add.stderr or add.stdout)
    commit = run(["git", "commit", "-m", args.message], worktree)
    if commit.returncode != 0:
        raise RuntimeError(commit.stderr or commit.stdout)
    msg = run(["git", "log", "-1", "--pretty=%B"], worktree)
    if msg.returncode != 0:
        raise RuntimeError(msg.stderr)
    token = forbidden_message(msg.stdout)
    if token:
        raise RuntimeError(f"created commit contains forbidden token: {token}")
    new_head_result = run(["git", "rev-parse", "HEAD"], worktree)
    if new_head_result.returncode != 0:
        raise RuntimeError(new_head_result.stderr)
    return {
        "pr_num": pr_num,
        "state": "completed",
        "exit_code": commit.returncode,
        "worktree": str(worktree),
        "old_head": old_head,
        "new_head": new_head_result.stdout.strip(),
        "message": args.message,
        "stdout": commit.stdout,
        "stderr": commit.stderr,
    }


def main() -> int:
    args = parse_args()
    run_dir = Path(args.run_dir).resolve()
    tasks = load_tasks(run_dir)
    candidates = candidate_status_paths(run_dir, tasks)
    if args.pr:
        allowed = set(args.pr)
        candidates = {pr_num: paths for pr_num, paths in candidates.items() if pr_num in allowed}
    results: list[dict[str, object]] = []
    ok = True
    for pr_num in sorted(candidates):
        try:
            row = commit_one(args, pr_num)
        except Exception as exc:
            row = {
                "pr_num": pr_num,
                "state": "failed",
                "exit_code": 1,
                "error": f"{type(exc).__name__}: {exc}",
            }
        results.append(row)
        if row["state"] not in {"completed", "no_changes", "dry_run"}:
            ok = False
        update_status_paths(candidates[pr_num], row)
    write_json(run_dir / "commit_result.json", results)
    print(json.dumps(results, indent=2, ensure_ascii=False))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
