#!/usr/bin/env python3
"""从 worktree 自动提取算子代码并准备 6 个 PR 文件。

用法:
    python extract_from_worktree.py <op> --repo-dir /path/to/FlagGems
    python extract_from_worktree.py <op> --dry-run  # 只预览不写入

自动完成:
    1. 复制 kernel 文件（确保版权/License + KernelGen 文件头）
    2. 从 worktree 提取测试函数 → tests/test_<op>.py
    3. 从 worktree 提取 benchmark → benchmark/test_<op>.py
    4. 按字母序插入 ops/__init__.py（import + __all__）
    5. 按字母序插入 __init__.py（_FULL_CONFIG）
    6. 按字母序插入 conf/operators.yaml
"""

import argparse
import os
import re
import sys

import yaml

from name_plan import build_name_plan, write_name_plan

DEFAULT_REPO = "/root/FlagGems"
COPYRIGHT_LICENSE_HEADER = """# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
KERNELGEN_HEADER = "# Generated by KernelGen: https://github.com/flagos-ai/KernelGen\n"
REQUIRED_KERNEL_HEADER = COPYRIGHT_LICENSE_HEADER + KERNELGEN_HEADER

# accuracy_utils symbols that need `utils.` prefix when converting imports
UTILS_SYMBOLS = [
    "FLOAT_DTYPES", "ALL_FLOAT_DTYPES", "INT_DTYPES", "ALL_INT_DTYPES",
    "BOOL_TYPES", "COMPLEX_DTYPES", "POINTWISE_SHAPES", "SPECIAL_SHAPES",
    "DISTRIBUTION_SHAPES", "REDUCTION_SHAPES", "to_reference",
    "gems_assert_close", "gems_assert_equal",
]


class Colors:
    OK = "\033[92m"
    FAIL = "\033[91m"
    BOLD = "\033[1m"
    CYAN = "\033[96m"
    END = "\033[0m"


def ok(msg):
    print(f"  {Colors.OK}✓{Colors.END} {msg}")


def warn(msg):
    print(f"  {Colors.CYAN}⚠{Colors.END} {msg}")


def fatal(msg):
    print(f"  {Colors.FAIL}✗ FATAL: {msg}{Colors.END}")
    sys.exit(1)


def section(msg):
    print(f"\n{Colors.BOLD}[{msg}]{Colors.END}")


def get_op_id(op_name):
    return op_name.lstrip("_")


def normalize_kernel_header(content):
    if content.startswith(REQUIRED_KERNEL_HEADER):
        return content

    if content.startswith(COPYRIGHT_LICENSE_HEADER):
        rest = content[len(COPYRIGHT_LICENSE_HEADER):]
        if rest.startswith(KERNELGEN_HEADER):
            return content
        if rest.startswith("# Generated by KernelGen"):
            rest = rest.split("\n", 1)[1] if "\n" in rest else ""
        return REQUIRED_KERNEL_HEADER + rest.lstrip("\n")

    if content.startswith("# Generated by KernelGen"):
        content = content.split("\n", 1)[1] if "\n" in content else ""

    return REQUIRED_KERNEL_HEADER + content


# ---------------------------------------------------------------------------
# Step 1: Kernel file
# ---------------------------------------------------------------------------


def extract_kernel(op, worktree, repo, dry_run):
    section("Step 1: Kernel 文件")
    src = os.path.join(worktree, f"src/flag_gems/ops/{op}.py")
    dst = os.path.join(repo, f"src/flag_gems/ops/{op}.py")

    if not os.path.isfile(src):
        fatal(f"worktree kernel 不存在: {src}")

    with open(src) as f:
        content = f.read()

    content = normalize_kernel_header(content)

    if dry_run:
        ok(f"[DRY] 将写入 {dst} ({len(content.splitlines())} 行)")
    else:
        with open(dst, "w") as f:
            f.write(content)
        ok(f"已复制: {dst}")


# ---------------------------------------------------------------------------
# Step 2: Test file
# ---------------------------------------------------------------------------


def find_test_function(op, worktree):
    """Find and extract test function(s) for the operator from worktree.

    Search priority:
    1. test_accuracy_<op_id> — most common pattern
    2. test_accuracy_<op_name> — underscore-prefixed variant
    3. test_<op_id> — no accuracy prefix (reflection_pad3d, embedding etc.)
    4. Any function decorated with @pytest.mark.<op_id>
    """
    tests_dir = os.path.join(worktree, "tests")
    op_id = get_op_id(op)

    candidates = [
        f"test_accuracy_{op_id}",
        f"test_accuracy_{op}" if op.startswith("_") else None,
        f"test_{op_id}",
    ]
    candidates = [c for c in candidates if c]

    for target_func in candidates:
        for fname in os.listdir(tests_dir):
            if not fname.endswith(".py"):
                continue
            fpath = os.path.join(tests_dir, fname)
            with open(fpath) as f:
                content = f.read()
            if f"def {target_func}" in content:
                return fpath, content, target_func

    # Fallback: find by @pytest.mark.<op_id>
    mark_pattern = f"@pytest.mark.{op_id}"
    for fname in os.listdir(tests_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(tests_dir, fname)
        with open(fpath) as f:
            content = f.read()
        if mark_pattern in content:
            # Find the first test function after the mark
            match = re.search(rf"{re.escape(mark_pattern)}.*?def\s+(test_\w+)", content, re.DOTALL)
            if match:
                return fpath, content, match.group(1)

    return None, None, None


def find_all_related_test_functions(content, op_id, primary_func_name):
    """Find all test functions related to the operator in the same file.

    Looks for functions decorated with @pytest.mark.<op_id>.
    """
    func_names = []
    mark = f"@pytest.mark.{op_id}"

    # Use regex to find all def lines preceded (somewhere above) by the mark
    # Pattern: @pytest.mark.<op_id> followed eventually by def test_xxx
    for m in re.finditer(
        rf"^{re.escape(mark)}\s*\n(?:.*\n)*?^\s*def\s+(test_\w+)",
        content, re.MULTILINE
    ):
        fn = m.group(1)
        if fn not in func_names:
            func_names.append(fn)

    if not func_names and primary_func_name:
        func_names = [primary_func_name]

    return func_names



def extract_assignment_block(content, name):
    """Extract a module-level NAME = ... assignment, including preceding comments."""
    lines = content.split("\n")
    start = None
    for i, line in enumerate(lines):
        if re.match(rf"^{re.escape(name)}\s*=", line):
            start = i
            break
    if start is None:
        return None

    comment_start = start
    j = start - 1
    while j >= 0 and lines[j].strip().startswith("#"):
        comment_start = j
        j -= 1

    end = start + 1
    balance = 0
    for i in range(start, len(lines)):
        line = lines[i]
        balance += (
            line.count("(") + line.count("[") + line.count("{")
            - line.count(")") - line.count("]") - line.count("}")
        )
        if i > start and balance <= 0:
            end = i + 1
            break
    return "\n".join(lines[comment_start:end]).rstrip()


def extract_referenced_constants(content, block_text):
    names = sorted(set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b", block_text)))
    blocks = []
    for name in names:
        block = extract_assignment_block(content, name)
        if block:
            blocks.append(block)
    return blocks

def extract_function_block(content, func_name):
    """Extract a function and its decorators from source code."""
    lines = content.split("\n")
    func_start = None
    decorator_start = None
    func_end = None

    for i, line in enumerate(lines):
        if f"def {func_name}" in line or f"class {func_name}" in line:
            func_start = i
            # Walk backwards to find decorators, including multi-line parametrize blocks.
            decorator_start = i
            j = i - 1
            balance = 0
            while j >= 0:
                stripped = lines[j].strip()
                if stripped == "" and balance == 0:
                    break
                if balance > 0 or stripped.startswith("@") or stripped.startswith((")", "]", "}")):
                    decorator_start = j
                    balance += (
                        stripped.count(")") + stripped.count("]") + stripped.count("}")
                        - stripped.count("(") - stripped.count("[") - stripped.count("{")
                    )
                    if stripped.startswith("@") and balance <= 0:
                        balance = 0
                    j -= 1
                    continue
                break
            break

    if func_start is None:
        return None

    # Find function end (next def/class at same or lower indent, or EOF)
    indent = len(lines[func_start]) - len(lines[func_start].lstrip())
    for i in range(func_start + 1, len(lines)):
        line = lines[i]
        if line.strip() == "":
            continue
        line_indent = len(line) - len(line.lstrip())
        if line_indent <= indent and (line.strip().startswith("def ") or
                                       line.strip().startswith("class ") or
                                       line.strip().startswith("@")):
            # Check if decorator belongs to this function
            if i > func_start + 1:
                func_end = i
                break
    if func_end is None:
        func_end = len(lines)

    # Trim trailing blank lines
    while func_end > decorator_start and lines[func_end - 1].strip() == "":
        func_end -= 1

    return "\n".join(lines[decorator_start:func_end])


def convert_test_imports(func_block, op):
    """Convert direct accuracy_utils imports to `utils.` prefix style."""
    op_id = get_op_id(op)
    result = func_block

    # Replace function name: test_accuracy_<op> → test_<op>
    result = re.sub(rf"def test_accuracy_{re.escape(op_id)}\b",
                    f"def test_{op_id}", result)
    if op.startswith("_"):
        result = re.sub(rf"def test_accuracy_{re.escape(op)}\b",
                        f"def test_{op_id}", result)

    # Replace bare symbols with utils. prefix
    for sym in UTILS_SYMBOLS:
        # Only replace bare occurrences (not already prefixed)
        result = re.sub(rf"(?<!\.)(?<!\w){re.escape(sym)}\b", f"utils.{sym}", result)

    # Replace device reference
    result = result.replace("device=device", "device=flag_gems.device")

    # Remove vendor-specific branches
    result = re.sub(
        r"\s*if flag_gems\.vendor_name\s*==\s*[\"']kunlunxin[\"'].*?(?=\n\S|\n@|\Z)",
        "", result, flags=re.DOTALL
    )

    return result


def extract_test(op, worktree, repo, dry_run):
    section("Step 2: Test 文件")
    op_id = get_op_id(op)
    dst = os.path.join(repo, f"tests/test_{op_id}.py")

    fpath, content, func_name = find_test_function(op, worktree)
    if not fpath:
        fatal(f"worktree 中未找到 test_accuracy_{op_id} 或 test_{op_id} 函数")

    ok(f"找到测试: {os.path.basename(fpath)}:{func_name}")

    # Find all related test functions (including variants like _list_padding, _empty_padding)
    all_funcs = find_all_related_test_functions(content, op_id, func_name)
    ok(f"找到 {len(all_funcs)} 个相关测试函数: {', '.join(all_funcs)}")

    blocks = []
    for fn in all_funcs:
        block = extract_function_block(content, fn)
        if block:
            block = convert_test_imports(block, op)
            blocks.append(block)

    if not blocks:
        fatal(f"无法提取函数 {func_name}")

    constants = extract_referenced_constants(content, "\n".join(blocks))
    combined_blocks = "\n\n\n".join(constants + blocks)

    test_content = (
        "import pytest\n"
        "import torch\n"
        "\n"
        "import flag_gems\n"
        "\n"
        "from . import accuracy_utils as utils\n"
        "\n"
        "\n"
        f"{combined_blocks}\n"
    )

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{test_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(test_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 3: Benchmark file
# ---------------------------------------------------------------------------


def find_benchmark_code(op, worktree):
    """Find benchmark code for the operator in worktree."""
    op_id = get_op_id(op)
    bench_dir = os.path.join(worktree, "benchmark")

    for fname in os.listdir(bench_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(bench_dir, fname)
        with open(fpath) as f:
            content = f.read()
        if (f"mark.{op_id}" in content or f'op_name="{op_id}"' in content
                or f'"{op_id}"' in content):
            return fpath, content

    return None, None


def extract_benchmark_block(content, op, source_file):
    """Extract benchmark related code (class, input_fn, test function)."""
    op_id = get_op_id(op)
    lines = content.split("\n")
    blocks = []

    # Strategy 1: Find standalone class + test function (e.g., RandintBenchmark)
    op_key = re.sub(r"[^0-9A-Za-z]+", "", op_id).lower()
    for i, line in enumerate(lines):
        class_match = re.search(r"class\s+(\w*Benchmark)\b", line)
        if not class_match:
            continue
        cls_name = class_match.group(1)
        cls_key = re.sub(r"[^0-9A-Za-z]+", "", cls_name).lower()
        if op_key not in cls_key:
            continue
        block = extract_function_block(content, cls_name)
        if block:
            blocks.append(("class", block))

    # Strategy 2: Find input_fn for this op
    input_fn_names = [
        f"{op_id}_input_fn", f"_{op_id}_input_fn", f"_input_fn",
    ]
    for fn_name in input_fn_names:
        for i, line in enumerate(lines):
            if f"def {fn_name}" in line:
                block = extract_function_block(content, fn_name)
                if block:
                    blocks.append(("input_fn", block))
                break

    # Strategy 3: Find standalone test function (e.g., test_perf_randint)
    test_patterns = [
        rf"def test_(?:perf_)?{re.escape(op_id)}(?:_perf)?\b",
        rf"def test_{re.escape(op_id)}(?:_perf)?\b",
    ]
    for pat in test_patterns:
        for i, line in enumerate(lines):
            if re.search(pat, line):
                fname = re.search(r"def (\w+)", line).group(1)
                block = extract_function_block(content, fname)
                if block:
                    blocks.append(("test", block))
                break
        if any(t == "test" for t, _ in blocks):
            break

    # Strategy 4: op in a parametrized list → generate standalone benchmark
    if not any(t == "test" for t, _ in blocks):
        list_entry = _find_list_entry(lines, op_id, source_file)
        if list_entry:
            blocks.append(("list_entry", list_entry))

    if blocks:
        block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
        constants = extract_referenced_constants(content, block_text)
        for const_block in reversed(constants):
            blocks.insert(0, ("constant", const_block))

    return blocks


def _find_list_entry(lines, op_id, source_file):
    """Find op in a parametrized operations list and return benchmark info dict."""
    basename = os.path.basename(source_file) if source_file else ""

    for i, line in enumerate(lines):
        stripped = line.strip()
        if f'"{op_id}"' not in stripped:
            continue

        # Parse: ("op_name", torch.op, [dtypes]) or ("op_name", lambda..., dtypes_expr)
        # Try standard pattern first: "op_name", torch.xxx, ...
        match = re.search(
            rf'\(\s*"{re.escape(op_id)}"\s*,\s*([\w.]+)\s*(?:,\s*(.+?))?\s*\)',
            stripped
        )
        if match:
            torch_op = match.group(1)
            third_arg = match.group(2).strip().rstrip(",") if match.group(2) else None
        else:
            # Fallback: match lambda/partial patterns, e.g. ("op_name", lambda a: a.op_(), DTYPES)
            match = re.search(
                rf'\(\s*"{re.escape(op_id)}"\s*,\s*(lambda[^,]*)\s*,\s*(.+?)\s*\)',
                stripped
            )
            if not match:
                continue
            torch_op = match.group(1).strip()
            third_arg = match.group(2).strip().rstrip(",")

        # Determine benchmark type from file name
        bench_type = "generic"
        if "unary_pointwise" in basename:
            bench_type = "unary"
        elif "binary_pointwise" in basename:
            bench_type = "binary"

        # Determine dtypes
        dtypes = None
        if third_arg:
            dtypes = third_arg.rstrip(",")

        return {
            "type": bench_type,
            "torch_op": torch_op,
            "dtypes": dtypes,
            "op_id": op_id,
        }

    return None


def generate_benchmark_file(blocks, op, bench_source_file):
    """Generate independent benchmark file from extracted blocks."""
    op_id = get_op_id(op)

    has_class = any(t == "class" for t, _ in blocks)
    has_test = any(t == "test" for t, _ in blocks)
    list_entry = next((b for t, b in blocks if t == "list_entry"), None)

    # Case A: standalone class + input_fn + test function → combine them
    if has_class or has_test:
        all_block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
        needs_consts = ("consts." in all_block_text or "FLOAT_DTYPES" in all_block_text
                        or "INT_DTYPES" in all_block_text)
        needs_generator = "Generator" in all_block_text
        needs_flag_gems = "flag_gems." in all_block_text

        header_parts = []
        if needs_generator:
            header_parts.append("from typing import Generator")
        header_parts.append("import pytest")
        header_parts.append("import torch")
        if needs_flag_gems:
            header_parts.append("\nimport flag_gems")
        header = "\n".join(header_parts) + "\n\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        parts = [header]
        for btype, block in blocks:
            if not isinstance(block, str):
                continue
            if btype == "test":
                block = re.sub(rf"def test_perf_{re.escape(op_id)}\b",
                               f"def test_{op_id}", block)
            parts.append(f"\n\n{block}")

        content = "\n".join(parts)

        # Add base. prefix to benchmark classes/helpers if not already prefixed
        for cls in ["GenericBenchmark", "GenericBenchmarkExcluse1D",
                     "GenericBenchmarkExcluse3D", "GenericBenchmark2DOnly",
                     "GenericBenchmark4DOnly", "UnaryPointwiseBenchmark",
                     "BinaryPointwiseBenchmark", "UnaryReductionBenchmark",
                     "BlasBenchmark", "Benchmark"]:
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\(", f"base.{cls}(", content)
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\)", f"base.{cls})", content)
        for helper in ["generate_tensor_input", "Config"]:
            content = re.sub(rf"(?<!base\.)(?<!\w){helper}\b", f"base.{helper}", content)
        content = content.replace("base.base.", "base.")

        # Add consts. prefix
        for const in ["FLOAT_DTYPES", "INT_DTYPES", "EXTRA_INT_DTYPES", "BOOL_DTYPES"]:
            content = re.sub(rf"(?<!consts\.)(?<!\w){const}\b", f"consts.{const}", content)
        content = content.replace("consts.consts.", "consts.")

    # Case B: list entry → generate standard benchmark
    elif list_entry:
        info = list_entry
        torch_op = info["torch_op"]
        dtypes_str = info.get("dtypes")

        if info["type"] == "unary":
            cls = "base.UnaryPointwiseBenchmark"
        elif info["type"] == "binary":
            cls = "base.BinaryPointwiseBenchmark"
        else:
            cls = "base.GenericBenchmark"

        # Build dtypes argument
        if dtypes_str:
            dtypes_arg = f"dtypes={dtypes_str}"
            needs_consts = False
        else:
            dtypes_arg = "dtypes=consts.FLOAT_DTYPES"
            needs_consts = True

        header = "import pytest\nimport torch\n\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        content = f"""{header}


@pytest.mark.{op_id}
def test_{op_id}():
    bench = {cls}(
        op_name="{op_id}",
        torch_op={torch_op},
        {dtypes_arg},
    )
    bench.run()
"""
    else:
        return None

    if not content.endswith("\n"):
        content += "\n"
    return content


def extract_benchmark(op, worktree, repo, dry_run):
    section("Step 3: Benchmark 文件")
    op_id = get_op_id(op)
    dst = os.path.join(repo, f"benchmark/test_{op_id}.py")

    fpath, content = find_benchmark_code(op, worktree)
    if not fpath:
        fatal(f"worktree benchmark 中未找到 {op_id} 相关代码")

    ok(f"找到 benchmark: {os.path.basename(fpath)}")

    blocks = extract_benchmark_block(content, op, fpath)
    if not blocks:
        fatal(f"无法提取 benchmark 代码块")

    ok(f"提取到 {len(blocks)} 个代码块: {[t for t, _ in blocks]}")

    bench_content = generate_benchmark_file(blocks, op, fpath)

    if not bench_content:
        fatal("无法生成 benchmark 文件内容")

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{bench_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(bench_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 4: ops/__init__.py
# ---------------------------------------------------------------------------


def insert_ops_init(op, worktree, repo, dry_run):
    section("Step 4: ops/__init__.py")
    wt_init = os.path.join(worktree, "src/flag_gems/ops/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/ops/__init__.py")

    # Extract import line and __all__ entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    # Try both op and op without trailing underscore (inplace ops stored in base module)
    module_names = [op]
    if op.endswith("_"):
        module_names.append(op.rstrip("_"))

    import_patterns = [
        rf"^from flag_gems\.ops\.{re.escape(m)} import .+$" for m in module_names
    ]
    import_line = None
    used_module = None
    for line in wt_content.split("\n"):
        for pattern, module in zip(import_patterns, module_names):
            if re.match(pattern, line):
                import_line = line
                used_module = module
                break
        if import_line:
            break

    if not import_line:
        fatal(f"worktree ops/__init__.py 中未找到 {op} 的 import")

    # Extract __all__ names for this op
    all_names = re.findall(rf'from flag_gems\.ops\.{re.escape(used_module)} import (.+)', import_line)[0]
    names = [n.strip() for n in all_names.split(",")]
    ok(f"import: {import_line}")
    ok(f"导出名: {names}")

    # Fix import line module name: worktree may use base name (logical_not) but
    # repo uses op name (logical_not_) for the kernel file.
    if used_module != op:
        import_line = import_line.replace(
            f"from flag_gems.ops.{used_module} import",
            f"from flag_gems.ops.{op} import"
        )
        ok(f"import 模块名修正: {used_module} → {op}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    # Insert import line in alphabetical order
    repo_lines = repo_content.split("\n")
    import_section_end = 0
    existing_imports = []
    for i, line in enumerate(repo_lines):
        if line.startswith("from flag_gems.ops."):
            existing_imports.append((i, line))
            import_section_end = i

    # Check if already exists
    if any(import_line in line for _, line in existing_imports):
        ok("import 已存在，跳过")
    else:
        # Find insertion point by alphabetical order
        module_name = op
        insert_idx = import_section_end + 1
        for i, line in existing_imports:
            match = re.match(r"from flag_gems\.ops\.(\w+) import", line)
            if match:
                existing_mod = match.group(1)
                sort_key_existing = (not existing_mod.startswith("_"), existing_mod)
                sort_key_new = (not module_name.startswith("_"), module_name)
                if sort_key_new < sort_key_existing:
                    insert_idx = i
                    break
                insert_idx = i + 1

        repo_lines.insert(insert_idx, import_line)
        ok(f"import 插入位置: 行 {insert_idx + 1}")

    # Insert into __all__
    # Find __all__ block
    all_start = None
    all_end = None
    for i, line in enumerate(repo_lines):
        if "__all__" in line and "=" in line:
            all_start = i
        if all_start and line.strip() == "]":
            all_end = i
            break

    if all_start and all_end:
        # Extract current __all__ entries
        all_entries = []
        for i in range(all_start, all_end + 1):
            matches = re.findall(r'"(\w+)"', repo_lines[i])
            all_entries.extend(matches)

        for name in names:
            if name in all_entries:
                ok(f'__all__ 已包含 "{name}"')
                continue

            # Find insertion point
            insert_idx = all_end
            for i in range(all_start + 1, all_end):
                match = re.search(r'"(\w+)"', repo_lines[i])
                if match:
                    existing = match.group(1)
                    if name < existing:
                        insert_idx = i
                        break
                    insert_idx = i + 1

            entry = f'    "{name}",'
            repo_lines.insert(insert_idx, entry)
            all_end += 1
            ok(f'__all__ 插入 "{name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] ops/__init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("ops/__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 5: _FULL_CONFIG
# ---------------------------------------------------------------------------


def insert_full_config(op, worktree, repo, dry_run):
    section("Step 5: _FULL_CONFIG")
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/__init__.py")

    # Extract config entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    # Find all config entries for this op
    op_id = get_op_id(op)
    config_entries = []
    for line in wt_content.split("\n"):
        line_stripped = line.strip()
        if line_stripped.startswith("(") and ("," in line_stripped):
            match = re.match(r'\(\s*"([^"]+)"\s*,\s*(\w+)', line_stripped)
            if match:
                aten_name, func_name = match.groups()
                # special_* → special.* 格式修正
                if aten_name.startswith("special_") and "." not in aten_name:
                    corrected = aten_name.replace("special_", "special.", 1)
                    line_stripped = line_stripped.replace(f'"{aten_name}"', f'"{corrected}"')
                    warn(f"_FULL_CONFIG aten name 自动修正: {aten_name} → {corrected}")
                    aten_name = corrected
                base_name = aten_name.split(".")[0].replace("special", "special").lstrip("_")
                func_base = func_name.replace("special_", "").lstrip("_")
                op_base = op.replace("special_", "").lstrip("_")
                op_id_base = op_id.replace("special_", "").lstrip("_")
                if (base_name == op or base_name == op_id
                        or func_name == op or func_name == op_id
                        or func_base == op_base or func_base == op_id_base):
                    config_entries.append(line_stripped.rstrip(",") + ",")

    if not config_entries:
        fatal(f"worktree _FULL_CONFIG 中未找到 {op} 的条目")

    for entry in config_entries:
        ok(f"配置: {entry}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    repo_lines = repo_content.split("\n")

    # Find _FULL_CONFIG block
    config_start = None
    config_end = None
    for i, line in enumerate(repo_lines):
        if "_FULL_CONFIG" in line and "=" in line:
            config_start = i
        if config_start and line.strip() == ")":
            config_end = i
            break

    if not config_start or not config_end:
        fatal("未找到 _FULL_CONFIG 定义")

    # Insert each entry (deduplicate: track inserted aten names)
    inserted_names = set()
    for entry in config_entries:
        match = re.match(r'\(\s*"([^"]+)"', entry)
        if not match:
            continue
        aten_name = match.group(1)

        # Check if already exists in repo OR already inserted in this run
        if f'"{aten_name}"' in repo_content or aten_name in inserted_names:
            ok(f'_FULL_CONFIG 已包含 "{aten_name}"')
            continue

        # Find insertion point by alphabetical order of aten name
        insert_idx = config_end
        for i in range(config_start + 1, config_end):
            line_match = re.search(r'\(\s*"([^"]+)"', repo_lines[i])
            if line_match:
                existing_name = line_match.group(1)
                if aten_name < existing_name:
                    insert_idx = i
                    break
                insert_idx = i + 1

        indent = "    "
        repo_lines.insert(insert_idx, f"{indent}{entry}")
        config_end += 1
        inserted_names.add(aten_name)
        ok(f'_FULL_CONFIG 插入 "{aten_name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] __init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 6: operators.yaml
# ---------------------------------------------------------------------------


def insert_operators_yaml(op, worktree, repo, dry_run):
    section("Step 6: operators.yaml")
    op_id = get_op_id(op)
    repo_yaml = os.path.join(repo, "conf/operators.yaml")
    wt_yaml = os.path.join(worktree, "conf/operators.yaml")

    with open(repo_yaml) as f:
        repo_data = yaml.safe_load(f)

    # Check if already exists
    existing_ids = [o.get("id") for o in repo_data.get("ops", [])]
    if op_id in existing_ids:
        ok(f"operators.yaml 已包含 id: {op_id}")
        # Still check inplace split below
    else:
        # Try to get entry from worktree yaml
        entry = None
        with open(wt_yaml) as f:
            wt_data = yaml.safe_load(f)
        for wt_op in wt_data.get("ops", []):
            wt_name = wt_op.get("name", wt_op.get("id", ""))
            if wt_name == op or wt_name == op_id:
                entry = dict(wt_op)
                if "name" in entry:
                    entry["id"] = op_id
                    del entry["name"]
                break

        if not entry:
            entry = {
                "id": op_id,
                "description": f"Triton kernel implementation for {op}.\n",
                "for": [op],
                "labels": ["aten", "KernelGen"],
                "kind": ["Math"],
                "stages": [{"alpha": "5.4"}],
            }
            warn(f"worktree yaml 无此算子，使用默认条目（description 需人工补充）")
        else:
            labels = entry.get("labels", [])
            if "KernelGen" not in labels:
                labels.append("KernelGen")
                entry["labels"] = labels
            entry["id"] = op_id
            stages = entry.get("stages", {})
            if isinstance(stages, dict):
                entry["stages"] = [{k: v} for k, v in stages.items()]
            ok(f"从 worktree yaml 提取条目")

        # Split: if entry's 'for' list contains both op and op_ (inplace), split them
        for_list = entry.get("for", [])
        inplace_items = [f for f in for_list if f.rstrip(".").endswith("_") and f.rstrip("_.") == op.rstrip("_")]
        non_inplace_items = [f for f in for_list if f not in inplace_items]

        if inplace_items and non_inplace_items:
            warn(f"检测到 for 列表同时包含 inplace 和非 inplace: {for_list}，自动拆分")
            entry["for"] = non_inplace_items
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)
            # Create separate inplace entry
            inplace_entry = dict(entry)
            inplace_id = op_id + "_"
            inplace_entry["id"] = inplace_id
            inplace_entry["description"] = f"The in-place version of `{op_id}()`."
            inplace_entry["for"] = inplace_items
            if inplace_id not in existing_ids:
                _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, existing_ids, dry_run)
                ok(f"已拆分 inplace 变体为独立条目: id={inplace_id}")
        else:
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)

    # Check _FULL_CONFIG for inplace variant not in yaml
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    if os.path.isfile(wt_init):
        with open(wt_init) as f:
            wt_content = f.read()
        inplace_op = op + "_" if not op.endswith("_") else None
        if inplace_op:
            inplace_id = get_op_id(inplace_op)
            inplace_pattern = rf'\(\s*"[^"]*{re.escape(inplace_op)}[^"]*"\s*,'
            if re.search(inplace_pattern, wt_content):
                # Reload to check current state
                with open(repo_yaml) as f:
                    current_data = yaml.safe_load(f)
                current_ids = [o.get("id") for o in current_data.get("ops", [])]
                if inplace_id not in current_ids:
                    inplace_entry = {
                        "id": inplace_id,
                        "description": f"The in-place version of `{op_id}()`.",
                        "for": [inplace_op],
                        "labels": ["aten", "KernelGen"],
                        "kind": ["Math"],
                        "stages": [{"alpha": "5.4"}],
                    }
                    _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, current_ids, dry_run)
                    ok(f"_FULL_CONFIG 注册了 inplace 变体，已生成独立 yaml 条目: {inplace_id}")


def _insert_yaml_entry(entry, repo_yaml, entry_id, existing_ids, dry_run):
    """Insert a single yaml entry in alphabetical order."""
    if entry_id in existing_ids:
        ok(f"yaml 已包含 id: {entry_id}，跳过")
        return

    with open(repo_yaml) as f:
        yaml_lines = f.readlines()

    insert_line = len(yaml_lines)
    i = 0
    while i < len(yaml_lines):
        match = re.match(r"\s*-\s*id:\s*(\S+)", yaml_lines[i])
        if match:
            existing_id = match.group(1)
            if entry_id < existing_id:
                insert_line = i
                break
        i += 1

    new_lines = []
    new_lines.append(f"  - id: {entry['id']}\n")
    desc = entry.get("description", "").strip()
    if "\n" in desc or len(desc) > 60:
        new_lines.append("    description: |\n")
        for dline in desc.split("\n"):
            new_lines.append(f"      {dline.strip()}\n")
    else:
        new_lines.append(f"    description: {desc}\n")
    new_lines.append("    for:\n")
    for item in entry.get("for", []):
        # special_* 算子 for 字段用 aten dispatch 格式: special.xxx
        if item.startswith("special_") and "." not in item:
            item = item.replace("special_", "special.", 1)
            warn(f"yaml for 自动修正: special_xxx → {item}")
        new_lines.append(f"      - {item}\n")
    new_lines.append("    labels:\n")
    for label in entry.get("labels", ["aten", "KernelGen"]):
        new_lines.append(f"      - {label}\n")
    new_lines.append("    kind:\n")
    for kind in entry.get("kind", ["Math"]):
        new_lines.append(f"      - {kind}\n")
    new_lines.append("    stages:\n")
    stages = entry.get("stages", [{"alpha": "5.4"}])
    if isinstance(stages, list):
        for s in stages:
            if isinstance(s, dict):
                for k, v in s.items():
                    new_lines.append(f"      - {k}: '{v}'\n")
    elif isinstance(stages, dict):
        for k, v in stages.items():
            new_lines.append(f"      - {k}: '{v}'\n")

    yaml_lines[insert_line:insert_line] = new_lines
    ok(f"yaml 插入 id: {entry_id} 在行 {insert_line + 1}")

    if dry_run:
        ok(f"[DRY] operators.yaml 将被更新 ({entry_id})")
    else:
        with open(repo_yaml, "w") as f:
            f.writelines(yaml_lines)
        ok(f"operators.yaml 已更新 ({entry_id})")




# ---------------------------------------------------------------------------
# Canonical rename
# ---------------------------------------------------------------------------


def _replace_tokens(content, plan):
    replacements = []
    for old in [
        plan.source_name,
        plan.impl_name,
        plan.source_op_id,
        plan.impl_op_id,
    ]:
        if old and old != plan.canonical_name and old != plan.canonical_op_id:
            replacements.append((old, plan.canonical_name))

    result = content
    # Longer tokens first so Cross_Attention is replaced before cross_attention-like substrings.
    for old, new in sorted(set(replacements), key=lambda item: len(item[0]), reverse=True):
        result = result.replace(old, new)
    return result


def canonicalize_extracted_files(plan, repo, dry_run):
    """Rename generated source-name files and contents to the canonical name."""
    if not plan.renamed:
        return

    section("Step 7: 规范名重命名")
    ok(f"source_name: {plan.source_name}")
    ok(f"canonical_name: {plan.canonical_name}")

    source_files = [
        f"src/flag_gems/ops/{plan.source_name}.py",
        f"tests/test_{plan.impl_op_id}.py",
        f"benchmark/test_{plan.impl_op_id}.py",
        "src/flag_gems/ops/__init__.py",
        "src/flag_gems/__init__.py",
        "conf/operators.yaml",
    ]

    for relpath in source_files:
        full = os.path.join(repo, relpath)
        if not os.path.isfile(full):
            continue
        with open(full) as f:
            content = f.read()
        new_content = _replace_tokens(content, plan)
        if new_content != content:
            if dry_run:
                ok(f"[DRY] 将规范化内容: {relpath}")
            else:
                with open(full, "w") as f:
                    f.write(new_content)
                ok(f"已规范化内容: {relpath}")

    renames = [
        (
            f"src/flag_gems/ops/{plan.source_name}.py",
            f"src/flag_gems/ops/{plan.canonical_name}.py",
        ),
        (
            f"tests/test_{plan.impl_op_id}.py",
            f"tests/test_{plan.canonical_op_id}.py",
        ),
        (
            f"benchmark/test_{plan.impl_op_id}.py",
            f"benchmark/test_{plan.canonical_op_id}.py",
        ),
    ]

    for old_rel, new_rel in renames:
        old = os.path.join(repo, old_rel)
        new = os.path.join(repo, new_rel)
        if old == new or not os.path.isfile(old):
            continue
        if os.path.exists(new):
            fatal(f"规范名目标文件已存在，不能覆盖: {new_rel}")
        if dry_run:
            ok(f"[DRY] 将重命名: {old_rel} → {new_rel}")
        else:
            os.rename(old, new)
            ok(f"已重命名: {old_rel} → {new_rel}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="从 worktree 自动提取算子代码")
    parser.add_argument("operator", help="算子名称或规范名")
    parser.add_argument(
        "--repo-dir",
        default=os.environ.get("FLAGGEMS_REPO", DEFAULT_REPO),
    )
    parser.add_argument("--source-name", help="生成器/worktree 中的原始算子名")
    parser.add_argument("--canonical-name", help="最终提交使用的规范算子名")
    parser.add_argument("--impl-name", help="worktree 内部 wrapper/pytest mark/benchmark op_name")
    parser.add_argument("--dry-run", action="store_true", help="只预览不写入")
    args = parser.parse_args()

    repo = os.path.abspath(args.repo_dir)
    plan = build_name_plan(
        args.operator,
        repo,
        source_name=args.source_name,
        canonical_name=args.canonical_name,
        impl_name=args.impl_name,
    )
    source_op = plan.source_name
    impl_op = plan.impl_name
    canonical_op = plan.canonical_name
    canonical_op_id = get_op_id(canonical_op)
    worktree = plan.worktree_dir

    print(f"{Colors.BOLD}从 worktree 提取: {args.operator}{Colors.END}")
    print(f"source_name: {plan.source_name}")
    print(f"impl_name: {plan.impl_name}")
    print(f"canonical_name: {plan.canonical_name}")
    print(f"worktree: {worktree}")
    print(f"repo: {repo}")

    if plan.renamed:
        warn("检测到生成名和规范名不同，最终文件/注册将统一为规范名")

    if not os.path.isdir(worktree):
        fatal(f"worktree 不存在: {worktree}")

    extract_kernel(source_op, worktree, repo, args.dry_run)
    extract_test(impl_op, worktree, repo, args.dry_run)
    extract_benchmark(impl_op, worktree, repo, args.dry_run)
    insert_ops_init(source_op, worktree, repo, args.dry_run)
    insert_full_config(impl_op, worktree, repo, args.dry_run)
    insert_operators_yaml(impl_op, worktree, repo, args.dry_run)
    canonicalize_extracted_files(plan, repo, args.dry_run)

    if not args.dry_run:
        write_name_plan(repo, plan)

    print(f"\n{Colors.OK}{Colors.BOLD}✓ 6 个文件已准备完毕{Colors.END}")
    print(f"  src/flag_gems/ops/{canonical_op}.py")
    print(f"  src/flag_gems/ops/__init__.py")
    print(f"  src/flag_gems/__init__.py")
    print(f"  tests/test_{canonical_op_id}.py")
    print(f"  benchmark/test_{canonical_op_id}.py")
    print(f"  conf/operators.yaml")
    print(f"\n  接下来运行: CUDA_VISIBLE_DEVICES=<N> python scripts/submit_operator.py {canonical_op}")


if __name__ == "__main__":
    main()
