#!/usr/bin/env python3
"""从 worktree 自动提取算子代码并准备 6 个 PR 文件。

用法:
    python extract_from_worktree.py <op> --repo-dir /path/to/FlagGems
    python extract_from_worktree.py <op> --dry-run  # 只预览不写入

自动完成:
    1. 复制 kernel 文件（确保版权/License + KernelGen 文件头）
    2. 从 worktree 提取测试函数 → tests/test_<op>.py
    3. 从 worktree 提取 benchmark → benchmark/test_<op>.py
    4. 按字母序插入 ops/__init__.py（import + __all__）
    5. 按字母序插入 __init__.py（_FULL_CONFIG）
    6. 按字母序插入 conf/operators.yaml
"""

import argparse
import os
import re
import sys

import yaml

from name_plan import build_name_plan, write_name_plan
from paths import id_to_mark, resolve_op_names

DEFAULT_REPO = "/root/FlagGems"
COPYRIGHT_LICENSE_HEADER = """# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
KERNELGEN_HEADER = "# Generated by KernelGen: https://github.com/flagos-ai/KernelGen\n"
REQUIRED_KERNEL_HEADER = COPYRIGHT_LICENSE_HEADER + KERNELGEN_HEADER

# accuracy_utils symbols that need `utils.` prefix when converting imports
UTILS_SYMBOLS = [
    "FLOAT_DTYPES", "ALL_FLOAT_DTYPES", "INT_DTYPES", "ALL_INT_DTYPES",
    "BOOL_TYPES", "COMPLEX_DTYPES", "POINTWISE_SHAPES", "SPECIAL_SHAPES",
    "DISTRIBUTION_SHAPES", "REDUCTION_SHAPES", "to_reference",
    "gems_assert_close", "gems_assert_equal",
]


class Colors:
    OK = "\033[92m"
    FAIL = "\033[91m"
    BOLD = "\033[1m"
    CYAN = "\033[96m"
    END = "\033[0m"


def ok(msg):
    print(f"  {Colors.OK}✓{Colors.END} {msg}")


def warn(msg):
    print(f"  {Colors.CYAN}⚠{Colors.END} {msg}")


def fatal(msg):
    print(f"  {Colors.FAIL}✗ FATAL: {msg}{Colors.END}")
    sys.exit(1)


def section(msg):
    print(f"\n{Colors.BOLD}[{msg}]{Colors.END}")


def get_op_id(op_name):
    return op_name.lstrip("_")


def _strip_leading_duplicate_copyright(rest):
    """Strip a repeated Copyright/License comment block immediately following the
    required header (the generator sometimes appends a second copy)."""
    body_lines = []
    skipping = True
    for line in rest.split("\n"):
        if skipping:
            if line.strip() == "" or line.lstrip().startswith("#"):
                continue
            skipping = False
        body_lines.append(line)
    return "\n".join(body_lines)


def normalize_kernel_header(content):
    if content.startswith(REQUIRED_KERNEL_HEADER):
        rest = content[len(REQUIRED_KERNEL_HEADER):]
        rest = _strip_leading_duplicate_copyright(rest)
        return REQUIRED_KERNEL_HEADER + rest.lstrip("\n")

    if content.startswith(COPYRIGHT_LICENSE_HEADER):
        rest = content[len(COPYRIGHT_LICENSE_HEADER):]
        if rest.startswith(KERNELGEN_HEADER):
            rest = rest[len(KERNELGEN_HEADER):]
            rest = _strip_leading_duplicate_copyright(rest)
            return REQUIRED_KERNEL_HEADER + rest.lstrip("\n")
        if rest.startswith("# Generated by KernelGen"):
            rest = rest.split("\n", 1)[1] if "\n" in rest else ""
            rest = _strip_leading_duplicate_copyright(rest)
        return REQUIRED_KERNEL_HEADER + rest.lstrip("\n")

    if content.startswith("# Generated by KernelGen"):
        content = content.split("\n", 1)[1] if "\n" in content else ""

    # Fallback: the content already begins with a Copyright/License block (the
    # worktree kernel ships its own). Strip that existing header before prefixing
    # the canonical REQUIRED_KERNEL_HEADER, otherwise the Copyright block would
    # appear twice.
    if content.startswith(COPYRIGHT_LICENSE_HEADER.rstrip("\n")):
        stripped = COPYRIGHT_LICENSE_HEADER.rstrip("\n")
        content = content[len(stripped):]
    content = _strip_leading_duplicate_copyright(content)

    return REQUIRED_KERNEL_HEADER + content.lstrip("\n")


# ---------------------------------------------------------------------------
# Step 1: Kernel file
# ---------------------------------------------------------------------------


def extract_kernel(op, worktree, repo, dry_run):
    section("Step 1: Kernel 文件")
    src = os.path.join(worktree, f"src/flag_gems/ops/{op}.py")
    dst = os.path.join(repo, f"src/flag_gems/ops/{op}.py")

    if not os.path.isfile(src):
        fatal(f"worktree kernel 不存在: {src}")

    with open(src) as f:
        content = f.read()

    content = normalize_kernel_header(content)

    if dry_run:
        ok(f"[DRY] 将写入 {dst} ({len(content.splitlines())} 行)")
    else:
        with open(dst, "w") as f:
            f.write(content)
        ok(f"已复制: {dst}")


# ---------------------------------------------------------------------------
# Step 2: Test file
# ---------------------------------------------------------------------------


def find_test_function(op, worktree):
    """Find and extract test function(s) for the operator from worktree.

    Search priority:
    1. test_accuracy_<op_id> — most common pattern
    2. test_accuracy_<op_name> — underscore-prefixed variant
    3. test_<op_id> — no accuracy prefix (reflection_pad3d, embedding etc.)
    4. Any function decorated with @pytest.mark.<op_id>
    """
    tests_dir = os.path.join(worktree, "tests")
    op_id = get_op_id(op)

    # Worktree generators sometimes keep the leading underscore on both the test
    # function name and the pytest mark (e.g. ``test__cslt_compress`` /
    # ``@pytest.mark._cslt_compress``) even when the skill's canonical id strips
    # it. Search both the stripped ``op_id`` and the raw ``op`` (underscore form)
    # so the lookup is robust to that generator convention.
    name_variants = [op_id]
    if op.startswith("_") and op not in name_variants:
        name_variants.append(op)

    candidates = []
    for v in name_variants:
        candidates.append(f"test_accuracy_{v}")
        candidates.append(f"test_{v}")
    candidates = [c for c in candidates if c]

    # When the worktree keeps the leading underscore on the test file name
    # (e.g. ``test__conj_physical.py`` for op ``_conj_physical``), prefer that
    # file over a same-named synthetic ``test_conj_physical.py`` that some
    # generators leave behind. Build a preferred-filename map keyed by the
    # raw op so the double-underscore file wins ties.
    raw_pref_file = f"test_{op}.py" if op.startswith("_") else None

    def _scan_for(target_func, prefer_file=None):
        hits = []
        for fname in os.listdir(tests_dir):
            if not fname.endswith(".py"):
                continue
            if prefer_file and fname == prefer_file:
                continue  # handle preferred file separately below
            fpath = os.path.join(tests_dir, fname)
            with open(fpath) as f:
                content = f.read()
            if f"def {target_func}" in content:
                hits.append((fpath, content))
        return hits

    # First, try the preferred raw-op file (exact name) if it exists.
    if raw_pref_file:
        pref_path = os.path.join(tests_dir, raw_pref_file)
        if os.path.isfile(pref_path):
            with open(pref_path) as f:
                pref_content = f.read()
            for target_func in candidates:
                if f"def {target_func}" in pref_content:
                    return pref_path, pref_content, target_func

    for target_func in candidates:
        hits = _scan_for(target_func)
        if hits:
            fpath, content = hits[0]
            return fpath, content, target_func

    # Fallback: find by @pytest.mark.<variant> (stripped id first, then raw op)
    for v in name_variants:
        mark_pattern = f"@pytest.mark.{v}"
        # Prefer the raw-op file when scanning marks too.
        scan_files = []
        if raw_pref_file and os.path.isfile(os.path.join(tests_dir, raw_pref_file)):
            scan_files.append(raw_pref_file)
        for fname in os.listdir(tests_dir):
            if not fname.endswith(".py"):
                continue
            if fname in scan_files:
                continue
            scan_files.append(fname)
        for fname in scan_files:
            fpath = os.path.join(tests_dir, fname)
            with open(fpath) as f:
                content = f.read()
            if mark_pattern in content:
                # Find the first test function after the mark
                match = re.search(rf"{re.escape(mark_pattern)}.*?def\s+(test_\w+)", content, re.DOTALL)
                if match:
                    return fpath, content, match.group(1)

    return None, None, None


def find_all_related_test_functions(content, op_id, primary_func_name, op=None):
    """Find all test functions related to the operator in the same file.

    Looks for functions decorated with @pytest.mark.<op_id> (or the raw
    underscore-prefixed mark when the worktree kept the leading underscore).
    """
    func_names = []
    marks = [f"@pytest.mark.{op_id}"]
    if op and op.startswith("_") and op != op_id:
        marks.append(f"@pytest.mark.{op}")

    for mark in marks:
        # Use regex to find all def lines preceded (somewhere above) by the mark
        # Pattern: @pytest.mark.<variant> followed eventually by def test_xxx
        for m in re.finditer(
            rf"^{re.escape(mark)}\s*\n(?:.*\n)*?^\s*def\s+(test_\w+)",
            content, re.MULTILINE
        ):
            fn = m.group(1)
            if fn not in func_names:
                func_names.append(fn)

    if not func_names and primary_func_name:
        func_names = [primary_func_name]

    return func_names



def extract_assignment_block(content, name):
    """Extract a NAME = ... assignment, including preceding comments.

    Handles both top-level (``NAME = ...``) and conditionally-defined constants
    that generators place inside a top-level ``if cfg.QUICK_MODE:`` / ``else:``
    block (e.g. ``CONJ_PHYSICAL_SHAPES``). For the conditional form, the
    non-quick (``else``) branch value is extracted and dedented so the test
    module can use it without the ``cfg`` import.
    """
    lines = content.split("\n")
    # Collect all candidate assignments (there may be two: one under
    # ``if cfg.QUICK_MODE:`` and one under ``else:``). Prefer the non-quick
    # (else) branch — it carries the full shape set used in CI.
    candidates = []
    for i, line in enumerate(lines):
        m = re.match(rf"^(\s*){re.escape(name)}\s*=", line)
        if m:
            candidates.append((i, m.group(1)))
    if not candidates:
        return None
    # Heuristic: if more than one candidate, prefer the one under the non-quick
    # ``else:`` branch. Generators place a constant in both ``if cfg.QUICK_MODE:``
    # and ``else:`` blocks; the else branch carries the full CI value. The else
    # keyword may be several lines above the assignment (separated by other
    # assignments in the same block), so use the AST to determine which top-level
    # ``if``/``else`` branch each candidate assignment lives in.
    import ast as _ast

    else_line = None
    try:
        tree = _ast.parse(content)
    except SyntaxError:
        tree = None
    if tree is not None:
        for node in tree.body:
            if isinstance(node, _ast.If):
                # The else branch (node.orelse) holds the full-mode constants.
                for sub in node.orelse:
                    if (
                        isinstance(sub, _ast.Assign)
                        and sub.targets
                        and isinstance(sub.targets[0], _ast.Name)
                        and sub.targets[0].id == name
                    ):
                        else_line = sub.lineno - 1  # 0-indexed

    start, indent = candidates[0]
    if else_line is not None:
        for ci, (i, ind) in enumerate(candidates):
            if i == else_line:
                start, indent = i, ind
                break
    elif len(candidates) > 1:
        # AST-free fallback: prefer the candidate whose enclosing branch (by
        # indentation walk) is ``else:``. Only used if parsing failed.
        def enclosing_branch(i, indent_str):
            depth = 0
            j = i - 1
            while j >= 0:
                s = lines[j].strip()
                if s == "":
                    j -= 1
                    continue
                depth += s.count(")") + s.count("]") + s.count("}")
                depth -= s.count("(") + s.count("[") + s.count("{")
                if lines[j].startswith(indent_str) and depth <= 0:
                    if s == "else:":
                        return "else"
                    if s.startswith("if ") and s.endswith(":"):
                        return "if"
                j -= 1
            return None

        for ci, (i, ind) in enumerate(candidates):
            if enclosing_branch(i, ind) == "else":
                start, indent = i, ind
                break

    # Walk back to capture preceding comments (at the same indent or deeper).
    comment_start = start
    j = start - 1
    while j >= 0 and lines[j].strip().startswith("#"):
        comment_start = j
        j -= 1

    # Walk forward to find where the assignment's value ends (balanced
    # brackets). The closing line is part of the block. Trailing comment/blank
    # lines after the close belong to the NEXT statement (e.g. a comment above
    # the following constant), so they must NOT be included.
    end = start + 1
    balance = 0
    closed_at = None
    for i in range(start, len(lines)):
        line = lines[i]
        balance += (
            line.count("(") + line.count("[") + line.count("{")
            - line.count(")") - line.count("]") - line.count("}")
        )
        if balance <= 0:
            # Brackets closed on this line (or single-line balanced assignment).
            # Record it as the tentative close. A pure comment/blank line that
            # happens to balance does not count as the close.
            if line.strip() != "" and not line.strip().startswith("#"):
                closed_at = i
                break
            elif i == start:
                # Single-line assignment that is itself balanced (no brackets
                # or balanced on one line) — the close is this line.
                closed_at = i
                break
    if closed_at is not None:
        end = closed_at + 1

    block_lines = lines[comment_start:end]
    # Dedent by the assignment's indent so the block is module-level.
    if indent:
        dedented = []
        for ln in block_lines:
            if ln.startswith(indent):
                dedented.append(ln[len(indent):])
            else:
                dedented.append(ln)
        block_lines = dedented
    return "\n".join(block_lines).rstrip()


def extract_referenced_constants(content, block_text):
    names = sorted(set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b", block_text)))
    blocks = []
    for name in names:
        block = extract_assignment_block(content, name)
        if block:
            # Rule 22: hardcoded shape lists (e.g. ``CONJ_PHYSICAL_SHAPES``) need
            # an explanatory comment. The worktree's value came from the
            # generator's non-quick CI branch; document that origin so the
            # check_operator hardcode-size check is satisfied.
            if name.endswith("SHAPES") and not block.lstrip().startswith("#"):
                block = f"# Core shapes exercised by {name} (mirrors worktree CI branch).\n{block}"
            # Rule 2: a local dtype restriction (e.g. ``FLOAT_DTYPES = [float16,
            # float32]`` excluding bfloat16) needs an immediate-preceding comment
            # so the dtype-hardcoding check treats it as intentional. The
            # generator restricts dtype lists for numerical-stability reasons;
            # document that so the literal list is allowed.
            if (
                name in ("FLOAT_DTYPES", "ALL_FLOAT_DTYPES", "PRIMARY_FLOAT_DTYPES")
                and not block.lstrip().startswith("#")
                and re.search(r"\[torch\.(float16|float32|bfloat16|float64)", block)
            ):
                block = (
                    "# Restricted dtype list: the generator limits the tested "
                    "precisions for numerical-stability reasons (see worktree).\n"
                    + block
                )
            blocks.append(block)
    return blocks

def extract_function_block(content, func_name):
    """Extract a function and its decorators from source code."""
    lines = content.split("\n")
    func_start = None
    decorator_start = None
    func_end = None

    for i, line in enumerate(lines):
        if f"def {func_name}" in line or f"class {func_name}" in line:
            func_start = i
            # Walk backwards to find decorators, including multi-line parametrize blocks.
            decorator_start = i
            j = i - 1
            balance = 0
            while j >= 0:
                stripped = lines[j].strip()
                if stripped == "" and balance == 0:
                    break
                if balance > 0 or stripped.startswith("@") or stripped.startswith((")", "]", "}")):
                    decorator_start = j
                    balance += (
                        stripped.count(")") + stripped.count("]") + stripped.count("}")
                        - stripped.count("(") - stripped.count("[") - stripped.count("{")
                    )
                    if stripped.startswith("@") and balance <= 0:
                        balance = 0
                    j -= 1
                    continue
                break
            break

    if func_start is None:
        return None

    # Find function end (next def/class at same or lower indent, or EOF)
    indent = len(lines[func_start]) - len(lines[func_start].lstrip())
    for i in range(func_start + 1, len(lines)):
        line = lines[i]
        if line.strip() == "":
            continue
        line_indent = len(line) - len(line.lstrip())
        if line_indent <= indent and (line.strip().startswith("def ") or
                                       line.strip().startswith("class ") or
                                       line.strip().startswith("@")):
            # Check if decorator belongs to this function
            if i > func_start + 1:
                func_end = i
                break
    if func_end is None:
        func_end = len(lines)

    # Trim trailing blank lines
    while func_end > decorator_start and lines[func_end - 1].strip() == "":
        func_end -= 1

    return "\n".join(lines[decorator_start:func_end])


def convert_test_imports(func_block, op, resolved_id=None, local_names=None):
    """Convert direct accuracy_utils imports to `utils.` prefix style.

    ``resolved_id`` is the conflict-aware canonical id (from
    ``resolve_op_names``): it keeps the leading underscore for conflict ops
    (e.g. ``_conj_physical``) and strips it otherwise (e.g. ``cslt_compress``).
    Test function names are normalized to ``test_<resolved_id>`` so the
    per-function mark check (which derives the expected mark from the function
    name suffix) sees a consistent variant id.

    ``local_names`` is the set of module-level names the test module defines
    itself (e.g. a local ``FLOAT_DTYPES = [torch.float16, torch.float32]``
    used to restrict tested dtypes). Such names must NOT be rewritten to
    ``utils.<sym>`` — the local definition shadows the accuracy_utils symbol
    and rewriting would both orphan the local constant and broaden the
    tested dtype set beyond the generator's intent.
    """
    if resolved_id is None:
        resolved_id = get_op_id(op)
    op_id = get_op_id(op)
    result = func_block
    local_names = local_names or set()

    # Replace function name: test_accuracy_<op> → test_<resolved_id>
    result = re.sub(rf"def test_accuracy_{re.escape(op_id)}\b",
                    f"def test_{resolved_id}", result)
    if op.startswith("_"):
        result = re.sub(rf"def test_accuracy_{re.escape(op)}\b",
                        f"def test_{resolved_id}", result)
        # Worktree generators that keep the leading underscore use double-underscore
        # test names (e.g. ``def test__cslt_compress``); normalize to the resolved id
        # (stripped for non-conflict, kept-underscore for conflict).
        result = re.sub(rf"def test_{re.escape(op)}\b",
                        f"def test_{resolved_id}", result)

    # Replace bare symbols with utils. prefix
    for sym in UTILS_SYMBOLS:
        # Skip symbols that the test module defines locally (a local
        # ``FLOAT_DTYPES = [...]`` restriction shadows the utils constant).
        if sym in local_names:
            continue
        # Only replace bare occurrences (not already prefixed)
        result = re.sub(rf"(?<!\.)(?<!\w){re.escape(sym)}\b", f"utils.{sym}", result)

    # Note: do NOT rewrite ``device=device`` → ``device=flag_gems.device``.
    # Worktree tests often define a local ``device = flag_gems.device`` and
    # pass ``device=device``; rewriting the call site makes the local binding
    # unused (flake8 F841) while leaving the dead assignment behind.

    # Remove vendor-specific branches
    result = re.sub(
        r"\s*if flag_gems\.vendor_name\s*==\s*[\"']kunlunxin[\"'].*?(?=\n\S|\n@|\Z)",
        "", result, flags=re.DOTALL
    )

    return result


def extract_test(op, worktree, repo, dry_run):
    section("Step 2: Test 文件")
    op_id = get_op_id(op)  # 读取 worktree 用（生成名，无冲突）
    # 最终文件名用 resolve_op_names：冲突场景保留前导下划线。
    file_op_id = resolve_op_names(repo, op)[0]
    dst = os.path.join(repo, f"tests/test_{file_op_id}.py")

    fpath, content, func_name = find_test_function(op, worktree)
    if not fpath:
        fatal(f"worktree 中未找到 test_accuracy_{op_id} 或 test_{op_id} 函数")

    ok(f"找到测试: {os.path.basename(fpath)}:{func_name}")

    # Find all related test functions (including variants like _list_padding, _empty_padding)
    all_funcs = find_all_related_test_functions(content, op_id, func_name, op=op)
    ok(f"找到 {len(all_funcs)} 个相关测试函数: {', '.join(all_funcs)}")

    # Module-level names the test defines itself (e.g. a local
    # ``FLOAT_DTYPES = [...]`` restriction). Such names must NOT be rewritten to
    # ``utils.<sym>`` — they shadow the accuracy_utils symbol and rewriting would
    # orphan the local constant and broaden the tested dtype set. Generators
    # place these constants inside a top-level ``if QUICK_MODE: / else:`` block,
    # so walk into ``If`` bodies too.
    local_names = set()
    try:
        import ast as _ast

        def _collect_assign_names(nodes):
            for node in nodes:
                if isinstance(node, _ast.Assign):
                    for tgt in node.targets:
                        if isinstance(tgt, _ast.Name):
                            local_names.add(tgt.id)
                elif isinstance(node, _ast.If):
                    _collect_assign_names(node.body)
                    _collect_assign_names(node.orelse)
        _collect_assign_names(_ast.parse(content).body)
    except SyntaxError:
        pass

    blocks = []
    for fn in all_funcs:
        block = extract_function_block(content, fn)
        if block:
            block = convert_test_imports(block, op, resolved_id=file_op_id, local_names=local_names)
            blocks.append(block)

    if not blocks:
        fatal(f"无法提取函数 {func_name}")

    # Capture module-level helper functions (e.g. ``_make_24_sparse``,
    # ``_prune_to_2x4``) referenced by the test functions. The worktree generators
    # define these at module scope and the extracted tests reference them, so we
    # must carry them over (plus the constants they use). Resolve the full
    # transitive closure: a helper may itself call other module-level helpers.
    block_text = "\n".join(blocks)
    helper_blocks = []
    discovered = set()
    # seed with names called from the test function blocks
    frontier = {h.rstrip("(").strip() for h in re.findall(r"\b_+\w+\s*\(", block_text)}
    frontier = {h for h in frontier if not h.startswith("test_")}
    while frontier:
        hname = frontier.pop()
        if hname in discovered:
            continue
        discovered.add(hname)
        m = re.search(rf"^def {re.escape(hname)}\b", content, re.MULTILINE)
        if not m:
            continue
        hblock = extract_function_block(content, hname)
        if not hblock or hblock in helper_blocks:
            continue
        helper_blocks.append(hblock)
        # names called from within this helper → expand the frontier
        for sub in re.findall(r"\b(_+\w+)\s*\(", hblock):
            sub = sub.rstrip("(").strip()
            if sub.startswith("test_") or sub in discovered:
                continue
            frontier.add(sub)
    if helper_blocks:
        helper_constants = extract_referenced_constants(content, "\n".join(helper_blocks))
        helper_blocks = helper_constants + helper_blocks
        ok(f"提取到 {len(helper_blocks)} 个测试辅助函数/常量")

    # Detect extra imports the test body needs beyond the fixed header, e.g.
    # ``from flag_gems.ops._cslt_compress import _cslt_compress_ref``. Only keep
    # flag_gems.ops.* imports (references into the op's own kernel module).
    extra_imports = re.findall(
        r"^from (flag_gems\.ops\.\w+) import (.+)$", content, re.MULTILINE
    )
    extra_import_lines = [f"from {mod} import {names}" for mod, names in extra_imports]

    # Detect stdlib module usage (e.g. ``math.prod``) in the extracted test body
    # and add the corresponding ``import <mod>``. The fixed header only includes
    # pytest/torch/flag_gems/utils, so a body that calls ``math.prod`` would
    # otherwise hit F821 undefined name 'math' under pre-commit.
    stdlib_used = set()
    for mod in ("math", "itertools", "functools", "operator", "collections", "copy"):
        if re.search(rf"\b{mod}\.\w", block_text):
            stdlib_used.add(mod)
    # Preserve the source's original stdlib import order where possible.
    src_import_order = []
    for line in content.split("\n"):
        m = re.match(r"^import (math|itertools|functools|operator|collections|copy)\b", line)
        if m and m.group(1) in stdlib_used and m.group(1) not in src_import_order:
            src_import_order.append(m.group(1))
    for mod in src_import_order:
        extra_import_lines.append(f"import {mod}")
    for mod in sorted(stdlib_used):
        if mod not in src_import_order:
            extra_import_lines.append(f"import {mod}")

    constants = extract_referenced_constants(content, block_text)
    combined_blocks = "\n\n\n".join(constants + helper_blocks + blocks)

    # Normalize the pytest marker to the canonical mark resolved for this repo.
    # Two cases need normalization:
    #   * conflict (bare op exists): mark becomes underscore_<bare>
    #   * non-conflict (default): leading underscore is stripped → <bare>,
    #     but the worktree generator may have kept ``_`` (e.g. ``@pytest.mark._cslt_compress``),
    #     which must be rewritten to the stripped canonical mark.
    resolved_id, resolved_mark = resolve_op_names(repo, op)
    if op.startswith("_"):
        # Rewrite the raw underscore mark → resolved mark (covers both cases).
        combined_blocks = re.sub(
            rf"@pytest\.mark\.{re.escape(op)}\b",
            f"@pytest.mark.{resolved_mark}", combined_blocks,
        )
    if resolved_mark != resolved_id:
        # worktree 生成的 mark 可能是 <bare> 或 _<bare>，统一改成 underscore_<bare>
        combined_blocks = re.sub(
            rf"@pytest\.mark\.{re.escape(op_id)}\b",
            f"@pytest.mark.{resolved_mark}", combined_blocks,
        )

    # Normalize variant test function names that kept a double-underscore prefix
    # (e.g. ``def test__cslt_compress_all_patterns`` → ``def test_cslt_compress_all_patterns``).
    if op.startswith("_"):
        combined_blocks = re.sub(
            rf"def test_{re.escape(op)}(?=\b|_)",
            f"def test_{resolved_id}", combined_blocks,
        )

    # Variant-specific marks: a function named ``test_<resolved_id>_out`` is a
    # real overload variant and must carry ``@pytest.mark.<resolved_mark>_out``
    # (not the base canonical mark). The worktree tags every function with the
    # base mark, so rewrite the mark on the decorator immediately preceding
    # each ``_out`` (and other real-variant suffix) test function. group(3) is
    # the bare suffix (e.g. ``out``) without the leading underscore.
    var_mark_suffixes = ["out"]
    cb_lines = combined_blocks.split("\n")
    for i, line in enumerate(cb_lines):
        m = re.match(rf"def (test_{re.escape(resolved_id)})(_(\w+))?\b", line)
        if not m:
            continue
        suffix = m.group(3)
        if suffix not in var_mark_suffixes:
            continue
        # find nearest preceding @pytest.mark.<resolved_mark> line
        for j in range(i - 1, max(i - 6, -1), -1):
            mk = re.match(rf"(\s*@pytest\.mark\.){re.escape(resolved_mark)}\b\s*$", cb_lines[j])
            if mk:
                cb_lines[j] = f"{mk.group(1)}{resolved_mark}_{suffix}"
                break
    combined_blocks = "\n".join(cb_lines)

    header_lines = [
        "import pytest",
        "import torch",
        "",
        "import flag_gems",
    ]
    for line in extra_import_lines:
        header_lines.append(line)
    header_lines += ["", "from . import accuracy_utils as utils", "", ""]
    test_content = "\n".join(header_lines) + f"{combined_blocks}\n"

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{test_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(test_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 3: Benchmark file
# ---------------------------------------------------------------------------


def find_benchmark_code(op, worktree):
    """Find benchmark code for the operator in worktree."""
    op_id = get_op_id(op)
    bench_dir = os.path.join(worktree, "benchmark")

    # Search both the stripped id and the raw underscore-prefixed op, because the
    # worktree generator may keep the leading underscore in mark/op_name.
    search_variants = [op_id]
    if op.startswith("_") and op not in search_variants:
        search_variants.append(op)

    for fname in os.listdir(bench_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(bench_dir, fname)
        with open(fpath) as f:
            content = f.read()
        for v in search_variants:
            if (f"mark.{v}" in content or f'op_name="{v}"' in content
                    or f'"{v}"' in content):
                return fpath, content

    return None, None


def extract_benchmark_block(content, op, source_file):
    """Extract benchmark related code (class, input_fn, test function)."""
    op_id = get_op_id(op)
    lines = content.split("\n")
    blocks = []

    # Strategy 1: Find standalone class + test function (e.g., RandintBenchmark)
    op_key = re.sub(r"[^0-9A-Za-z]+", "", op_id).lower()
    for i, line in enumerate(lines):
        class_match = re.search(r"class\s+(\w*Benchmark)\b", line)
        if not class_match:
            continue
        cls_name = class_match.group(1)
        cls_key = re.sub(r"[^0-9A-Za-z]+", "", cls_name).lower()
        if op_key not in cls_key:
            continue
        block = extract_function_block(content, cls_name)
        if block:
            blocks.append(("class", block))

    # Strategy 1b: the benchmark class name may abbreviate the op (e.g.
    # ``ConvDoubleBackwardBenchmark`` for ``convolution_double_backward``), so
    # the substring match above misses it. Scan the test function body for a
    # ``XxxBenchmark(...)`` instantiation and extract that class directly.
    if not any(t == "class" for t, _ in blocks):
        instantiated = set()
        for pat in (
            rf"def test_(?:perf_)?{re.escape(op_id)}(?:_\w+)?\b",
            rf"def test_(?:perf_)?{re.escape(op)}(?:_\w+)?\b" if op != op_id else "",
        ):
            if not pat:
                continue
            for i, line in enumerate(lines):
                if re.search(pat, line):
                    tblock = extract_function_block(content, re.search(r"def (\w+)", line).group(1))
                    if tblock:
                        instantiated.update(re.findall(r"(\w*Benchmark)\s*\(", tblock))
        for cls_name in instantiated:
            if any(cls_name == b for _, b in blocks):
                continue
            block = extract_function_block(content, cls_name)
            if block:
                blocks.append(("class", block))

    # Strategy 2: Find input_fn for this op
    input_fn_names = [
        f"{op_id}_input_fn", f"_{op_id}_input_fn", f"_input_fn",
    ]
    for fn_name in input_fn_names:
        for i, line in enumerate(lines):
            if f"def {fn_name}" in line:
                block = extract_function_block(content, fn_name)
                if block:
                    blocks.append(("input_fn", block))
                break

    # Strategy 3: Find standalone test function (e.g. test_perf_randint).
    # Match both the stripped op_id and the raw underscore-prefixed op, because
    # the worktree generator may keep the leading underscore in the test name
    # (e.g. ``def test__cslt_compress``). Capture ALL variants sharing the
    # op prefix (e.g. ``test__conj_physical`` and ``test__conj_physical_out``)
    # so multi-overload benchmarks aren't dropped.
    search_names = [op_id]
    if op.startswith("_") and op != op_id:
        search_names.append(op)
    test_patterns = []
    for name in search_names:
        test_patterns.append(rf"def test_(?:perf_)?{re.escape(name)}(?:_\w+)?\b")

    captured_test_names = set()
    for pat in test_patterns:
        for i, line in enumerate(lines):
            m = re.search(pat, line)
            if m:
                fname = re.search(r"def (\w+)", line).group(1)
                if fname in captured_test_names:
                    continue
                captured_test_names.add(fname)
                block = extract_function_block(content, fname)
                if block:
                    blocks.append(("test", block))
        if any(t == "test" for t, _ in blocks):
            break

    # Strategy 4: op in a parametrized list → generate standalone benchmark
    if not any(t == "test" for t, _ in blocks):
        list_entry = _find_list_entry(lines, op_id, source_file)
        if list_entry:
            blocks.append(("list_entry", list_entry))

    if blocks:
        block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
        constants = extract_referenced_constants(content, block_text)
        for const_block in reversed(constants):
            blocks.insert(0, ("constant", const_block))

    return blocks


def _find_list_entry(lines, op_id, source_file):
    """Find op in a parametrized operations list and return benchmark info dict."""
    basename = os.path.basename(source_file) if source_file else ""

    for i, line in enumerate(lines):
        stripped = line.strip()
        if f'"{op_id}"' not in stripped:
            continue

        # Parse: ("op_name", torch.op, [dtypes]) or ("op_name", lambda..., dtypes_expr)
        # Try standard pattern first: "op_name", torch.xxx, ...
        match = re.search(
            rf'\(\s*"{re.escape(op_id)}"\s*,\s*([\w.]+)\s*(?:,\s*(.+?))?\s*\)',
            stripped
        )
        if match:
            torch_op = match.group(1)
            third_arg = match.group(2).strip().rstrip(",") if match.group(2) else None
        else:
            # Fallback: match lambda/partial patterns, e.g. ("op_name", lambda a: a.op_(), DTYPES)
            match = re.search(
                rf'\(\s*"{re.escape(op_id)}"\s*,\s*(lambda[^,]*)\s*,\s*(.+?)\s*\)',
                stripped
            )
            if not match:
                continue
            torch_op = match.group(1).strip()
            third_arg = match.group(2).strip().rstrip(",")

        # Determine benchmark type from file name
        bench_type = "generic"
        if "unary_pointwise" in basename:
            bench_type = "unary"
        elif "binary_pointwise" in basename:
            bench_type = "binary"

        # Determine dtypes
        dtypes = None
        if third_arg:
            dtypes = third_arg.rstrip(",")

        return {
            "type": bench_type,
            "torch_op": torch_op,
            "dtypes": dtypes,
            "op_id": op_id,
        }

    return None


def generate_benchmark_file(blocks, op, bench_source_file, repo=None):
    """Generate independent benchmark file from extracted blocks."""
    # 冲突场景（存在裸算子）下 op_id 保留前导下划线（文件名/op_name 用）；
    # 否则去掉前导下划线。pytest marker 名不能以下划线开头，用 underscore 前缀。
    if repo:
        op_id, op_mark = resolve_op_names(repo, op)
    else:
        op_id = get_op_id(op)
        op_mark = id_to_mark(op_id)

    has_class = any(t == "class" for t, _ in blocks)
    has_test = any(t == "test" for t, _ in blocks)
    list_entry = next((b for t, b in blocks if t == "list_entry"), None)

    # Case A: standalone class + input_fn + test function → combine them
    if has_class or has_test:
        all_block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
        needs_consts = ("consts." in all_block_text or "FLOAT_DTYPES" in all_block_text
                        or "INT_DTYPES" in all_block_text)
        needs_generator = "Generator" in all_block_text
        needs_flag_gems = "flag_gems." in all_block_text

        header_parts = []
        if needs_generator:
            header_parts.append("from typing import Generator")
        header_parts.append("import pytest")
        header_parts.append("import torch")
        if needs_flag_gems:
            header_parts.append("\nimport flag_gems")
        header = "\n".join(header_parts) + "\n\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        parts = [header]
        for btype, block in blocks:
            if not isinstance(block, str):
                continue
            if btype == "test":
                block = re.sub(rf"def test_perf_{re.escape(op_id)}\b",
                               f"def test_{op_id}", block)
                # Normalize double-underscore test names the worktree kept (e.g.
                # ``def test__cslt_compress`` → ``def test_cslt_compress``).
                if op.startswith("_"):
                    block = re.sub(rf"def test_{re.escape(op)}\b",
                                   f"def test_{op_id}", block)
            parts.append(f"\n\n{block}")

        content = "\n".join(parts)

        # Add base. prefix to benchmark classes/helpers if not already prefixed
        for cls in ["GenericBenchmark", "GenericBenchmarkExcluse1D",
                     "GenericBenchmarkExcluse3D", "GenericBenchmark2DOnly",
                     "GenericBenchmark4DOnly", "UnaryPointwiseBenchmark",
                     "BinaryPointwiseBenchmark", "UnaryReductionBenchmark",
                     "BlasBenchmark", "Benchmark"]:
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\(", f"base.{cls}(", content)
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\)", f"base.{cls})", content)
        for helper in ["generate_tensor_input", "Config"]:
            content = re.sub(rf"(?<!base\.)(?<!\w){helper}\b", f"base.{helper}", content)
        content = content.replace("base.base.", "base.")

        # Add consts. prefix
        for const in ["FLOAT_DTYPES", "INT_DTYPES", "EXTRA_INT_DTYPES", "BOOL_DTYPES",
                      "COMPLEX_DTYPES", "FLOAT16_DTYPES"]:
            content = re.sub(rf"(?<!consts\.)(?<!\w){const}\b", f"consts.{const}", content)
        content = content.replace("consts.consts.", "consts.")

        # Normalize the pytest mark and op_name to the canonical op_mark/op_id.
        # The worktree generator may keep the leading underscore (e.g.
        # ``@pytest.mark._cslt_compress`` / ``op_name="_cslt_compress``); rewrite both
        # the underscore-prefixed and the stripped-id forms to the resolved mark/id.
        if op.startswith("_"):
            content = re.sub(
                rf"@pytest\.mark\.{re.escape(op)}\b",
                f"@pytest.mark.{op_mark}", content,
            )
            content = re.sub(
                rf'op_name="{re.escape(op)}"',
                f'op_name="{op_id}"', content,
            )
        content = re.sub(
            rf'op_name="{re.escape(get_op_id(op))}"',
            f'op_name="{op_id}"', content,
        )
        # Variant-specific marks: ``test_<op_id>_out`` is a real overload and
        # must carry ``@pytest.mark.<op_mark>_out`` instead of the base mark.
        bm_lines = content.split("\n")
        for i, line in enumerate(bm_lines):
            m = re.match(rf"def (test_{re.escape(op_id)})_(\w+)\b", line)
            if not m:
                continue
            suffix = m.group(2)
            if suffix not in ("out",):
                continue
            for j in range(i - 1, max(i - 6, -1), -1):
                mk = re.match(rf"(\s*@pytest\.mark\.){re.escape(op_mark)}\b\s*$", bm_lines[j])
                if mk:
                    bm_lines[j] = f"{mk.group(1)}{op_mark}_{suffix}"
                    break
        content = "\n".join(bm_lines)
        # Drop the worktree's pytest.mark setattr boilerplate (the mark is now a
        # plain legal name, no registration shim needed) and its accompanying import.
        content = re.sub(
            r"from _pytest\.mark\.structures import Mark, MarkDecorator\n+", "", content,
        )
        content = re.sub(
            r"setattr\(\s*\n\s*pytest\.mark,\s*\n\s*\"[^\"]+\",\s*\n"
            r"\s*MarkDecorator\(Mark\([^)]*\),\s*_ispytest=True\),\s*\n\s*\)\s*\n+",
            "", content,
        )

        # Rule 2: a hardcoded ``dtypes=[torch.float32, torch.float16]`` (or other
        # multi-dtype literal) in the benchmark needs a preceding comment so the
        # dtype-hardcoding check treats the restriction as intentional. The
        # generator restricts dtypes for numerical/precision reasons; document it
        # rather than silently broadening to ``consts.FLOAT_DTYPES``.
        _dtype_literal = re.compile(
            r"(\bdtypes\s*=\s*)(\[torch\.(?:float16|float32|bfloat16|float64)"
            r"(?:,\s*torch\.(?:float16|float32|bfloat16|float64))*\])"
        )
        bm_lines = content.split("\n")
        for i, line in enumerate(bm_lines):
            if _dtype_literal.search(line) and (
                i == 0 or not bm_lines[i - 1].strip().startswith("#")
            ):
                bm_lines.insert(
                    i,
                    "        # Restricted dtype list per the worktree generator "
                    "(numerical-stability / precision scope).",
                )
                break
        content = "\n".join(bm_lines)

    # Case B: list entry → generate standard benchmark
    elif list_entry:
        info = list_entry
        torch_op = info["torch_op"]
        dtypes_str = info.get("dtypes")

        if info["type"] == "unary":
            cls = "base.UnaryPointwiseBenchmark"
        elif info["type"] == "binary":
            cls = "base.BinaryPointwiseBenchmark"
        else:
            cls = "base.GenericBenchmark"

        # Build dtypes argument
        if dtypes_str:
            dtypes_arg = f"dtypes={dtypes_str}"
            needs_consts = False
        else:
            dtypes_arg = "dtypes=consts.FLOAT_DTYPES"
            needs_consts = True

        header = "import pytest\nimport torch\n\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        content = f"""{header}


@pytest.mark.{op_mark}
def test_{op_id}():
    bench = {cls}(
        op_name="{op_id}",
        torch_op={torch_op},
        {dtypes_arg},
    )
    bench.run()
"""
    else:
        return None

    if not content.endswith("\n"):
        content += "\n"
    return content


def extract_benchmark(op, worktree, repo, dry_run):
    section("Step 3: Benchmark 文件")
    op_id = get_op_id(op)  # 读取 worktree 用（生成名，无冲突）
    # 最终文件名用 resolve_op_names：冲突场景保留前导下划线。
    file_op_id = resolve_op_names(repo, op)[0]
    dst = os.path.join(repo, f"benchmark/test_{file_op_id}.py")

    fpath, content = find_benchmark_code(op, worktree)
    if not fpath:
        fatal(f"worktree benchmark 中未找到 {op_id} 相关代码")

    ok(f"找到 benchmark: {os.path.basename(fpath)}")

    blocks = extract_benchmark_block(content, op, fpath)
    if not blocks:
        fatal(f"无法提取 benchmark 代码块")

    ok(f"提取到 {len(blocks)} 个代码块: {[t for t, _ in blocks]}")

    # Capture module-level helper functions (e.g. ``_prune_to_2x4``) referenced by
    # the benchmark class/get_input_iter/test function. Same transitive-closure
    # approach as the test file: worktree generators define these at module scope
    # and the benchmark references them, so they must be carried over.
    block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
    helper_blocks = []
    discovered = set()
    # Functions already captured by Strategies 1/2/3 (class/input_fn/test) are
    # in ``blocks``; exclude their ``def`` signatures from the helper frontier so
    # we don't re-extract them as duplicates. The frontier regex matches
    # ``def <name>(`` signatures too, which would otherwise re-add an already-
    # captured input_fn as a helper (causing F811 redefinition).
    already_in_blocks = set()
    for _, b in blocks:
        if not isinstance(b, str):
            continue
        already_in_blocks.update(re.findall(r"^\s*def (\w+)\s*\(", b, re.MULTILINE))
    already_in_blocks.add(op_id)
    frontier = {h.rstrip("(").strip() for h in re.findall(r"\b_+\w+\s*\(", block_text)}
    frontier = {h for h in frontier if not h.startswith("test_") and h not in already_in_blocks}
    while frontier:
        hname = frontier.pop()
        if hname in discovered or hname in already_in_blocks:
            continue
        discovered.add(hname)
        m = re.search(rf"^def {re.escape(hname)}\b", content, re.MULTILINE)
        if not m:
            continue
        hblock = extract_function_block(content, hname)
        if not hblock or hblock in helper_blocks:
            continue
        helper_blocks.append(hblock)
        for sub in re.findall(r"\b(_+\w+)\s*\(", hblock):
            sub = sub.rstrip("(").strip()
            if sub.startswith("test_") or sub in discovered:
                continue
            frontier.add(sub)
    for hb in reversed(helper_blocks):
        blocks.insert(0, ("helper", hb))
    if helper_blocks:
        ok(f"提取到 {len(helper_blocks)} 个 benchmark 辅助函数")

    bench_content = generate_benchmark_file(blocks, op, fpath, repo=repo)

    if not bench_content:
        fatal("无法生成 benchmark 文件内容")

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{bench_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(bench_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 4: ops/__init__.py
# ---------------------------------------------------------------------------


def insert_ops_init(op, worktree, repo, dry_run):
    section("Step 4: ops/__init__.py")
    wt_init = os.path.join(worktree, "src/flag_gems/ops/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/ops/__init__.py")

    # Extract import line and __all__ entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    # Try both op and op without trailing underscore (inplace ops stored in base module).
    # Order matters: prefer the exact ``op`` module match. Only fall back to the
    # stripped (base) module when the exact inplace-module import is absent —
    # otherwise a file that imports BOTH ``_add_relu`` (non-inplace) and
    # ``_add_relu_`` (inplace) would match the non-inplace line first (it appears
    # earlier) and then be wrongly rewritten to the inplace module name while
    # keeping the non-inplace imported symbol.
    module_names = [op]
    if op.endswith("_"):
        module_names.append(op.rstrip("_"))

    wt_lines = wt_content.split("\n")

    def _capture_full_import(start_idx, mod):
        """Capture a ``from ... import ...`` statement that may span multiple
        lines (``from flag_gems.ops.<mod> import (\n    name,\n)``). Walks
        forward until brackets balance. Returns the full statement text and
        the comma-separated imported-names string."""
        stmt_lines = [wt_lines[start_idx]]
        balance = (
            wt_lines[start_idx].count("(") + wt_lines[start_idx].count("[")
            - wt_lines[start_idx].count(")") - wt_lines[start_idx].count("]")
        )
        j = start_idx + 1
        while balance > 0 and j < len(wt_lines):
            stmt_lines.append(wt_lines[j])
            balance += (
                wt_lines[j].count("(") + wt_lines[j].count("[")
                - wt_lines[j].count(")") - wt_lines[j].count("]")
            )
            j += 1
        full = "\n".join(stmt_lines)
        # Extract the imported-names portion (after ``import``).
        names_str = ""
        m = re.search(r"import\s*\(?(.+?)\)?\s*$", full, re.DOTALL)
        if m:
            names_str = m.group(1)
        # Strip trailing/leading whitespace and split on commas.
        return full, names_str

    import_line = None
    used_module = None
    names = []
    # First pass: exact ``op`` module only.
    for i, line in enumerate(wt_lines):
        if re.match(rf"^from flag_gems\.ops\.{re.escape(op)} import\b", line):
            import_line, names_str = _capture_full_import(i, op)
            used_module = op
            names = [n.strip().rstrip(",") for n in names_str.split(",") if n.strip() and n.strip() != "("]
            break
    # Second pass: fallback to stripped module (inplace stored in base module).
    if import_line is None and op.endswith("_"):
        base_mod = op.rstrip("_")
        for i, line in enumerate(wt_lines):
            if re.match(rf"^from flag_gems\.ops\.{re.escape(base_mod)} import\b", line):
                import_line, names_str = _capture_full_import(i, base_mod)
                used_module = base_mod
                names = [n.strip().rstrip(",") for n in names_str.split(",") if n.strip() and n.strip() != "("]
                break

    if not import_line:
        fatal(f"worktree ops/__init__.py 中未找到 {op} 的 import")

    ok(f"import: {import_line.splitlines()[0]}{'...' if len(import_line.splitlines()) > 1 else ''}")
    ok(f"导出名: {names}")

    # Fix import line module name: worktree may use base name (logical_not) but
    # repo uses op name (logical_not_) for the kernel file.
    if used_module != op:
        import_line = import_line.replace(
            f"from flag_gems.ops.{used_module} import",
            f"from flag_gems.ops.{op} import"
        )
        ok(f"import 模块名修正: {used_module} → {op}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    # Insert import line in alphabetical order
    repo_lines = repo_content.split("\n")
    import_section_end = 0
    existing_imports = []
    for i, line in enumerate(repo_lines):
        if line.startswith("from flag_gems.ops."):
            existing_imports.append((i, line))
            import_section_end = i

    # Check if already exists
    if any(import_line in line for _, line in existing_imports):
        ok("import 已存在，跳过")
    else:
        # Find insertion point by alphabetical order
        module_name = op
        insert_idx = import_section_end + 1
        for i, line in existing_imports:
            match = re.match(r"from flag_gems\.ops\.(\w+) import", line)
            if match:
                existing_mod = match.group(1)
                sort_key_existing = (not existing_mod.startswith("_"), existing_mod)
                sort_key_new = (not module_name.startswith("_"), module_name)
                if sort_key_new < sort_key_existing:
                    insert_idx = i
                    break
                insert_idx = i + 1

        repo_lines.insert(insert_idx, import_line)
        ok(f"import 插入位置: 行 {insert_idx + 1}")

    # Insert into __all__
    # Find __all__ block
    all_start = None
    all_end = None
    for i, line in enumerate(repo_lines):
        if "__all__" in line and "=" in line:
            all_start = i
        if all_start and line.strip() == "]":
            all_end = i
            break

    if all_start and all_end:
        # Extract current __all__ entries
        all_entries = []
        for i in range(all_start, all_end + 1):
            matches = re.findall(r'"(\w+)"', repo_lines[i])
            all_entries.extend(matches)

        for name in names:
            if name in all_entries:
                ok(f'__all__ 已包含 "{name}"')
                continue

            # Find insertion point
            insert_idx = all_end
            for i in range(all_start + 1, all_end):
                match = re.search(r'"(\w+)"', repo_lines[i])
                if match:
                    existing = match.group(1)
                    if name < existing:
                        insert_idx = i
                        break
                    insert_idx = i + 1

            entry = f'    "{name}",'
            repo_lines.insert(insert_idx, entry)
            all_end += 1
            ok(f'__all__ 插入 "{name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] ops/__init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("ops/__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 5: _FULL_CONFIG
# ---------------------------------------------------------------------------


def insert_full_config(op, worktree, repo, dry_run):
    section("Step 5: _FULL_CONFIG")
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/__init__.py")

    # Extract config entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    # Find all config entries for this op
    op_id = get_op_id(op)
    config_entries = []
    for line in wt_content.split("\n"):
        line_stripped = line.strip()
        if line_stripped.startswith("(") and ("," in line_stripped):
            match = re.match(r'\(\s*"([^"]+)"\s*,\s*(\w+)', line_stripped)
            if match:
                aten_name, func_name = match.groups()
                # special_* → special.* 格式修正
                if aten_name.startswith("special_") and "." not in aten_name:
                    corrected = aten_name.replace("special_", "special.", 1)
                    line_stripped = line_stripped.replace(f'"{aten_name}"', f'"{corrected}"')
                    warn(f"_FULL_CONFIG aten name 自动修正: {aten_name} → {corrected}")
                    aten_name = corrected
                base_name = aten_name.split(".")[0].replace("special", "special").lstrip("_")
                func_base = func_name.replace("special_", "").lstrip("_")
                op_base = op.replace("special_", "").lstrip("_")
                op_id_base = op_id.replace("special_", "").lstrip("_")
                if (base_name == op or base_name == op_id
                        or func_name == op or func_name == op_id
                        or func_base == op_base or func_base == op_id_base):
                    config_entries.append(line_stripped.rstrip(",") + ",")

    if not config_entries:
        fatal(f"worktree _FULL_CONFIG 中未找到 {op} 的条目")

    for entry in config_entries:
        ok(f"配置: {entry}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    repo_lines = repo_content.split("\n")

    # Find _FULL_CONFIG block
    config_start = None
    config_end = None
    for i, line in enumerate(repo_lines):
        if "_FULL_CONFIG" in line and "=" in line:
            config_start = i
        if config_start and line.strip() == ")":
            config_end = i
            break

    if not config_start or not config_end:
        fatal("未找到 _FULL_CONFIG 定义")

    # Insert each entry (deduplicate: track inserted aten names)
    inserted_names = set()
    for entry in config_entries:
        match = re.match(r'\(\s*"([^"]+)"', entry)
        if not match:
            continue
        aten_name = match.group(1)

        # Check if already exists in repo OR already inserted in this run
        if f'"{aten_name}"' in repo_content or aten_name in inserted_names:
            ok(f'_FULL_CONFIG 已包含 "{aten_name}"')
            continue

        # Find insertion point by alphabetical order of aten name
        insert_idx = config_end
        for i in range(config_start + 1, config_end):
            line_match = re.search(r'\(\s*"([^"]+)"', repo_lines[i])
            if line_match:
                existing_name = line_match.group(1)
                if aten_name < existing_name:
                    insert_idx = i
                    break
                insert_idx = i + 1

        indent = "    "
        repo_lines.insert(insert_idx, f"{indent}{entry}")
        config_end += 1
        inserted_names.add(aten_name)
        ok(f'_FULL_CONFIG 插入 "{aten_name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] __init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 6: operators.yaml
# ---------------------------------------------------------------------------


def insert_operators_yaml(op, worktree, repo, dry_run):
    section("Step 6: operators.yaml")
    # yaml id 用 resolve_op_names：冲突场景保留前导下划线（与 API 一致）。
    op_id = resolve_op_names(repo, op)[0]
    repo_yaml = os.path.join(repo, "conf/operators.yaml")
    wt_yaml = os.path.join(worktree, "conf/operators.yaml")

    with open(repo_yaml) as f:
        repo_data = yaml.safe_load(f)

    # Check if already exists
    existing_ids = [o.get("id") for o in repo_data.get("ops", [])]
    if op_id in existing_ids:
        ok(f"operators.yaml 已包含 id: {op_id}")
        # Still check inplace split below
    else:
        # Try to get entry from worktree yaml
        entry = None
        with open(wt_yaml) as f:
            wt_data = yaml.safe_load(f)
        for wt_op in wt_data.get("ops", []):
            wt_name = wt_op.get("name", wt_op.get("id", ""))
            if wt_name == op or wt_name == op_id:
                entry = dict(wt_op)
                if "name" in entry:
                    entry["id"] = op_id
                    del entry["name"]
                break

        if not entry:
            entry = {
                "id": op_id,
                "description": f"Triton kernel implementation for {op}.\n",
                "for": [op],
                "labels": ["aten", "KernelGen"],
                "kind": ["Math"],
                "stages": [{"alpha": "5.4"}],
            }
            warn(f"worktree yaml 无此算子，使用默认条目（description 需人工补充）")
        else:
            labels = entry.get("labels", [])
            if "KernelGen" not in labels:
                labels.append("KernelGen")
                entry["labels"] = labels
            entry["id"] = op_id
            stages = entry.get("stages", {})
            if isinstance(stages, dict):
                entry["stages"] = [{k: v} for k, v in stages.items()]
            ok(f"从 worktree yaml 提取条目")

        # Split: if entry's 'for' list contains both op and op_ (inplace), split them
        for_list = entry.get("for", [])
        inplace_items = [f for f in for_list if f.rstrip(".").endswith("_") and f.rstrip("_.") == op.rstrip("_")]
        non_inplace_items = [f for f in for_list if f not in inplace_items]

        if inplace_items and non_inplace_items:
            warn(f"检测到 for 列表同时包含 inplace 和非 inplace: {for_list}，自动拆分")
            entry["for"] = non_inplace_items
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)
            # Create separate inplace entry
            inplace_entry = dict(entry)
            inplace_id = op_id + "_"
            inplace_entry["id"] = inplace_id
            inplace_entry["description"] = f"The in-place version of `{op_id}()`."
            inplace_entry["for"] = inplace_items
            if inplace_id not in existing_ids:
                _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, existing_ids, dry_run)
                ok(f"已拆分 inplace 变体为独立条目: id={inplace_id}")
        else:
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)

    # Check _FULL_CONFIG for inplace variant not in yaml
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    if os.path.isfile(wt_init):
        with open(wt_init) as f:
            wt_content = f.read()
        inplace_op = op + "_" if not op.endswith("_") else None
        if inplace_op:
            inplace_id = get_op_id(inplace_op)
            inplace_pattern = rf'\(\s*"[^"]*{re.escape(inplace_op)}[^"]*"\s*,'
            if re.search(inplace_pattern, wt_content):
                # Reload to check current state
                with open(repo_yaml) as f:
                    current_data = yaml.safe_load(f)
                current_ids = [o.get("id") for o in current_data.get("ops", [])]
                if inplace_id not in current_ids:
                    inplace_entry = {
                        "id": inplace_id,
                        "description": f"The in-place version of `{op_id}()`.",
                        "for": [inplace_op],
                        "labels": ["aten", "KernelGen"],
                        "kind": ["Math"],
                        "stages": [{"alpha": "5.4"}],
                    }
                    _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, current_ids, dry_run)
                    ok(f"_FULL_CONFIG 注册了 inplace 变体，已生成独立 yaml 条目: {inplace_id}")

    # Insert sibling overload entries (e.g. ``_conj_physical_out`` with
    # ``for: [_conj_physical.out]``) that the worktree yaml defines as separate
    # ops. These are distinct from inplace variants and must each get their own
    # yaml entry so check_operator's overload-consistency check passes.
    out_variant_ids = set()
    if os.path.isfile(wt_yaml):
        with open(wt_yaml) as f:
            wt_data = yaml.safe_load(f)
        with open(repo_yaml) as f:
            cur_data = yaml.safe_load(f)
        cur_ids = {o.get("id") for o in cur_data.get("ops", [])}
        for wt_op in wt_data.get("ops", []):
            wt_id = wt_op.get("name", wt_op.get("id", ""))
            # Sibling: id starts with op_id + a suffix like "_out", and is not
            # the primary op_id itself, and not the bare upstream op.
            if (wt_id != op_id and wt_id != op
                    and wt_id.startswith(op_id)
                    and wt_id[len(op_id):].startswith("_")):
                out_variant_ids.add(wt_id)
                if wt_id in cur_ids:
                    ok(f"operators.yaml 已包含 sibling 变体 id: {wt_id}")
                    continue
                sib_entry = dict(wt_op)
                if "name" in sib_entry:
                    del sib_entry["name"]
                sib_entry["id"] = wt_id
                labels = sib_entry.get("labels", [])
                if "KernelGen" not in labels:
                    labels.append("KernelGen")
                    sib_entry["labels"] = labels
                stages = sib_entry.get("stages", {})
                if isinstance(stages, dict):
                    sib_entry["stages"] = [{k: v} for k, v in stages.items()]
                # refresh cur_ids for ordering against just-inserted siblings
                with open(repo_yaml) as f:
                    cur_data = yaml.safe_load(f)
                cur_ids = [o.get("id") for o in cur_data.get("ops", [])]
                _insert_yaml_entry(sib_entry, repo_yaml, wt_id, cur_ids, dry_run)
                ok(f"已插入 sibling 变体 yaml 条目: id={wt_id}")


def _insert_yaml_entry(entry, repo_yaml, entry_id, existing_ids, dry_run):
    """Insert a single yaml entry in alphabetical order."""
    if entry_id in existing_ids:
        ok(f"yaml 已包含 id: {entry_id}，跳过")
        return

    with open(repo_yaml) as f:
        yaml_lines = f.readlines()

    insert_line = len(yaml_lines)
    i = 0
    while i < len(yaml_lines):
        match = re.match(r"\s*-\s*id:\s*(\S+)", yaml_lines[i])
        if match:
            existing_id = match.group(1)
            if entry_id < existing_id:
                insert_line = i
                break
        i += 1

    new_lines = []
    new_lines.append(f"  - id: {entry['id']}\n")
    desc = entry.get("description", "").strip()
    if "\n" in desc or len(desc) > 60:
        new_lines.append("    description: |\n")
        for dline in desc.split("\n"):
            new_lines.append(f"      {dline.strip()}\n")
    else:
        new_lines.append(f"    description: {desc}\n")
    new_lines.append("    for:\n")
    for item in entry.get("for", []):
        # special_* 算子 for 字段用 aten dispatch 格式: special.xxx
        if item.startswith("special_") and "." not in item:
            item = item.replace("special_", "special.", 1)
            warn(f"yaml for 自动修正: special_xxx → {item}")
        new_lines.append(f"      - {item}\n")
    new_lines.append("    labels:\n")
    for label in entry.get("labels", ["aten", "KernelGen"]):
        new_lines.append(f"      - {label}\n")
    new_lines.append("    kind:\n")
    for kind in entry.get("kind", ["Math"]):
        new_lines.append(f"      - {kind}\n")
    new_lines.append("    stages:\n")
    stages = entry.get("stages", [{"alpha": "5.4"}])
    if isinstance(stages, list):
        for s in stages:
            if isinstance(s, dict):
                for k, v in s.items():
                    new_lines.append(f"      - {k}: '{v}'\n")
    elif isinstance(stages, dict):
        for k, v in stages.items():
            new_lines.append(f"      - {k}: '{v}'\n")

    yaml_lines[insert_line:insert_line] = new_lines
    ok(f"yaml 插入 id: {entry_id} 在行 {insert_line + 1}")

    if dry_run:
        ok(f"[DRY] operators.yaml 将被更新 ({entry_id})")
    else:
        with open(repo_yaml, "w") as f:
            f.writelines(yaml_lines)
        ok(f"operators.yaml 已更新 ({entry_id})")




# ---------------------------------------------------------------------------
# Canonical rename
# ---------------------------------------------------------------------------


def _replace_tokens(content, plan):
    replacements = []
    for old in [
        plan.source_name,
        plan.impl_name,
        plan.source_op_id,
        plan.impl_op_id,
    ]:
        if old and old != plan.canonical_name and old != plan.canonical_op_id:
            replacements.append((old, plan.canonical_name))

    result = content
    # Longer tokens first so Cross_Attention is replaced before cross_attention-like substrings.
    for old, new in sorted(set(replacements), key=lambda item: len(item[0]), reverse=True):
        result = result.replace(old, new)
    return result


def canonicalize_extracted_files(plan, repo, dry_run):
    """Rename generated source-name files and contents to the canonical name."""
    if not plan.renamed:
        return

    section("Step 7: 规范名重命名")
    ok(f"source_name: {plan.source_name}")
    ok(f"canonical_name: {plan.canonical_name}")

    source_files = [
        f"src/flag_gems/ops/{plan.source_name}.py",
        f"tests/test_{plan.impl_op_id}.py",
        f"benchmark/test_{plan.impl_op_id}.py",
        "src/flag_gems/ops/__init__.py",
        "src/flag_gems/__init__.py",
        "conf/operators.yaml",
    ]

    for relpath in source_files:
        full = os.path.join(repo, relpath)
        if not os.path.isfile(full):
            continue
        with open(full) as f:
            content = f.read()
        new_content = _replace_tokens(content, plan)
        if new_content != content:
            if dry_run:
                ok(f"[DRY] 将规范化内容: {relpath}")
            else:
                with open(full, "w") as f:
                    f.write(new_content)
                ok(f"已规范化内容: {relpath}")

    renames = [
        (
            f"src/flag_gems/ops/{plan.source_name}.py",
            f"src/flag_gems/ops/{plan.canonical_name}.py",
        ),
        (
            f"tests/test_{plan.impl_op_id}.py",
            f"tests/test_{plan.canonical_op_id}.py",
        ),
        (
            f"benchmark/test_{plan.impl_op_id}.py",
            f"benchmark/test_{plan.canonical_op_id}.py",
        ),
    ]

    for old_rel, new_rel in renames:
        old = os.path.join(repo, old_rel)
        new = os.path.join(repo, new_rel)
        if old == new or not os.path.isfile(old):
            continue
        if os.path.exists(new):
            fatal(f"规范名目标文件已存在，不能覆盖: {new_rel}")
        if dry_run:
            ok(f"[DRY] 将重命名: {old_rel} → {new_rel}")
        else:
            os.rename(old, new)
            ok(f"已重命名: {old_rel} → {new_rel}")


# ---------------------------------------------------------------------------
# tune_configs.yaml (Nvidia backend) — copy the op's autotune config block.
# ---------------------------------------------------------------------------

def _parse_yaml_top_level_blocks(content):
    """Return list of (key, block_text, start_line, end_line) for top-level keys.

    A top-level key is a line matching ``^<key>:$`` at column 0. Its block runs
    until the next top-level key or EOF.
    """
    blocks = []
    cur_key = None
    cur_start = None
    lines = content.split("\n")
    for i, line in enumerate(lines):
        if re.match(r"^[A-Za-z_][A-Za-z0-9_]*:$", line):
            if cur_key is not None:
                blocks.append((cur_key, cur_start, i))
            cur_key = line[:-1]
            cur_start = i
    if cur_key is not None:
        blocks.append((cur_key, cur_start, len(lines)))
    return lines, blocks


def insert_tune_configs(op, worktree, repo, dry_run):
    """Copy the op's autotune config block from the worktree's Nvidia
    ``tune_configs.yaml`` into the repo's, if the worktree has one and the
    repo does not. The block is inserted in alphabetical order of the key.
    """
    section("Step 7: tune_configs.yaml (Nvidia)")
    # The kernel may use runtime.get_tuned_config("<resolved_id>") or
    # runtime.get_tuned_config("<op>"). Try both, plus variant ids registered
    # in the worktree yaml (_out variants share the kernel's config usually,
    # but the worktree may still list them).
    resolved_id = resolve_op_names(repo, op)[0]
    candidate_keys = []
    for k in [op, resolved_id, get_op_id(op)]:
        if k and k not in candidate_keys:
            candidate_keys.append(k)

    wt_yaml = os.path.join(
        worktree, "src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml"
    )
    repo_yaml = os.path.join(
        repo, "src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml"
    )
    if not os.path.isfile(wt_yaml):
        warn("worktree 无 tune_configs.yaml，跳过")
        return
    if not os.path.isfile(repo_yaml):
        warn("repo 无 tune_configs.yaml，跳过")
        return

    with open(wt_yaml) as f:
        wt_content = f.read()
    with open(repo_yaml) as f:
        repo_content = f.read()

    wt_lines, wt_blocks = _parse_yaml_top_level_blocks(wt_content)
    repo_lines, repo_blocks = _parse_yaml_top_level_blocks(repo_content)
    repo_keys = {k for k, _, _ in repo_blocks}

    inserted_any = False
    for key in candidate_keys:
        wt_block = next(((s, e) for k, s, e in wt_blocks if k == key), None)
        if wt_block is None:
            continue
        if key in repo_keys:
            ok(f"tune_configs.yaml 已包含 {key}")
            continue
        block_text = "\n".join(wt_lines[wt_block[0]:wt_block[1]]).rstrip() + "\n"
        # Find alphabetical insertion point among existing top-level keys.
        insert_line = len(repo_lines)
        for k, s, _ in repo_blocks:
            if key < k:
                insert_line = s
                break
        if dry_run:
            ok(f"[DRY] 将插入 tune_configs.yaml: {key} (在行 {insert_line})")
        else:
            new_lines = repo_lines[:insert_line] + block_text.split("\n") + repo_lines[insert_line:]
            with open(repo_yaml, "w") as f:
                f.write("\n".join(new_lines))
            ok(f"tune_configs.yaml 插入 {key} 在行 {insert_line}")
        inserted_any = True
        # refresh repo lines/keys for subsequent inserts
        with open(repo_yaml) as f:
            repo_content = f.read()
        repo_lines, repo_blocks = _parse_yaml_top_level_blocks(repo_content)
        repo_keys = {k for k, _, _ in repo_blocks}

    if not inserted_any:
        ok("tune_configs.yaml 无需更新（kernel 不依赖外部 autotune 配置）")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="从 worktree 自动提取算子代码")
    parser.add_argument("operator", help="算子名称或规范名")
    parser.add_argument(
        "--repo-dir",
        default=os.environ.get("FLAGGEMS_REPO", DEFAULT_REPO),
    )
    parser.add_argument("--source-name", help="生成器/worktree 中的原始算子名")
    parser.add_argument("--canonical-name", help="最终提交使用的规范算子名")
    parser.add_argument("--impl-name", help="worktree 内部 wrapper/pytest mark/benchmark op_name")
    parser.add_argument("--worktree-dir", help="显式指定 worktree 源目录（覆盖默认 repo-dir/.worktrees/gen-<op>）")
    parser.add_argument("--dry-run", action="store_true", help="只预览不写入")
    args = parser.parse_args()

    repo = os.path.abspath(args.repo_dir)
    plan = build_name_plan(
        args.operator,
        repo,
        source_name=args.source_name,
        canonical_name=args.canonical_name,
        impl_name=args.impl_name,
        worktree_dir=os.path.abspath(args.worktree_dir) if args.worktree_dir else None,
    )
    source_op = plan.source_name
    impl_op = plan.impl_name
    canonical_op = plan.canonical_name
    # 冲突场景（存在裸算子）下 canonical_op_id 保留前导下划线（最终文件名用）。
    canonical_op_id, _canonical_mark = resolve_op_names(repo, canonical_op)
    worktree = plan.worktree_dir

    print(f"{Colors.BOLD}从 worktree 提取: {args.operator}{Colors.END}")
    print(f"source_name: {plan.source_name}")
    print(f"impl_name: {plan.impl_name}")
    print(f"canonical_name: {plan.canonical_name}")
    print(f"worktree: {worktree}")
    print(f"repo: {repo}")

    if plan.renamed:
        warn("检测到生成名和规范名不同，最终文件/注册将统一为规范名")

    if not os.path.isdir(worktree):
        fatal(f"worktree 不存在: {worktree}")

    extract_kernel(source_op, worktree, repo, args.dry_run)
    extract_test(impl_op, worktree, repo, args.dry_run)
    extract_benchmark(impl_op, worktree, repo, args.dry_run)
    insert_ops_init(source_op, worktree, repo, args.dry_run)
    insert_full_config(impl_op, worktree, repo, args.dry_run)
    insert_operators_yaml(impl_op, worktree, repo, args.dry_run)
    insert_tune_configs(source_op, worktree, repo, args.dry_run)
    canonicalize_extracted_files(plan, repo, args.dry_run)

    if not args.dry_run:
        write_name_plan(repo, plan)

    print(f"\n{Colors.OK}{Colors.BOLD}✓ 6 个文件已准备完毕{Colors.END}")
    print(f"  src/flag_gems/ops/{canonical_op}.py")
    print(f"  src/flag_gems/ops/__init__.py")
    print(f"  src/flag_gems/__init__.py")
    print(f"  tests/test_{canonical_op_id}.py")
    print(f"  benchmark/test_{canonical_op_id}.py")
    print(f"  conf/operators.yaml")
    print(f"\n  接下来运行: CUDA_VISIBLE_DEVICES=<N> python scripts/submit_operator.py {canonical_op}")


if __name__ == "__main__":
    main()
