#!/usr/bin/env python3
"""Parallel read-only auditor for FlagGems PRs.

The script collects GitHub PR diffs, runs deterministic checks for common
flaggems-pr-submit rule violations, then starts one streaming model agent per
PR to produce a focused review report. It never writes to PR branches.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import selectors
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path


LOCAL_NO_PROXY_HOSTS = ("localhost", "127.0.0.1", "::1")
PR_NUMBER_RE = re.compile(r"(?:/pull/|#)?(\d+)\b")
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
MACHINE_SUMMARY_RE = re.compile(r"```json\s*(\{.*?\})\s*```", re.DOTALL)
MANUAL_PR_RE = re.compile(r"\bgh\s+pr\s+(?:create|edit|merge|ready|reopen|close)\b")

INFRA_PREFIXES = (
    ".github/workflows/",
    "container/",
)
INFRA_FILES = {
    "tools/vendor.sh",
    "setup.sh",
    "tools/env.sh",
    "pyproject.toml",
}
BACKEND_OP_PATH_RE = re.compile(r"src/flag_gems/runtime/backend/(_[A-Za-z0-9]+)/ops/(.+)\.py$")
BACKEND_OPS_INIT_RE = re.compile(r"src/flag_gems/runtime/backend/(_[A-Za-z0-9]+)/ops/__init__\.py$")
BACKEND_TUNE_CONFIG_RE = re.compile(r"src/flag_gems/runtime/backend/(_[A-Za-z0-9]+)/tune_configs\.yaml$")
FUSED_OP_PATH_RE = re.compile(r"src/flag_gems/fused/([^/]+)\.py$")
FUSED_OPS_INIT_RE = re.compile(r"src/flag_gems/fused/__init__\.py$")
BACKEND_FUSED_OP_PATH_RE = re.compile(r"src/flag_gems/runtime/backend/(_[A-Za-z0-9]+)/fused/(.+)\.py$")
BACKEND_FUSED_INIT_RE = re.compile(r"src/flag_gems/runtime/backend/(_[A-Za-z0-9]+)/fused/__init__\.py$")
PR_BODY_DEBUG_WORDS = (
    "operator not in summary",
    "TODO",
    "FIXME",
    "UNKNOWN",
    "parser",
    "debug",
    "artifact",
)
REQUIRED_KERNEL_HEADER = """# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""
VALID_YAML_KINDS = {"Math", "NeuralNetwork", "Tensor", "LinearAlg", "BLAS", "Reduction", "Distribution", "MoE", "Data", "DSA"}
TENSOR_KIND_OPS = {
    "resize", "resize_", "resize_as", "resize_as_", "contiguous", "clone", "expand",
    "view", "reshape", "permute", "transpose", "narrow", "select", "slice", "cat",
    "stack", "chunk", "split", "unbind", "squeeze", "unsqueeze", "flatten",
    "unflatten", "t",
}
PROBABILITY_OP_HINTS = ("dropout", "bernoulli", "rand", "normal", "poisson", "multinomial")
DEVICE_HARDCODE_PATTERNS = (
    re.compile(r"\.is_cuda\b"),
    re.compile(r"\bdevice\.type\s*==\s*[\"']cuda[\"']"),
)


@dataclass
class Finding:
    severity: str
    check: str
    message: str
    evidence: list[str]


@dataclass
class AuditResult:
    pr: int
    url: str | None
    title: str | None
    status: str
    verdict: str
    highest_severity: str
    blocking_count: int
    non_blocking_count: int
    start_time: str
    end_time: str
    duration_seconds: int
    pr_dir: str
    report_file: str
    conversation_file: str | None
    log_file: str | None
    error_summary: str | None = None


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def run_cmd(cmd: list[str], cwd: Path, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=str(cwd), text=True, capture_output=True, timeout=timeout)


def extend_no_proxy(env: dict[str, str]) -> None:
    existing: list[str] = []
    for key in ("NO_PROXY", "no_proxy"):
        existing.extend(part.strip() for part in env.get(key, "").split(",") if part.strip())
    merged: list[str] = []
    for host in [*existing, *LOCAL_NO_PROXY_HOSTS]:
        if host not in merged:
            merged.append(host)
    value = ",".join(merged)
    env["NO_PROXY"] = value
    env["no_proxy"] = value


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = os.path.expandvars(value.strip().strip('"').strip("'"))
    return values


def parse_pr_number(raw: str) -> int:
    match = PR_NUMBER_RE.search(raw.strip())
    if not match:
        raise ValueError(f"Could not parse PR number from: {raw}")
    return int(match.group(1))


def load_pr_numbers(args: argparse.Namespace) -> list[int]:
    numbers: list[int] = []
    if args.prs:
        for part in re.split(r"[,\s]+", args.prs):
            if part.strip():
                numbers.append(parse_pr_number(part))
    if args.prs_file:
        for raw in args.prs_file.read_text().splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                numbers.append(parse_pr_number(line))
    if args.query:
        cmd = [
            "gh",
            "pr",
            "list",
            "--repo",
            args.repo,
            "--search",
            args.query,
            "--json",
            "number",
            "--limit",
            str(args.query_limit),
        ]
        result = run_cmd(cmd, Path.cwd(), timeout=60)
        if result.returncode != 0:
            raise RuntimeError(f"gh pr list failed: {result.stderr or result.stdout}")
        for item in json.loads(result.stdout):
            numbers.append(int(item["number"]))

    deduped: list[int] = []
    seen: set[int] = set()
    for number in numbers:
        if number not in seen:
            seen.add(number)
            deduped.append(number)
    return deduped


def collect_pr_artifacts(pr: int, args: argparse.Namespace, pr_dir: Path) -> dict:
    pr_dir.mkdir(parents=True, exist_ok=True)

    view_cmd = [
        "gh",
        "pr",
        "view",
        str(pr),
        "--repo",
        args.repo,
        "--json",
        "number,title,url,author,headRefName,baseRefName,body,state,isDraft,mergeable",
    ]
    view = run_cmd(view_cmd, Path.cwd(), timeout=60)
    if view.returncode != 0:
        raise RuntimeError(f"gh pr view {pr} failed: {view.stderr or view.stdout}")
    pr_json = json.loads(view.stdout)
    (pr_dir / "pr.json").write_text(json.dumps(pr_json, indent=2, ensure_ascii=False) + "\n")

    diff = run_cmd(["gh", "pr", "diff", str(pr), "--repo", args.repo], Path.cwd(), timeout=120)
    if diff.returncode != 0:
        raise RuntimeError(f"gh pr diff {pr} failed: {diff.stderr or diff.stdout}")
    (pr_dir / "diff.patch").write_text(diff.stdout)

    files = run_cmd(["gh", "pr", "diff", str(pr), "--repo", args.repo, "--name-only"], Path.cwd(), timeout=120)
    if files.returncode != 0:
        names = parse_files_from_diff(diff.stdout)
    else:
        names = [line.strip() for line in files.stdout.splitlines() if line.strip()]
    (pr_dir / "files.txt").write_text("\n".join(names) + ("\n" if names else ""))

    return {"metadata": pr_json, "diff": diff.stdout, "files": names}


def parse_files_from_diff(diff_text: str) -> list[str]:
    files: list[str] = []
    for line in diff_text.splitlines():
        if line.startswith("diff --git "):
            parts = line.split()
            if len(parts) >= 4:
                path = parts[3]
                if path.startswith("b/"):
                    path = path[2:]
                files.append(path)
    return files


def parse_added_lines_by_file(diff_text: str) -> dict[str, list[tuple[int | None, str]]]:
    """Return added lines grouped by destination file.

    The line number is the new-file line number when the hunk header provides
    enough information. It is best-effort and intended for report evidence only.
    """
    by_file: dict[str, list[tuple[int | None, str]]] = {}
    current: str | None = None
    new_line: int | None = None
    for raw in diff_text.splitlines():
        if raw.startswith("diff --git "):
            current = None
            new_line = None
            continue
        if raw.startswith("+++ b/"):
            current = raw[len("+++ b/") :]
            by_file.setdefault(current, [])
            continue
        if raw.startswith("@@"):
            match = re.search(r"\+(\d+)(?:,(\d+))?", raw)
            new_line = int(match.group(1)) if match else None
            continue
        if current is None:
            continue
        if raw.startswith("+") and not raw.startswith("+++"):
            by_file[current].append((new_line, raw[1:]))
            if new_line is not None:
                new_line += 1
        elif raw.startswith("-") and not raw.startswith("---"):
            continue
        elif new_line is not None:
            new_line += 1
    return by_file


def infer_operator_ids(files: list[str], diff_text: str, title: str | None) -> set[str]:
    ids: set[str] = set()
    for path in files:
        match = re.match(r"src/flag_gems/ops/(.+)\.py$", path)
        if match and not match.group(1).startswith("__"):
            ids.add(match.group(1).lstrip("_"))
        match = re.match(r"tests/test_(.+)\.py$", path)
        if match:
            ids.add(match.group(1).lstrip("_"))
        match = re.match(r"benchmark/test_(.+)\.py$", path)
        if match:
            ids.add(match.group(1).lstrip("_"))
        match = BACKEND_OP_PATH_RE.match(path)
        if match and match.group(2) != "__init__":
            ids.add(match.group(2).lstrip("_"))

    for line in diff_text.splitlines():
        match = re.match(r"\+\s+- id:\s+(\S+)", line)
        if match:
            ids.add(match.group(1).lstrip("_"))

    if title:
        title_match = re.search(r"Add\s+([A-Za-z0-9_.]+)\s+operator", title)
        if title_match:
            ids.add(title_match.group(1).lstrip("_"))
    return ids


def base_id(value: str) -> str:
    value = value.strip().strip('"').strip("'").lstrip("_")
    for suffix in ("_out", "_scalar", "_tensor", "_dtype", "_dtype_out"):
        if value.endswith(suffix):
            return value[: -len(suffix)]
    if value.endswith("_") and len(value) > 1:
        return value[:-1]
    return value.split(".")[0]


def belongs_to_current(value: str, current_ids: set[str]) -> bool:
    if not current_ids:
        return False
    normalized = canonical_variant_id(value)
    candidates = {normalized, base_id(normalized)}
    return bool(candidates & current_ids)


def canonical_variant_id(value: str) -> str:
    value = value.strip().strip('"').strip("'").lstrip("_")
    if value.startswith("special."):
        value = value.replace("special.", "special_", 1)
    value = value.replace(".out", "_out")
    return value.replace(".", "_")


def backend_scope_state(files: list[str], current_ids: set[str]) -> dict[str, set[str]]:
    state: dict[str, set[str]] = {}
    for path in files:
        match = BACKEND_OP_PATH_RE.match(path)
        if not match or match.group(2) == "__init__":
            continue
        backend = match.group(1)
        op_name = match.group(2)
        if belongs_to_current(op_name, current_ids):
            state.setdefault(backend, set()).add(op_name)
    return state


def infer_fused_ids(files: list[str], diff_text: str, current_ids: set[str]) -> set[str]:
    fused_ids: set[str] = set()
    for path in files:
        match = FUSED_OP_PATH_RE.match(path)
        if match and match.group(1) != "__init__":
            fused_ids.add(canonical_variant_id(match.group(1)))
        match = BACKEND_FUSED_OP_PATH_RE.match(path)
        if match and match.group(2) != "__init__":
            fused_ids.add(canonical_variant_id(match.group(2)))

    for line in diff_text.splitlines():
        match = re.match(r"\+\s+- id:\s+(\S+)", line)
        if match:
            op_id = canonical_variant_id(match.group(1))
            if "fused" in op_id:
                fused_ids.add(op_id)

    for op_id in current_ids:
        if "fused" in canonical_variant_id(op_id):
            fused_ids.add(canonical_variant_id(op_id))
    return fused_ids


def is_allowed_operator_scoped_file(path: str, current_ids: set[str], backend_state: dict[str, set[str]]) -> bool:
    if path in {
        "conf/operators.yaml",
        "src/flag_gems/__init__.py",
        "src/flag_gems/ops/__init__.py",
        "src/flag_gems/fused/__init__.py",
        "benchmark/core_shapes.yaml",
    }:
        return True
    if path.startswith("src/flag_gems/runtime/backend/_nvidia/") and path.endswith("tune_configs.yaml"):
        return True
    patterns = [
        r"src/flag_gems/ops/(.+)\.py$",
        r"tests/test_(.+)\.py$",
        r"benchmark/test_(.+)\.py$",
    ]
    for pattern in patterns:
        match = re.match(pattern, path)
        if match:
            return belongs_to_current(match.group(1), current_ids)
    fused_op = FUSED_OP_PATH_RE.match(path)
    if fused_op:
        return belongs_to_current(fused_op.group(1), current_ids)
    backend_init = BACKEND_OPS_INIT_RE.match(path)
    if backend_init:
        return bool(backend_state.get(backend_init.group(1)))
    backend_tune = BACKEND_TUNE_CONFIG_RE.match(path)
    if backend_tune:
        return bool(backend_state.get(backend_tune.group(1)))
    backend_fused_init = BACKEND_FUSED_INIT_RE.match(path)
    if backend_fused_init:
        return True
    backend_fused_op = BACKEND_FUSED_OP_PATH_RE.match(path)
    if backend_fused_op:
        return belongs_to_current(backend_fused_op.group(2), current_ids)
    backend_op = BACKEND_OP_PATH_RE.match(path)
    if backend_op:
        return belongs_to_current(backend_op.group(2), current_ids)
    return False


def evidence_line(path: str, line_no: int | None, text: str) -> str:
    prefix = f"{path}:{line_no}" if line_no is not None else path
    return f"{prefix}: {text.strip()[:220]}"


def added_text_for(path: str, added_by_file: dict[str, list[tuple[int | None, str]]]) -> str:
    return "\n".join(text for _, text in added_by_file.get(path, []))


def is_added_new_file(path: str, added_by_file: dict[str, list[tuple[int | None, str]]]) -> bool:
    line_numbers = [line_no for line_no, _ in added_by_file.get(path, []) if line_no is not None]
    return bool(line_numbers) and min(line_numbers) == 1


def added_line_evidence(path: str, added_by_file: dict[str, list[tuple[int | None, str]]], pattern: str) -> list[str]:
    hits: list[str] = []
    regex = re.compile(pattern)
    for line_no, text in added_by_file.get(path, []):
        if regex.search(text):
            hits.append(evidence_line(path, line_no, text))
    return hits


def deterministic_checks(metadata: dict, files: list[str], diff_text: str) -> dict:
    title = metadata.get("title")
    body = metadata.get("body") or ""
    current_ids = infer_operator_ids(files, diff_text, title)
    added_by_file = parse_added_lines_by_file(diff_text)
    backend_state = backend_scope_state(files, current_ids)
    fused_ids = infer_fused_ids(files, diff_text, current_ids)
    findings: list[Finding] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append(Finding(severity, check, message, evidence[:10]))

    infra = [path for path in files if path in INFRA_FILES or path.startswith(INFRA_PREFIXES)]
    if infra:
        add("high", "infra_files", "PR touches global infra/dependency files.", infra)

    unexpected_files = [
        path for path in files
        if not is_allowed_operator_scoped_file(path, current_ids, backend_state)
    ]
    if unexpected_files:
        add(
            "medium",
            "unexpected_files",
            "PR touches files outside the normal single-operator scope.",
            unexpected_files,
        )

    op_files = [path for path in files if re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path)]
    op_roots = {Path(path).stem.lstrip("_") for path in op_files}
    if len(op_roots) > 1:
        add("high", "multiple_operator_files", "PR contains multiple operator implementation files.", sorted(op_files))

    deleted_yaml_ids: list[str] = []
    added_yaml_ids: list[str] = []
    deleted_config: list[str] = []
    added_config: list[str] = []
    deleted_exports: list[str] = []
    bad_special_for: list[str] = []
    bad_special_config: list[str] = []
    special_logger_mismatches: list[str] = []
    added_pytest_marks: set[str] = set()
    added_benchmark_op_names: set[str] = set()
    added_out_functions: set[str] = set()
    added_inplace_functions: set[str] = set()
    manual_pr_commands: list[str] = []

    for line in diff_text.splitlines():
        if line.startswith("---") or line.startswith("+++"):
            continue
        stripped = line[1:].strip() if line[:1] in {"+", "-"} else line.strip()
        if line.startswith("-"):
            m = re.match(r"-\s+- id:\s+(\S+)", line)
            if m:
                deleted_yaml_ids.append(m.group(1))
            m = re.match(r'-\s+\("([^"]+)",\s*(\w+)', line)
            if m:
                deleted_config.append(f'{m.group(1)} -> {m.group(2)}')
            m = re.match(r'-\s+"([^"]+)",\s*$', line)
            if m:
                deleted_exports.append(m.group(1))
        elif line.startswith("+"):
            m = re.match(r"\+\s+- id:\s+(\S+)", line)
            if m:
                added_yaml_ids.append(m.group(1))
            m = re.match(r'\+\s+\("([^"]+)",\s*(\w+)', line)
            if m:
                added_config.append(f'{m.group(1)} -> {m.group(2)}')
                if m.group(1).startswith("special_"):
                    bad_special_config.append(m.group(1))
            m = re.match(r"\+\s+-\s+(special_[A-Za-z0-9_.]+)\s*$", line)
            if m:
                bad_special_for.append(m.group(1))
            m = re.search(r'logger\.debug\(\s*["\']GEMS\s+([A-Z0-9_]+)', line)
            if m:
                logged = m.group(1)
                for current_id in current_ids:
                    if current_id.startswith("special_"):
                        expected = current_id.upper()
                        if current_id.endswith("_out"):
                            expected = current_id.upper()
                        if logged == expected or logged.startswith(expected + " "):
                            break
                        if logged.endswith(expected.removeprefix("SPECIAL_")):
                            special_logger_mismatches.append(
                                f"{logged} should include full special operator prefix, e.g. {expected}"
                            )
                            break
            m = re.search(r"@pytest\.mark\.([A-Za-z0-9_]+)", line)
            if m:
                added_pytest_marks.add(m.group(1))
            m = re.search(r"\bop_name\s*=\s*['\"]([^'\"]+)['\"]", line)
            if m:
                added_benchmark_op_names.add(m.group(1))
        if MANUAL_PR_RE.search(stripped):
            manual_pr_commands.append(stripped)

    unrelated_deleted_ids = [
        item for item in deleted_yaml_ids if not belongs_to_current(item, current_ids)
    ]
    if unrelated_deleted_ids:
        add(
            "high",
            "unrelated_yaml_id_deleted",
            "PR deletes YAML operator ids that do not appear to belong to the current operator.",
            unrelated_deleted_ids,
        )

    unrelated_deleted_config = [
        item for item in deleted_config if not belongs_to_current(item.split(" -> ", 1)[0], current_ids)
    ]
    if unrelated_deleted_config:
        add(
            "high",
            "unrelated_full_config_deleted",
            "PR deletes _FULL_CONFIG entries that do not appear to belong to the current operator.",
            unrelated_deleted_config,
        )

    unrelated_deleted_exports = [
        item for item in deleted_exports if not belongs_to_current(item, current_ids)
    ]
    if unrelated_deleted_exports:
        add(
            "medium",
            "unrelated_export_deleted",
            "PR deletes __all__ exports that do not appear to belong to the current operator.",
            unrelated_deleted_exports,
        )

    if bad_special_for:
        add(
            "high",
            "bad_special_yaml_for",
            "New special_* YAML for entries should use special.xxx dispatch format.",
            [f"{item} -> {item.replace('special_', 'special.', 1)}" for item in bad_special_for],
        )

    if bad_special_config:
        add(
            "high",
            "bad_special_full_config",
            "New special_* _FULL_CONFIG keys should use special.xxx dispatch format.",
            [f"{item} -> {item.replace('special_', 'special.', 1)}" for item in bad_special_config],
        )

    if special_logger_mismatches:
        add(
            "low",
            "special_logger_prefix",
            "Logger messages for special_* operators should keep the full operator name.",
            sorted(set(special_logger_mismatches)),
        )

    if manual_pr_commands:
        add("high", "manual_pr_command", "Diff contains manual gh pr commands.", manual_pr_commands)

    duplicate_added_yaml_ids = sorted({item for item in added_yaml_ids if added_yaml_ids.count(item) > 1})
    if duplicate_added_yaml_ids:
        add("high", "yaml_duplicate_added_id", "PR adds duplicate operators.yaml ids.", duplicate_added_yaml_ids)

    added_public_functions = extract_public_operator_functions(added_by_file, current_ids)
    added_out_functions, added_inplace_functions = extract_operator_variant_functions(added_by_file)

    body_findings = check_pr_body(body)
    for severity, check, message, evidence in body_findings:
        add(severity, check, message, evidence)

    added_line_findings = check_added_lines(added_by_file)
    for severity, check, message, evidence in added_line_findings:
        add(severity, check, message, evidence)

    device_findings = check_device_hardcode(added_by_file)
    for severity, check, message, evidence in device_findings:
        add(severity, check, message, evidence)

    structure_findings = check_new_file_structure(added_by_file, current_ids)
    for severity, check, message, evidence in structure_findings:
        add(severity, check, message, evidence)

    backend_findings = check_backend_specialization_files(
        files=files,
        added_by_file=added_by_file,
        current_ids=current_ids,
        backend_state=backend_state,
    )
    for severity, check, message, evidence in backend_findings:
        add(severity, check, message, evidence)

    fused_findings = check_fused_layout(
        files=files,
        added_by_file=added_by_file,
        current_ids=current_ids,
        fused_ids=fused_ids,
    )
    for severity, check, message, evidence in fused_findings:
        add(severity, check, message, evidence)

    yaml_block_findings = check_yaml_added_blocks(added_by_file, current_ids)
    for severity, check, message, evidence in yaml_block_findings:
        add(severity, check, message, evidence)

    registration_findings = check_registration_surfaces(
        added_by_file=added_by_file,
        added_public_functions=added_public_functions,
        added_full_config=added_config,
    )
    for severity, check, message, evidence in registration_findings:
        add(severity, check, message, evidence)

    kernel_risk_findings = check_kernel_risks(added_by_file, current_ids)
    for severity, check, message, evidence in kernel_risk_findings:
        add(severity, check, message, evidence)

    logger_findings = check_logger_usage(added_by_file, added_public_functions)
    for severity, check, message, evidence in logger_findings:
        add(severity, check, message, evidence)

    variant_findings = check_variant_consistency(
        added_out_functions=added_out_functions,
        added_inplace_functions=added_inplace_functions,
        added_yaml_ids=added_yaml_ids,
        added_full_config=added_config,
        added_pytest_marks=added_pytest_marks,
        added_benchmark_op_names=added_benchmark_op_names,
    )
    for severity, check, message, evidence in variant_findings:
        add(severity, check, message, evidence)

    coverage_findings = check_public_function_coverage(
        added_public_functions=added_public_functions,
        added_yaml_ids=added_yaml_ids,
        added_pytest_marks=added_pytest_marks,
        added_benchmark_op_names=added_benchmark_op_names,
        current_ids=current_ids,
    )
    for severity, check, message, evidence in coverage_findings:
        add(severity, check, message, evidence)

    benchmark_fairness_findings = check_benchmark_fairness(added_by_file, current_ids, fused_ids)
    for severity, check, message, evidence in benchmark_fairness_findings:
        add(severity, check, message, evidence)

    specialization_dependency_findings = check_specialization_pr_dependency(
        metadata=metadata,
        files=files,
        current_ids=current_ids,
        backend_state=backend_state,
        repo="flagos-ai/FlagGems-Experimental",
    )
    for severity, check, message, evidence in specialization_dependency_findings:
        add(severity, check, message, evidence)

    speedup_findings = extract_speedup_findings(body, current_ids)
    for item in speedup_findings:
        add(
            "info",
            "low_speedup",
            "PR body reports little or no geometric mean speedup.",
            [item],
        )

    severity_order = {"high": 4, "medium": 3, "low": 2, "info": 1}
    highest = "none"
    for finding in findings:
        if severity_order.get(finding.severity, 0) > severity_order.get(highest, 0):
            highest = finding.severity

    return {
        "current_operator_ids_inferred": sorted(current_ids),
        "backend_specializations_inferred": {backend: sorted(ids) for backend, ids in sorted(backend_state.items())},
        "fused_operator_ids_inferred": sorted(fused_ids),
        "changed_files": files,
        "added_yaml_ids": added_yaml_ids,
        "deleted_yaml_ids": deleted_yaml_ids,
        "added_full_config": added_config,
        "deleted_full_config": deleted_config,
        "added_public_operator_functions": sorted(added_public_functions),
        "findings": [asdict(item) for item in findings],
        "highest_severity": highest,
        "blocking_count": sum(1 for item in findings if item.severity == "high"),
        "actionable_count": sum(1 for item in findings if item.severity in {"high", "medium", "low"}),
    }


def check_pr_body(body: str) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    if not body:
        findings.append(("info", "missing_pr_body", "PR body is empty or unavailable.", []))
        return findings

    debug_hits = [word for word in PR_BODY_DEBUG_WORDS if word.lower() in body.lower()]
    if debug_hits:
        findings.append((
            "info",
            "pr_body_debug_words",
            "PR body contains automation/debug placeholder words.",
            debug_hits,
        ))
    if "Co-Authored-By:" in body:
        findings.append((
            "high",
            "co_authored_by",
            "PR body contains Co-Authored-By.",
            ["Co-Authored-By:"],
        ))
    if "Validated against reference on device" not in body:
        findings.append((
            "info",
            "testing_phrase",
            "Testing section should contain 'Validated against reference on device'.",
            [],
        ))
    if "## Performance" not in body:
        findings.append((
            "info",
            "missing_performance_section",
            "PR body is missing a Performance section.",
            [],
        ))
    return findings


def check_added_lines(added_by_file: dict[str, list[tuple[int | None, str]]]) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    private_api: list[str] = []
    rtol_hits: list[str] = []
    bad_test_names: list[str] = []
    skip_without_issue: list[str] = []
    print_hits: list[str] = []
    test_print_hits: list[str] = []
    benchmark_print_hits: list[str] = []
    yaml_long_lines: list[str] = []
    py_long_lines: list[str] = []
    trailing_whitespace: list[str] = []
    benchmark_fstring_op_name: list[str] = []
    coauthored: list[str] = []
    hardcoded_test_dtype: list[str] = []
    hardcoded_bench_dtype: list[str] = []
    direct_cpu_reference: list[str] = []
    nan_without_equal_nan: list[str] = []

    for path, lines in added_by_file.items():
        file_text = "\n".join(text for _, text in lines)
        file_has_equal_nan = "equal_nan=True" in file_text
        for idx, (line_no, text) in enumerate(lines):
            stripped = text.strip()
            previous_added = lines[idx - 1][1].strip() if idx > 0 else ""
            if path.startswith(("tests/", "benchmark/")) and re.search(r"\btorch\._[A-Za-z]", stripped):
                private_api.append(evidence_line(path, line_no, text))
            if "gems_assert_close" in stripped and re.search(r"\brtol\s*=", stripped):
                rtol_hits.append(evidence_line(path, line_no, text))
            if path.startswith(("tests/", "benchmark/")) and re.search(r"\bdef\s+test_(?:perf_|accuracy_)", stripped):
                bad_test_names.append(evidence_line(path, line_no, text))
            if "pytest.mark.skip" in stripped or "pytest.mark.skipif" in stripped or "pytest.mark.xfail" in stripped:
                if not re.search(r"(https?://|#[0-9]+)", stripped):
                    skip_without_issue.append(evidence_line(path, line_no, text))
            if path.startswith("src/flag_gems/ops/") and re.search(r"\bprint\s*\(", stripped):
                print_hits.append(evidence_line(path, line_no, text))
            if path.startswith("tests/") and re.search(r"\bprint\s*\(", stripped):
                test_print_hits.append(evidence_line(path, line_no, text))
            if path.startswith("benchmark/") and re.search(r"\bprint\s*\(", stripped):
                benchmark_print_hits.append(evidence_line(path, line_no, text))
            if path == "conf/operators.yaml" and len(text) > 120:
                yaml_long_lines.append(evidence_line(path, line_no, f"len={len(text)} {text}"))
            if path.endswith(".py") and len(text) > 120:
                py_long_lines.append(evidence_line(path, line_no, f"len={len(text)} {text}"))
            if text.rstrip() != text:
                trailing_whitespace.append(evidence_line(path, line_no, text))
            if path.startswith("benchmark/") and re.search(r"\bop_name\s*=\s*f['\"]", stripped):
                benchmark_fstring_op_name.append(evidence_line(path, line_no, text))
            if "Co-Authored-By:" in stripped:
                coauthored.append(evidence_line(path, line_no, text))
            dtype_pattern = r"\[torch\.(?:float32|float64|float16|bfloat16)(?:\s*,\s*torch\.(?:float32|float64|float16|bfloat16))*\]"
            if path.startswith("tests/") and re.search(dtype_pattern, stripped) and not previous_added.startswith("#"):
                hardcoded_test_dtype.append(evidence_line(path, line_no, text))
            if path.startswith("benchmark/") and re.search(dtype_pattern, stripped) and not previous_added.startswith("#"):
                hardcoded_bench_dtype.append(evidence_line(path, line_no, text))
            if path.startswith("tests/") and "to_reference" not in stripped:
                if ".cpu()" in stripped or ".to(torch.float64)" in stripped:
                    direct_cpu_reference.append(evidence_line(path, line_no, text))
            if path.startswith("tests/") and re.search(r"\bnan\b|NaN|torch\.nan", stripped) and not file_has_equal_nan:
                nan_without_equal_nan.append(evidence_line(path, line_no, text))

    if private_api:
        add("high", "private_torch_api", "Tests/benchmarks should not call torch private APIs.", private_api)
    if rtol_hits:
        add("high", "gems_assert_close_rtol", "gems_assert_close should not pass rtol.", rtol_hits)
    if bad_test_names:
        add("medium", "bad_test_function_name", "Test functions should be named test_<op>, not test_perf_ or test_accuracy_.", bad_test_names)
    if skip_without_issue:
        add("high", "skip_without_issue", "New skip/xfail marks must cite an issue URL or #number.", skip_without_issue)
    if print_hits:
        add("medium", "print_in_operator", "Operator implementation should not use print().", print_hits)
    if test_print_hits:
        add("high", "print_in_test", "Tests should not use print().", test_print_hits)
    if benchmark_print_hits:
        add("low", "print_in_benchmark", "Benchmark should avoid print().", benchmark_print_hits)
    if yaml_long_lines:
        add("low", "yaml_long_line", "operators.yaml added lines should avoid long single-line text.", yaml_long_lines)
    if py_long_lines:
        add("low", "python_long_line", "Added Python lines over 120 characters may fail style checks.", py_long_lines)
    if trailing_whitespace:
        add("medium", "trailing_whitespace", "Added lines contain trailing whitespace.", trailing_whitespace)
    if benchmark_fstring_op_name:
        add("medium", "benchmark_dynamic_op_name", "benchmark op_name should be a fixed canonical/variant id, not an f-string.", benchmark_fstring_op_name)
    if coauthored:
        add("high", "co_authored_by", "Commit/PR text must not include Co-Authored-By.", coauthored)
    if hardcoded_test_dtype:
        add("high", "test_dtype_hardcoded", "Test dtype lists should use utils.FLOAT_DTYPES or have a comment explaining hardcoding.", hardcoded_test_dtype)
    if hardcoded_bench_dtype:
        add("high", "benchmark_dtype_hardcoded", "Benchmark dtype lists should use consts.FLOAT_DTYPES or have a comment explaining hardcoding.", hardcoded_bench_dtype)
    if direct_cpu_reference:
        add("low", "manual_cpu_reference", "Tests should prefer utils.to_reference instead of direct .cpu()/.to(torch.float64).", direct_cpu_reference)
    if nan_without_equal_nan:
        add("low", "nan_without_equal_nan", "NaN-related tests should use gems_assert_close(equal_nan=True).", nan_without_equal_nan)

    return findings


def check_new_file_structure(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    for path in added_by_file:
        if not is_added_new_file(path, added_by_file):
            continue
        text = added_text_for(path, added_by_file)
        if re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            if not text.startswith(REQUIRED_KERNEL_HEADER):
                add("high", "kernel_header", "New operator file must start with the fixed copyright/Apache License and KernelGen header.", [path])
            if "import logging" not in text or "logger" not in text:
                add("low", "missing_logging", "New operator file should use the logging module.", [path])

        if re.match(r"tests/test_.+\.py$", path):
            evidence: list[str] = []
            if "from . import accuracy_utils as utils" not in text:
                evidence.append("missing: from . import accuracy_utils as utils")
            if "flag_gems.use_gems()" not in text:
                evidence.append("missing: flag_gems.use_gems()")
            if "gems_assert_close" not in text and "gems_assert_equal" not in text:
                evidence.append("missing: utils.gems_assert_close or utils.gems_assert_equal")
            if "utils.to_reference" not in text:
                evidence.append("missing: utils.to_reference")
            if evidence:
                add("high", "test_file_structure", "New test file is missing required FlagGems test patterns.", [f"{path}: {item}" for item in evidence])

        if re.match(r"benchmark/test_.+\.py$", path):
            evidence = []
            if "from . import base" not in text:
                evidence.append("missing: from . import base")
            if "FLOAT_DTYPES" not in text and not re.search(r"\[torch\.(?:float32|float64|float16|bfloat16)", text):
                evidence.append("missing dtype coverage: consts.FLOAT_DTYPES or commented hardcoded dtype")
            benchmark_classes = (
                "UnaryPointwiseBenchmark",
                "BinaryPointwiseBenchmark",
                "ReductionBenchmark",
                "UnaryPointwiseIsCloseBenchmark",
                "GenericBenchmark",
                "BlasBenchmark",
                "OperationBenchmark",
            )
            if not any(cls in text for cls in benchmark_classes) and ".run()" not in text:
                evidence.append("missing benchmark wrapper class/run() usage")
            if evidence:
                add("medium", "benchmark_file_structure", "New benchmark file is missing expected benchmark patterns.", [f"{path}: {item}" for item in evidence])
            nested_classes = added_line_evidence(path, added_by_file, r"^\s+class\s+[A-Za-z_][A-Za-z0-9_]*Benchmark\b")
            if nested_classes:
                add("medium", "benchmark_class_nested", "Custom benchmark classes should be defined at module scope, not inside test functions.", nested_classes)
            empty_override = re.search(
                r"def\s+(set(?:_more)?_shapes)\s*\([^)]*\):\s*\n\s+super\(\)\.\1\s*\([^)]*\)",
                text,
                re.MULTILINE,
            )
            if empty_override:
                add("low", "benchmark_empty_override", "Do not keep empty set_shapes/set_more_shapes overrides that only call super().", [f"{path}: {empty_override.group(1)}"])

    probability_ids = [item for item in current_ids if any(hint in item for hint in PROBABILITY_OP_HINTS)]
    if probability_ids:
        test_text = "\n".join(
            added_text_for(path, added_by_file)
            for path in added_by_file
            if path.startswith("tests/")
        )
        has_stats = re.search(r"\b(mean|var|variance|std)\s*\(", test_text) or re.search(r"\bmean\b|\bvariance\b|\bstd\b", test_text)
        if "gems_assert_close" in test_text and not has_stats:
            add(
                "medium",
                "probability_test_not_statistical",
                "Probability/random operators should use statistical validation rather than only exact/close comparison.",
                probability_ids,
            )

    return findings


def check_backend_specialization_files(
    *,
    files: list[str],
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
    backend_state: dict[str, set[str]],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    if not backend_state:
        return findings

    for backend, ids in sorted(backend_state.items()):
        init_path = f"src/flag_gems/runtime/backend/{backend}/ops/__init__.py"
        tune_path = f"src/flag_gems/runtime/backend/{backend}/tune_configs.yaml"
        has_init = init_path in files
        has_tune = tune_path in files
        init_text = added_text_for(init_path, added_by_file)

        if not has_init:
            add(
                "high",
                "backend_missing_ops_init",
                "Backend-specialized PR should update backend ops/__init__.py for every touched backend.",
                [init_path],
            )
        else:
            missing_exports: list[str] = []
            for op_name in sorted(ids):
                simple_name = canonical_variant_id(op_name)
                if simple_name not in init_text:
                    missing_exports.append(f"{init_path}: missing import/export hint for {simple_name}")
            if missing_exports:
                add(
                    "medium",
                    "backend_ops_init_incomplete",
                    "Backend ops/__init__.py does not appear to import/export every touched backend operator.",
                    missing_exports,
                )

        if has_tune:
            tune_text = added_text_for(tune_path, added_by_file)
            unrelated = []
            for _, text in added_by_file.get(tune_path, []):
                stripped = text.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                if stripped.startswith("-") and "operator" not in stripped:
                    continue
                if any(belongs_to_current(token, current_ids) for token in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", stripped)):
                    continue
                if any(op in stripped for op in ids):
                    continue
                unrelated.append(stripped[:220])
            if unrelated and not tune_text:
                add(
                    "medium",
                    "backend_tune_config_unclear",
                    "Backend tune_configs.yaml changed, but added lines do not clearly map to the current operator.",
                    [f"{tune_path}: {line}" for line in unrelated[:6]],
                )

    backend_only_paths = [
        path for path in files
        if path.startswith("src/flag_gems/runtime/backend/")
        and not (
            BACKEND_OP_PATH_RE.match(path)
            or BACKEND_OPS_INIT_RE.match(path)
            or BACKEND_TUNE_CONFIG_RE.match(path)
        )
    ]
    if backend_only_paths:
        add(
            "medium",
            "backend_unexpected_path",
            "Backend-specialized PR touches backend paths outside the minimal operator-scoped allowlist.",
            backend_only_paths,
        )

    return findings


def check_device_hardcode(added_by_file: dict[str, list[tuple[int | None, str]]]) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    hits: list[str] = []
    for path, lines in added_by_file.items():
        if not path.endswith(".py"):
            continue
        for line_no, text in lines:
            if any(pattern.search(text) for pattern in DEVICE_HARDCODE_PATTERNS):
                hits.append(evidence_line(path, line_no, text))
    if hits:
        findings.append((
            "high",
            "device_hardcode_cuda",
            "Use flag_gems.device or backend-agnostic checks instead of .is_cuda / device.type == \"cuda\".",
            hits[:12],
        ))
    return findings


def check_fused_layout(
    *,
    files: list[str],
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
    fused_ids: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    fused_ops_in_ops_dir = []
    for path in files:
        match = re.match(r"src/flag_gems/ops/(?!__init__\.py)(.+)\.py$", path)
        if not match:
            continue
        op_name = canonical_variant_id(match.group(1))
        if op_name in fused_ids or "fused" in op_name:
            fused_ops_in_ops_dir.append(path)
    if fused_ops_in_ops_dir:
        add(
            "high",
            "fused_op_in_ops_dir",
            "Fused operators should live under src/flag_gems/fused/, not src/flag_gems/ops/.",
            fused_ops_in_ops_dir,
        )

    generic_fused_files = [path for path in files if FUSED_OP_PATH_RE.match(path)]
    if generic_fused_files:
        init_text = added_text_for("src/flag_gems/fused/__init__.py", added_by_file)
        if "src/flag_gems/fused/__init__.py" not in files:
            add(
                "high",
                "fused_init_missing",
                "PR touching generic fused operators should update src/flag_gems/fused/__init__.py.",
                ["src/flag_gems/fused/__init__.py"],
            )
        else:
            missing = []
            for path in generic_fused_files:
                op_name = canonical_variant_id(Path(path).stem)
                if op_name not in init_text:
                    missing.append(f"src/flag_gems/fused/__init__.py: missing import/export hint for {op_name}")
            if missing:
                add(
                    "medium",
                    "fused_init_incomplete",
                    "src/flag_gems/fused/__init__.py does not appear to import/export every touched fused operator.",
                    missing,
                )

    backend_non_fused = [
        path for path in files
        if BACKEND_FUSED_OP_PATH_RE.match(path)
        and canonical_variant_id(BACKEND_FUSED_OP_PATH_RE.match(path).group(2)) not in fused_ids
    ]
    if backend_non_fused:
        add(
            "medium",
            "backend_fused_path_mismatch",
            "Backend fused/ path changed, but the operator does not look like a fused operator.",
            backend_non_fused,
        )

    return findings


def check_benchmark_fairness(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
    fused_ids: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    current_norm = {canonical_variant_id(item) for item in current_ids} | fused_ids
    suspect_hits: list[str] = []
    for path, lines in added_by_file.items():
        if not path.startswith("benchmark/") or not path.endswith(".py"):
            continue
        text = "\n".join(line for _, line in lines)
        if "gems_op=" not in text:
            continue
        if not any(op_id in canonical_variant_id(Path(path).stem) or op_id in text for op_id in current_norm):
            continue
        if re.search(r"torch_op\s*=\s*torch\.[A-Za-z_][A-Za-z0-9_]*", text) and "gems_op=" in text:
            continue
        if "torch.ops.aten." in text and "gems_op=" in text:
            continue
        wrapper_defs = re.findall(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", text)
        wrapper_defs = [name for name in wrapper_defs if "gems" not in name.lower() and ("torch" in name.lower() or "ref" in name.lower() or "wrapper" in name.lower())]
        if wrapper_defs and ("torch.nn.functional" in text or "torch.autograd" in text or ".backward(" in text):
            suspect_hits.append(f"{path}: custom torch wrapper may measure extra work compared with gems_op")
    if suspect_hits:
        add(
            "medium",
            "benchmark_fairness_suspect",
            "Benchmark torch path may be doing extra work beyond the gems path; verify equivalent measurement scope.",
            suspect_hits,
        )

    return findings


def check_specialization_pr_dependency(
    *,
    metadata: dict,
    files: list[str],
    current_ids: set[str],
    backend_state: dict[str, set[str]],
    repo: str,
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    if not backend_state:
        return findings

    title = metadata.get("title") or ""
    head_ref = metadata.get("headRefName") or ""
    generic_frontend_files = [
        path for path in files
        if re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path)
    ]
    if generic_frontend_files:
        return findings
    if not re.search(r"特化|speciali[sz]ed|backend", title, re.IGNORECASE) and not re.search(
        r"(backend|speciali[sz]ed|特化)",
        head_ref,
        re.IGNORECASE,
    ):
        return findings

    evidence: list[str] = []
    for op_id in sorted({base_id(item) for item in current_ids}):
        query = f"is:pr is:open repo:{repo} in:title \"Add {op_id} operator\""
        result = run_cmd(
            ["gh", "pr", "list", "--repo", repo, "--search", query, "--json", "number,title,state,mergedAt", "--limit", "5"],
            Path.cwd(),
            timeout=60,
        )
        if result.returncode != 0:
            continue
        try:
            items = json.loads(result.stdout)
        except json.JSONDecodeError:
            continue
        visible = []
        for item in items:
            if not isinstance(item, dict):
                continue
            item_title = item.get("title") or ""
            if item_title == title:
                continue
            if base_id(canonical_variant_id(op_id)) not in canonical_variant_id(item_title):
                visible.append(f"candidate PR #{item.get('number')}: {item_title}")
            else:
                visible.append(f"candidate PR #{item.get('number')}: {item_title}")
        if not visible:
            evidence.append(
                f"{op_id}: no obvious generic/open PR found for backend-specialized branch {head_ref or '(unknown branch)'}"
            )
    if evidence:
        findings.append((
            "medium",
            "specialization_without_obvious_generic_pr",
            "Backend-specialized PR should usually follow an existing generic implementation or generic PR.",
            evidence[:12],
        ))
    return findings


def extract_yaml_added_blocks(added_by_file: dict[str, list[tuple[int | None, str]]]) -> dict[str, list[str]]:
    blocks: dict[str, list[str]] = {}
    current_id: str | None = None
    current_lines: list[str] = []
    for _, text in added_by_file.get("conf/operators.yaml", []):
        match = re.match(r"\s*-\s+id:\s+(\S+)", text)
        if match:
            if current_id:
                blocks[current_id] = current_lines
            current_id = match.group(1).strip()
            current_lines = [text]
        elif current_id:
            current_lines.append(text)
    if current_id:
        blocks[current_id] = current_lines
    return blocks


def check_yaml_added_blocks(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    blocks = extract_yaml_added_blocks(added_by_file)

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    for op_id, lines in blocks.items():
        if current_ids and not belongs_to_current(op_id, current_ids):
            continue
        text = "\n".join(lines)
        missing = [
            field for field in ("id:", "description:", "for:", "labels:", "kind:", "stages:")
            if field not in text
        ]
        if missing:
            add("high", "yaml_missing_fields", "New operators.yaml block is missing required fields.", [f"{op_id}: {', '.join(missing)}"])
        if "KernelGen" not in text:
            add("medium", "yaml_missing_kernelgen_label", "New operators.yaml labels should include KernelGen.", [op_id])
        if not re.search(r"^\s*-\s+aten\s*$", text, re.MULTILINE):
            add("medium", "yaml_missing_aten_label", "New operators.yaml labels should include aten.", [op_id])
        if re.search(r"Triton kernel implementation for|Computes the .* operation", text):
            add("low", "yaml_placeholder_description", "operators.yaml description should not be a template placeholder.", [op_id])
        if re.search(r"\bstable\b|alpha:\s*['\"]?(?:1\.0|2\.0|3\.0|4\.)", text):
            add("medium", "yaml_stage_too_strong", "New KernelGen operator metadata should use conservative alpha/incubating stages.", [op_id])
        kind_hits = re.findall(r"^\s*-\s+([A-Za-z]+)\s*$", text, re.MULTILINE)
        kinds = [item for item in kind_hits if item in VALID_YAML_KINDS or item in {"Unknown", "UNKNOWN"}]
        for kind in kinds:
            if kind not in VALID_YAML_KINDS:
                add("low", "yaml_unknown_kind", "operators.yaml kind is not in the known kind list.", [f"{op_id}: {kind}"])
        if base_id(op_id) in TENSOR_KIND_OPS and re.search(r"^\s*-\s+Math\s*$", text, re.MULTILINE):
            add("medium", "yaml_kind_tensor_as_math", "Tensor-like operators should not use kind: Math.", [op_id])

    duplicate_added = sorted({item for item in blocks if list(blocks).count(item) > 1})
    if duplicate_added:
        add("high", "yaml_duplicate_added_id", "PR adds duplicate operators.yaml ids.", duplicate_added)

    return findings


def extract_kernel_function_sets(
    added_by_file: dict[str, list[tuple[int | None, str]]],
) -> tuple[set[str], set[str]]:
    jit_funcs: set[str] = set()
    all_funcs: set[str] = set()
    for path, lines in added_by_file.items():
        if not re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            continue
        decorators: list[str] = []
        for _, text in lines:
            stripped = text.strip()
            if stripped.startswith("@"):
                decorators.append(stripped)
                continue
            match = re.match(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", text)
            if match:
                func_name = match.group(1)
                all_funcs.add(func_name)
                if any("triton.jit" in deco or deco.endswith(".jit") or deco == "@jit" for deco in decorators):
                    jit_funcs.add(func_name)
                decorators = []
            elif stripped and not stripped.startswith("#"):
                decorators = []
    return all_funcs, jit_funcs


def check_registration_surfaces(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    added_public_functions: set[str],
    added_full_config: list[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    _, jit_funcs = extract_kernel_function_sets(added_by_file)
    ops_init_text = added_text_for("src/flag_gems/ops/__init__.py", added_by_file)
    top_init_text = added_text_for("src/flag_gems/__init__.py", added_by_file)

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    if added_public_functions and ops_init_text:
        for func_name in sorted(added_public_functions):
            if func_name not in ops_init_text:
                add("high", "ops_init_missing_export", "ops/__init__.py should import and export every new public wrapper.", [func_name])
    if jit_funcs and ops_init_text:
        leaked = [name for name in sorted(jit_funcs) if re.search(rf"\b{name}\b", ops_init_text)]
        if leaked:
            add("high", "ops_init_exports_kernel", "ops/__init__.py must not export Triton kernel functions.", leaked)

    config_keys = [entry.split(" -> ", 1)[0] for entry in added_full_config]
    duplicates = sorted({key for key in config_keys if config_keys.count(key) > 1})
    if duplicates:
        add("high", "full_config_duplicate_added", "_FULL_CONFIG should not add duplicate aten names.", duplicates)

    if added_full_config and jit_funcs:
        bad_targets = []
        for entry in added_full_config:
            _, target = entry.split(" -> ", 1)
            if target in jit_funcs:
                bad_targets.append(entry)
        if bad_targets:
            add("high", "full_config_maps_to_kernel", "_FULL_CONFIG must map aten names to public wrappers, not Triton kernels.", bad_targets)

    if added_public_functions and top_init_text:
        for func_name in sorted(added_public_functions):
            target_patterns = [func_name]
            if not func_name.startswith("_"):
                target_patterns.append(f"_{func_name}")
            if not any(
                re.search(rf'\(\s*["\'][^"\']+["\']\s*,\s*{re.escape(target)}\b', top_init_text)
                for target in target_patterns
            ):
                add("high", "full_config_missing_wrapper", "_FULL_CONFIG should register every new public wrapper.", [func_name])

    return findings


def check_kernel_risks(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    for path, lines in added_by_file.items():
        if not re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            continue
        text = "\n".join(line for _, line in lines)
        duplicate_names: dict[str, int] = {}
        for _, line in lines:
            match = re.match(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", line)
            if match:
                duplicate_names[match.group(1)] = duplicate_names.get(match.group(1), 0) + 1
        duplicates = sorted(name for name, count in duplicate_names.items() if count > 1)
        if duplicates:
            add("high", "duplicate_function_defs", "Added operator file contains duplicate function definitions.", [f"{path}: {name}" for name in duplicates])

        recursive_hits: list[str] = []
        variants = {item for current in current_ids for item in {canonical_variant_id(current), base_id(current)}}
        for line_no, line in lines:
            code_part = line.split("#", 1)[0]
            if "torch.ops." in code_part:
                continue
            for variant in variants:
                if re.search(rf"\btorch\.{re.escape(variant)}\s*\(", code_part):
                    recursive_hits.append(evidence_line(path, line_no, line))
        if recursive_hits:
            add("high", "fallback_recursion", "Operator wrapper should not call torch.<same_op>() because it can recurse through dispatch.", recursive_hits)

        alias_hits = [
            evidence_line(path, line_no, line)
            for line_no, line in lines
            if re.match(r"\s*[A-Za-z_][A-Za-z0-9_]*\s*=\s*tl_extra_shim\.[A-Za-z_][A-Za-z0-9_]*\s*$", line)
        ]
        if alias_hits:
            add("low", "alias_wrapper", "Avoid meaningless aliases for tl_extra_shim functions; call the original function directly.", alias_hits)

        global_hits = []
        for line_no, line in lines:
            stripped = line.strip()
            if not stripped or line.startswith((" ", "\t")):
                continue
            if not re.match(r"[A-Za-z_][A-Za-z0-9_]*\s*=", stripped):
                continue
            name = stripped.split("=", 1)[0].strip()
            if name.isupper() or name in {"logger"}:
                continue
            if stripped.startswith(("__all__", "_FULL_CONFIG")):
                continue
            if "tl_extra_shim." in stripped:
                continue
            global_hits.append(evidence_line(path, line_no, line))
        if global_hits:
            add("low", "kernel_module_global", "Reviewer guidance discourages module-level mutable/global variables in operator files.", global_hits)

        inline_configs = added_line_evidence(path, added_by_file, r"triton\.Config\s*\(")
        if inline_configs:
            add("medium", "inline_autotune_config", "Prefer external tune_configs.yaml/get_tuned_config over inline triton.Config blocks.", inline_configs)
        if "@triton.autotune" in text and "get_tuned_config" not in text:
            add("low", "autotune_without_get_tuned_config", "triton.autotune should usually use runtime.get_tuned_config or documented precedent.", [path])

        use_tl_extra_stubs: list[str] = []
        for idx, (line_no, line) in enumerate(lines):
            if "@use_tl_extra" not in line:
                continue
            following = "\n".join(item[1] for item in lines[idx + 1: idx + 6])
            match = re.search(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", following)
            if match and re.search(r"\bpass\b", following):
                func_name = match.group(1)
                if len(re.findall(rf"\b{re.escape(func_name)}\b", text)) <= 1:
                    use_tl_extra_stubs.append(f"{path}:{line_no}: {func_name}")
        if use_tl_extra_stubs:
            add("high", "unused_use_tl_extra_stub", "Unused @use_tl_extra pass stubs should be removed.", use_tl_extra_stubs)

    return findings


def check_logger_usage(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    added_public_functions: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []

    def add(severity: str, check: str, message: str, evidence: list[str]) -> None:
        findings.append((severity, check, message, evidence[:12]))

    bad_format: list[str] = []
    wrong_vendor: list[str] = []
    for path, lines in added_by_file.items():
        if not re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            continue
        for line_no, line in lines:
            match = re.search(r'logger\.debug\(\s*["\']([^"\']+)["\']', line)
            if not match:
                continue
            msg = match.group(1)
            if msg != msg.upper():
                bad_format.append(evidence_line(path, line_no, line))
            if not re.match(r"^GEMS(?:_[A-Z0-9]+)?\s+[A-Z0-9_]+$", msg):
                bad_format.append(evidence_line(path, line_no, line))
            if re.match(r"^[A-Z0-9]+_?GEMS\s+", msg) or re.match(r"^[A-Z0-9]+\s+GEMS\s+", msg):
                wrong_vendor.append(evidence_line(path, line_no, line))
    if bad_format:
        add("low", "logger_format", "logger.debug message should be uppercase and formatted as GEMS <OP> or GEMS_VENDOR <OP>.", sorted(set(bad_format)))
    if wrong_vendor:
        add("medium", "logger_vendor_format", "Backend logger format should be GEMS_VENDOR <OP>, not VENDOR GEMS <OP>.", sorted(set(wrong_vendor)))

    position_hits: list[str] = []
    public_names = {canonical_variant_id(item) for item in added_public_functions}
    for path, lines in added_by_file.items():
        if not re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            continue
        for idx, (line_no, line) in enumerate(lines):
            match = re.match(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", line)
            if not match or canonical_variant_id(match.group(1)) not in public_names:
                continue
            in_docstring = False
            for next_line_no, next_line in lines[idx + 1:]:
                if re.match(r"def\s+[A-Za-z_][A-Za-z0-9_]*\s*\(", next_line):
                    break
                stripped = next_line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                if stripped.startswith(('"""', "'''")):
                    if stripped.count('"""') == 1 or stripped.count("'''") == 1:
                        in_docstring = not in_docstring
                    continue
                if in_docstring:
                    continue
                if "logger.debug" not in stripped:
                    position_hits.append(evidence_line(path, next_line_no, f"{match.group(1)} first statement: {stripped}"))
                break
    if position_hits:
        add("low", "logger_not_first_statement", "Public wrapper logger.debug should be the first meaningful statement after the docstring.", position_hits)

    return findings


def extract_public_operator_functions(
    added_by_file: dict[str, list[tuple[int | None, str]]],
    current_ids: set[str],
) -> set[str]:
    functions: set[str] = set()
    for path, lines in added_by_file.items():
        if not re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            continue
        op_file_stem = Path(path).stem
        for _, text in lines:
            match = re.match(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", text)
            if not match:
                continue
            func_name = match.group(1)
            if func_name.startswith("_") and not op_file_stem.startswith("_"):
                continue
            if "kernel" in func_name or func_name.endswith(("_meta", "_impl", "_fallback")):
                continue
            if current_ids and not belongs_to_current(func_name, current_ids):
                continue
            functions.add(canonical_variant_id(func_name))
    return functions


def extract_operator_variant_functions(
    added_by_file: dict[str, list[tuple[int | None, str]]],
) -> tuple[set[str], set[str]]:
    out_functions: set[str] = set()
    inplace_functions: set[str] = set()
    for path, lines in added_by_file.items():
        if not re.match(r"src/flag_gems/ops/(?!__init__\.py).+\.py$", path):
            continue
        for _, text in lines:
            match = re.search(r"\bdef\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", text)
            if not match:
                continue
            func_name = match.group(1)
            if func_name.endswith("_out"):
                out_functions.add(func_name)
            elif func_name.endswith("_") and not func_name.startswith("__") and not func_name.endswith("__"):
                inplace_functions.add(func_name)
    return out_functions, inplace_functions


def check_public_function_coverage(
    *,
    added_public_functions: set[str],
    added_yaml_ids: list[str],
    added_pytest_marks: set[str],
    added_benchmark_op_names: set[str],
    current_ids: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    public_ids = {canonical_variant_id(item) for item in added_public_functions}
    yaml_ids = {canonical_variant_id(item) for item in added_yaml_ids}
    pytest_ids = {canonical_variant_id(item) for item in added_pytest_marks}
    benchmark_ids = {canonical_variant_id(item) for item in added_benchmark_op_names}

    scoped_yaml_ids = {item for item in yaml_ids if belongs_to_current(item, current_ids)}
    scoped_pytest_ids = {item for item in pytest_ids if belongs_to_current(item, current_ids)}
    scoped_benchmark_ids = {item for item in benchmark_ids if belongs_to_current(item, current_ids)}

    for func_id in sorted(public_ids):
        missing: list[str] = []
        if func_id not in scoped_yaml_ids:
            missing.append(f"missing yaml id: {func_id}")
        if func_id not in scoped_pytest_ids:
            missing.append(f"missing pytest mark: {func_id}")
        if func_id not in scoped_benchmark_ids:
            missing.append(f"missing benchmark op_name: {func_id}")
        if missing:
            findings.append((
                "high",
                "operator_function_missing_coverage",
                "New public operator function should have matching yaml id, pytest mark, and benchmark op_name.",
                [f"{func_id}: {item}" for item in missing],
            ))

    declared_ids = scoped_yaml_ids | scoped_pytest_ids | scoped_benchmark_ids
    for declared_id in sorted(declared_ids - public_ids):
        sources: list[str] = []
        if declared_id in scoped_yaml_ids:
            sources.append("yaml id")
        if declared_id in scoped_pytest_ids:
            sources.append("pytest mark")
        if declared_id in scoped_benchmark_ids:
            sources.append("benchmark op_name")
        findings.append((
            "high",
            "coverage_without_operator_function",
            "New yaml/test/benchmark operator entry should have a matching public operator function in the PR diff.",
            [f"{declared_id}: present in {', '.join(sources)}, missing public function def"],
        ))

    return findings


def check_variant_consistency(
    *,
    added_out_functions: set[str],
    added_inplace_functions: set[str],
    added_yaml_ids: list[str],
    added_full_config: list[str],
    added_pytest_marks: set[str],
    added_benchmark_op_names: set[str],
) -> list[tuple[str, str, str, list[str]]]:
    findings: list[tuple[str, str, str, list[str]]] = []
    config_keys = {entry.split(" -> ", 1)[0] for entry in added_full_config}

    def check_variant(func_name: str, variant_id: str, kind: str) -> None:
        evidence: list[str] = []
        if kind == "out" and not any(key.endswith(".out") and key.replace("special.", "special_").split(".out")[0] == variant_id[:-4] for key in config_keys):
            evidence.append(f"missing _FULL_CONFIG .out key for function {func_name}")
        if kind == "inplace" and not any(key.replace("special.", "special_").split(".")[0].lstrip("_") == variant_id for key in config_keys):
            evidence.append(f"missing _FULL_CONFIG key for inplace function {func_name}")
        if evidence:
            findings.append((
                "high",
                f"{kind}_variant_incomplete",
                f"Exported {kind} variant must have matching _FULL_CONFIG coverage.",
                evidence,
            ))

    for func_name in sorted(added_out_functions):
        check_variant(func_name, func_name, "out")
    for func_name in sorted(added_inplace_functions):
        check_variant(func_name, func_name.lstrip("_"), "inplace")
    return findings


def extract_speedup_findings(body: str, current_ids: set[str], threshold: float = 1.05) -> list[str]:
    findings: list[str] = []
    if not body:
        return findings
    for line in body.splitlines():
        if "|" not in line or "Geometric Mean" in line or "Mean Speedup" in line or "---" in line:
            continue
        cells = [cell.strip().strip("*") for cell in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        op_name = cells[0].strip("`")
        if op_name not in current_ids:
            continue
        try:
            speedup = float(cells[1])
        except ValueError:
            continue
        if speedup < threshold:
            findings.append(f"{op_name}: geometric mean speedup {speedup:.3f} < {threshold:.2f}")
    return findings


def render_prompt(template: str, pr_dir: Path, args: argparse.Namespace, checkout_dir: Path | None) -> str:
    return template.format(
        skill_path=str(args.skill_dir / "SKILL.md"),
        pr_json=str(pr_dir / "pr.json"),
        files_txt=str(pr_dir / "files.txt"),
        diff_patch=str(pr_dir / "diff.patch"),
        checks_json=str(pr_dir / "deterministic_checks.json"),
        checkout_dir=str(checkout_dir) if checkout_dir else "not created; use diff.patch",
    )


def run_streaming_agent(
    cmd: list[str],
    cwd: Path,
    timeout_seconds: int,
    env: dict[str, str],
    log_file: Path,
    conversation_file: Path,
    prompt: str,
) -> tuple[int, str, str]:
    stdout_chunks: list[str] = []
    stderr_chunks: list[str] = []
    deadline = time.monotonic() + timeout_seconds

    with log_file.open("w") as log, conversation_file.open("w") as stream:
        stream.write(json.dumps({
            "type": "meta",
            "time": utc_now(),
            "cwd": str(cwd),
            "command": cmd[:-1] + ["<prompt>"],
            "prompt": prompt,
        }, ensure_ascii=False) + "\n")
        stream.flush()

        proc = subprocess.Popen(
            cmd,
            cwd=str(cwd),
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=1,
        )
        sel = selectors.DefaultSelector()
        assert proc.stdout is not None
        assert proc.stderr is not None
        sel.register(proc.stdout, selectors.EVENT_READ, "stdout")
        sel.register(proc.stderr, selectors.EVENT_READ, "stderr")
        returncode = 1
        try:
            while sel.get_map():
                if time.monotonic() > deadline:
                    proc.kill()
                    raise subprocess.TimeoutExpired(cmd, timeout_seconds)
                for key, _ in sel.select(timeout=1.0):
                    line = key.fileobj.readline()
                    if line == "":
                        sel.unregister(key.fileobj)
                        continue
                    stream_name = key.data
                    if stream_name == "stdout":
                        stdout_chunks.append(line)
                    else:
                        stderr_chunks.append(line)
                    log.write(line)
                    log.flush()
                    record = {
                        "type": "stream",
                        "time": utc_now(),
                        "stream": stream_name,
                        "raw": line.rstrip("\n"),
                    }
                    try:
                        parsed = json.loads(line)
                    except json.JSONDecodeError:
                        parsed = None
                    if isinstance(parsed, dict):
                        record["event"] = parsed
                    stream.write(json.dumps(record, ensure_ascii=False) + "\n")
                    stream.flush()
            returncode = proc.wait(timeout=5)
            return returncode, "".join(stdout_chunks), "".join(stderr_chunks)
        finally:
            sel.close()
            stream.write(json.dumps({
                "type": "result",
                "time": utc_now(),
                "returncode": returncode,
            }, ensure_ascii=False) + "\n")


def extract_agent_report(stdout: str, stderr: str) -> str:
    texts: list[str] = []
    raw = stdout + "\n" + stderr
    for line in raw.splitlines():
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(event, dict):
            continue
        if isinstance(event.get("result"), str):
            texts.append(event["result"])
        message = event.get("message")
        if isinstance(message, dict):
            for item in message.get("content", []):
                if isinstance(item, dict) and item.get("type") == "text":
                    text = item.get("text")
                    if isinstance(text, str):
                        texts.append(text)
    if texts:
        return texts[-1].strip()
    clean = ANSI_RE.sub("", raw).strip()
    return clean[-8000:] if clean else "AGENT_FAILED: no output"


def parse_machine_summary(report: str) -> dict:
    match = MACHINE_SUMMARY_RE.search(report)
    if not match:
        return {}
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError:
        return {}


def build_agent_cmd(args: argparse.Namespace, prompt: str, pr_dir: Path, checkout_dir: Path | None) -> list[str]:
    cmd = [
        args.claude_bin,
        "-p",
        "--verbose",
        "--output-format",
        "stream-json",
        "--permission-mode",
        args.permission_mode,
        "--add-dir",
        str(pr_dir),
        "--add-dir",
        str(args.skill_dir),
    ]
    if checkout_dir:
        cmd.extend(["--add-dir", str(checkout_dir)])
    if args.model:
        cmd.extend(["--model", args.model])
    if args.settings_file and Path(args.settings_file).exists():
        cmd.extend(["--settings", str(args.settings_file)])
    if args.max_budget_usd is not None:
        cmd.extend(["--max-budget-usd", str(args.max_budget_usd)])
    cmd.append(prompt)
    return cmd


def audit_one_pr(pr: int, args: argparse.Namespace, run_dir: Path, prompt_template: str) -> AuditResult:
    start = utc_now()
    start_epoch = time.time()
    pr_dir = run_dir / f"pr_{pr}"
    report_file = pr_dir / "report.md"
    conversation_file = pr_dir / "conversation.jsonl"
    log_file = pr_dir / "raw.log"

    try:
        artifacts = collect_pr_artifacts(pr, args, pr_dir)
        checks = deterministic_checks(artifacts["metadata"], artifacts["files"], artifacts["diff"])
        (pr_dir / "deterministic_checks.json").write_text(
            json.dumps(checks, indent=2, ensure_ascii=False) + "\n"
        )

        if args.no_agent:
            report = deterministic_report(pr, artifacts["metadata"], checks)
            report_file.write_text(report)
            verdict = "NEEDS_FIX" if checks["actionable_count"] else "PASS"
            non_blocking = sum(
                1 for item in checks["findings"] if item["severity"] in {"medium", "low"}
            )
            end = utc_now()
            return AuditResult(
                pr=pr,
                url=artifacts["metadata"].get("url"),
                title=artifacts["metadata"].get("title"),
                status="success",
                verdict=verdict,
                highest_severity=checks["highest_severity"],
                blocking_count=checks["blocking_count"],
                non_blocking_count=non_blocking,
                start_time=start,
                end_time=end,
                duration_seconds=int(time.time() - start_epoch),
                pr_dir=str(pr_dir),
                report_file=str(report_file),
                conversation_file=None,
                log_file=None,
            )

        prompt = render_prompt(prompt_template, pr_dir, args, checkout_dir=None)
        env = os.environ.copy()
        extend_no_proxy(env)
        if args.anthropic_base_url:
            env["ANTHROPIC_BASE_URL"] = args.anthropic_base_url
        if args.anthropic_auth_token:
            env["ANTHROPIC_AUTH_TOKEN"] = args.anthropic_auth_token

        cmd = build_agent_cmd(args, prompt, pr_dir, checkout_dir=None)
        returncode, stdout, stderr = run_streaming_agent(
            cmd,
            pr_dir,
            args.timeout * 60,
            env,
            log_file,
            conversation_file,
            prompt,
        )
        report = extract_agent_report(stdout, stderr)
        if returncode != 0:
            report = f"# PR {pr} Audit\n\n## Verdict\nAGENT_FAILED\n\nAgent exited with {returncode}.\n\n```\n{report[-4000:]}\n```\n"
        report_file.write_text(report.rstrip() + "\n")

        machine = parse_machine_summary(report)
        verdict = str(machine.get("verdict") or ("AGENT_FAILED" if returncode else "PASS"))
        highest = str(machine.get("highest_severity") or checks["highest_severity"])
        blocking = int(machine.get("blocking_count") or checks["blocking_count"])
        fallback_non_blocking = sum(
            1 for item in checks["findings"] if item["severity"] in {"medium", "low"}
        )
        non_blocking = int(machine.get("non_blocking_count") or fallback_non_blocking)
        agent_actionable = non_blocking > 0 and highest in {"medium", "low"}
        if returncode == 0 and verdict == "PASS" and (blocking > 0 or checks["actionable_count"] > 0 or agent_actionable):
            verdict = "NEEDS_FIX"
        end = utc_now()
        return AuditResult(
            pr=pr,
            url=artifacts["metadata"].get("url"),
            title=artifacts["metadata"].get("title"),
            status="success" if returncode == 0 else "agent_failed",
            verdict=verdict,
            highest_severity=highest,
            blocking_count=blocking,
            non_blocking_count=non_blocking,
            start_time=start,
            end_time=end,
            duration_seconds=int(time.time() - start_epoch),
            pr_dir=str(pr_dir),
            report_file=str(report_file),
            conversation_file=str(conversation_file),
            log_file=str(log_file),
            error_summary=None if returncode == 0 else f"agent exited {returncode}",
        )
    except subprocess.TimeoutExpired as exc:
        end = utc_now()
        message = f"Timed out after {args.timeout} minutes: {exc}"
        pr_dir.mkdir(parents=True, exist_ok=True)
        report_file.write_text(f"# PR {pr} Audit\n\n## Verdict\nAGENT_FAILED\n\n{message}\n")
        return AuditResult(
            pr=pr,
            url=None,
            title=None,
            status="timeout",
            verdict="AGENT_FAILED",
            highest_severity="high",
            blocking_count=1,
            non_blocking_count=0,
            start_time=start,
            end_time=end,
            duration_seconds=int(time.time() - start_epoch),
            pr_dir=str(pr_dir),
            report_file=str(report_file),
            conversation_file=str(conversation_file),
            log_file=str(log_file),
            error_summary=message,
        )
    except Exception as exc:
        end = utc_now()
        pr_dir.mkdir(parents=True, exist_ok=True)
        report_file.write_text(f"# PR {pr} Audit\n\n## Verdict\nAGENT_FAILED\n\n{type(exc).__name__}: {exc}\n")
        return AuditResult(
            pr=pr,
            url=None,
            title=None,
            status="failed",
            verdict="AGENT_FAILED",
            highest_severity="high",
            blocking_count=1,
            non_blocking_count=0,
            start_time=start,
            end_time=end,
            duration_seconds=int(time.time() - start_epoch),
            pr_dir=str(pr_dir),
            report_file=str(report_file),
            conversation_file=str(conversation_file),
            log_file=str(log_file),
            error_summary=f"{type(exc).__name__}: {exc}",
        )


def deterministic_report(pr: int, metadata: dict, checks: dict) -> str:
    verdict = "NEEDS_FIX" if checks["actionable_count"] else "PASS"
    blocking = [item for item in checks["findings"] if item["severity"] == "high"]
    actionable = [item for item in checks["findings"] if item["severity"] in {"medium", "low"}]
    info = [item for item in checks["findings"] if item["severity"] == "info"]
    lines = [
        f"# PR {pr} Audit",
        "",
        "## Verdict",
        verdict,
        "",
        "## Blocking Findings",
    ]
    if not blocking:
        lines.append("None")
    else:
        for idx, item in enumerate(blocking, 1):
            lines.append(f"{idx}. {item['check']}: {item['message']}")
            lines.extend(f"   - {ev}" for ev in item.get("evidence", []))
    lines.extend(["", "## Actionable Non-blocking Findings"])
    if not actionable:
        lines.append("None")
    else:
        for idx, item in enumerate(actionable, 1):
            lines.append(f"{idx}. [{item['severity']}] {item['check']}: {item['message']}")
            lines.extend(f"   - {ev}" for ev in item.get("evidence", []))
    lines.extend(["", "## Info Findings"])
    if not info:
        lines.append("None")
    else:
        for idx, item in enumerate(info, 1):
            lines.append(f"{idx}. {item['check']}: {item['message']}")
            lines.extend(f"   - {ev}" for ev in item.get("evidence", []))
    lines.extend([
        "",
        "## Suggested Fix",
        "None" if not checks["actionable_count"] else "Review and repair the deterministic findings above.",
        "",
        "## Evidence Checked",
        "- deterministic checks: yes",
        "- diff.patch: no agent mode",
        "- skill rules: deterministic subset",
        "",
        "## Machine Summary",
        "```json",
        json.dumps({
            "verdict": verdict,
            "blocking_count": len(blocking),
            "non_blocking_count": len(actionable),
            "info_count": len(info),
            "highest_severity": checks["highest_severity"],
        }, ensure_ascii=False, indent=2),
        "```",
        "",
    ])
    return "\n".join(lines)


def write_summary(run_dir: Path, results: list[AuditResult]) -> None:
    payload = [asdict(item) for item in sorted(results, key=lambda item: item.pr)]
    (run_dir / "summary.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")

    lines = [
        "# Batch PR Audit Summary",
        "",
        f"- Time: {run_dir.name}",
        f"- PRs: {len(results)}",
        "",
        "| PR | Verdict | Severity | Blocking | Non-blocking | Report |",
        "|---:|---|---|---:|---:|---|",
    ]
    for item in sorted(results, key=lambda item: item.pr):
        rel = Path(item.report_file).relative_to(run_dir)
        label = f"#{item.pr}"
        if item.url:
            label = f"[#{item.pr}]({item.url})"
        lines.append(
            f"| {label} | {item.verdict} | {item.highest_severity} | "
            f"{item.blocking_count} | {item.non_blocking_count} | [{rel}]({rel}) |"
        )
    (run_dir / "summary.md").write_text("\n".join(lines) + "\n")


def parse_args() -> argparse.Namespace:
    defaults = load_env_file(Path(__file__).with_name("config.env"))
    parser = argparse.ArgumentParser(description="Parallel read-only auditor for FlagGems PRs")
    parser.add_argument("--prs", help="Comma/space separated PR numbers or URLs")
    parser.add_argument("--prs-file", type=Path, help="File containing PR numbers or URLs")
    parser.add_argument("--query", help="gh pr list --search query")
    parser.add_argument("--query-limit", type=int, default=50)
    parser.add_argument("--repo", default=defaults.get("REPO", "flagos-ai/FlagGems-Experimental"))
    parser.add_argument("--skill-dir", type=Path, default=defaults.get("SKILL_DIR", "/root/baai-internship/skills/flaggems-pr-submit"))
    parser.add_argument("--report-dir", type=Path, default=defaults.get("REPORT_DIR", "/root/baai-internship/batch_pr_audit/reports"))
    parser.add_argument("--prompt-template", type=Path, default=Path(__file__).parent / "prompts/pr_audit_prompt.md")
    parser.add_argument("--max-workers", type=int, default=int(defaults.get("MAX_WORKERS", "4")))
    parser.add_argument("--timeout", type=int, default=int(defaults.get("TIMEOUT_MINUTES", "25")), help="Per-PR agent timeout in minutes")
    parser.add_argument("--no-agent", action="store_true", help="Only collect diff and run deterministic checks")
    parser.add_argument("--claude-bin", default=defaults.get("CLAUDE_BIN", "claude"))
    parser.add_argument("--model", default=defaults.get("MODEL") or None)
    parser.add_argument("--settings-file", type=Path, default=None, help="Optional claude CLI --settings file")
    parser.add_argument("--permission-mode", default=defaults.get("PERMISSION_MODE", "acceptEdits"))
    parser.add_argument("--max-budget-usd", type=float, default=None)
    parser.add_argument("--anthropic-base-url", default=defaults.get("ANTHROPIC_BASE_URL") or os.environ.get("ANTHROPIC_BASE_URL"))
    parser.add_argument("--anthropic-auth-token", default=defaults.get("ANTHROPIC_AUTH_TOKEN") or os.environ.get("ANTHROPIC_AUTH_TOKEN"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    prs = load_pr_numbers(args)
    if not prs:
        print("No PRs provided. Use --prs, --prs-file, or --query.", file=sys.stderr)
        return 2
    if not args.skill_dir.exists():
        print(f"Skill dir not found: {args.skill_dir}", file=sys.stderr)
        return 2
    if not args.prompt_template.exists():
        print(f"Prompt template not found: {args.prompt_template}", file=sys.stderr)
        return 2

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = args.report_dir / timestamp
    run_dir.mkdir(parents=True, exist_ok=True)
    prompt_template = args.prompt_template.read_text()

    print("=" * 60)
    print("Batch PR Audit")
    print(f"Run dir: {run_dir}")
    print(f"PRs: {', '.join(map(str, prs))}")
    print(f"Workers: {args.max_workers}")
    print(f"Agent: {'disabled' if args.no_agent else args.model or args.claude_bin}")
    print("=" * 60)

    results: list[AuditResult] = []
    status_lock = threading.Lock()
    status_file = run_dir / "status.json"

    def save_status() -> None:
        with status_lock:
            status_file.write_text(json.dumps([asdict(item) for item in results], indent=2, ensure_ascii=False) + "\n")

    with ThreadPoolExecutor(max_workers=max(1, args.max_workers)) as executor:
        futures = {
            executor.submit(audit_one_pr, pr, args, run_dir, prompt_template): pr
            for pr in prs
        }
        for future in as_completed(futures):
            pr = futures[future]
            result = future.result()
            results.append(result)
            save_status()
            print(
                f"[{result.verdict}] PR #{pr} severity={result.highest_severity} "
                f"blocking={result.blocking_count} report={result.report_file}"
            )

    write_summary(run_dir, results)
    print(f"Summary: {run_dir / 'summary.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
