#!/usr/bin/env python3
"""FlagGems 摩尔线程(Moore Threads/MUSA)特化算子 PR 提交前自动化检查脚本。

用法:
    python check_operator.py <operator_name> [--repo-dir /path/to/FlagGems]

检查项:
    1. kernel 文件存在且内容合规（路径: _mthreads/ops/<op>.py，Apache 文件头）
    2. _mthreads/ops/__init__.py 注册（import + __all__，字母序，只导出 wrapper）
    3. 摩尔线程特有: musa 设备判定、回退 default 实现、GEMS_MTHREADS logger、
       tl_extra_shim（禁止 libdevice）、fp64/int64 白名单
    4. 通用算子存在上游 + 摩尔线程特化不存在上游
    5. 代码质量（重复函数、print、unused import、行长）
    6. 单算子 PR（git diff 只含本算子文件）
"""

import argparse
import ast
import os
import re
import subprocess
import sys


class Colors:
    OK = "\033[92m"
    WARN = "\033[93m"
    FAIL = "\033[91m"
    BOLD = "\033[1m"
    END = "\033[0m"


def ok(msg):
    print(f"  {Colors.OK}✓{Colors.END} {msg}")


def warn(msg):
    print(f"  {Colors.WARN}⚠{Colors.END} {msg}")


def fail(msg):
    print(f"  {Colors.FAIL}✗{Colors.END} {msg}")


def section(msg):
    print(f"\n{Colors.BOLD}[{msg}]{Colors.END}")


MTHREADS_OPS = "src/flag_gems/runtime/backend/_mthreads/ops"
GENERIC_OPS = "src/flag_gems/ops"


class OperatorChecker:
    def __init__(self, op_name, repo_dir):
        self.op_name = op_name
        self.repo_dir = repo_dir
        self.errors = []
        self.warnings = []

        self.op_upper = op_name.upper()
        self.kernel_path = os.path.join(repo_dir, MTHREADS_OPS, f"{op_name}.py")
        self.ops_init_path = os.path.join(repo_dir, MTHREADS_OPS, "__init__.py")

    def run_all(self):
        self.check_kernel()
        self.check_ops_init()
        self.check_mthreads_specific()
        self.check_code_quality()
        self.check_upstream()
        self.check_single_operator_pr()
        self.print_summary()
        return len(self.errors) == 0

    # ------------------------------------------------------------------ kernel
    def check_kernel(self):
        section("Kernel 文件检查")
        if not os.path.isfile(self.kernel_path):
            self.errors.append(f"kernel 文件不存在: {self.kernel_path}")
            fail(f"文件不存在: {self.kernel_path}")
            return

        ok(f"文件存在: {MTHREADS_OPS}/{self.op_name}.py")

        with open(self.kernel_path, "r") as f:
            content = f.read()
        self._kernel_content = content

        # Apache License header (摩尔线程特化不加 KernelGen 首行)
        head = "\n".join(content.split("\n")[:15])
        if "Licensed under the Apache License" in head:
            ok("Apache License 文件头存在")
        else:
            self.errors.append("kernel 文件缺少 Apache License 文件头")
            fail("文件头应为 Apache License 段（参考 _mthreads/ops/celu.py）")

        if content.split("\n")[0].strip().startswith("# Generated by KernelGen"):
            self.warnings.append("摩尔线程特化文件不应有 KernelGen 首行（与 _mthreads 现有风格不一致）")
            warn("检测到 KernelGen 首行 — 摩尔线程特化文件应以 Apache License 开头，无此首行")

        if "import logging" in content and "logging.getLogger" in content:
            ok("使用 logging 模块")
            # 摩尔线程后端专用 logger 命名：不允许主文件夹写法 getLogger(__name__)
            backend_logger = re.search(
                r'getLogger\(\s*f["\']flag_gems\.runtime\.backend\._mthreads\.ops\.'
                r'\{__name__\.split\(["\']\.["\']\)\[-1\]\}["\']\s*\)',
                content,
            )
            if backend_logger:
                ok("logger 命名符合摩尔线程后端专用写法")
            elif re.search(r'getLogger\(\s*__name__\s*\)', content):
                self.errors.append(
                    "logger 命名使用了主文件夹写法 getLogger(__name__)，"
                    "摩尔线程后端应为 "
                    "getLogger(f'flag_gems.runtime.backend._mthreads.ops.{__name__.split(\".\")[-1]}')"
                )
                fail(
                    'logger 命名应为 getLogger('
                    "f'flag_gems.runtime.backend._mthreads.ops.{__name__.split(\".\")[-1]}')"
                    "（参考 _mthreads/ops/celu.py），不是 getLogger(__name__)"
                )
            else:
                self.warnings.append("logger 命名未匹配摩尔线程后端专用写法，请人工确认")
                warn(
                    "建议 logger = getLogger("
                    "f'flag_gems.runtime.backend._mthreads.ops.{__name__.split(\".\")[-1]}')"
                )
        else:
            self.warnings.append("kernel 未使用 logging 模块")
            warn(
                "建议 logger = logging.getLogger("
                "f'flag_gems.runtime.backend._mthreads.ops.{__name__.split(\".\")[-1]}')"
            )

        if "print(" in content:
            self.errors.append("kernel 文件中使用了 print()")
            fail("包含 print() — 应使用 logger.debug()")
        else:
            ok("无 print() 调用")

        try:
            self._tree = ast.parse(content)
        except SyntaxError as e:
            self.errors.append(f"kernel 文件语法错误: {e}")
            fail(f"Python 语法错误: {e}")
            self._tree = None
            return

        self._check_duplicate_functions(content)
        self._check_line_length(content)

        # 导出函数 / jit kernel
        self.exported = [
            n.name for n in ast.iter_child_nodes(self._tree)
            if isinstance(n, ast.FunctionDef) and not n.name.startswith("_")
        ]
        self.jit_funcs = []
        for n in ast.walk(self._tree):
            if isinstance(n, ast.FunctionDef):
                for dec in n.decorator_list:
                    dtext = ast.dump(dec)
                    if "jit" in dtext:
                        self.jit_funcs.append(n.name)
        if self.jit_funcs:
            ok(f"检测到 triton.jit kernel: {', '.join(sorted(set(self.jit_funcs)))}")

    def _check_duplicate_functions(self, content):
        try:
            tree = ast.parse(content)
        except SyntaxError:
            return
        names = {}
        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.FunctionDef):
                names.setdefault(node.name, 0)
                names[node.name] += 1
        dups = [n for n, c in names.items() if c > 1]
        if dups:
            self.errors.append(f"kernel 存在重复函数定义: {dups}")
            fail(f"重复函数定义（后者覆盖前者）: {dups}")
        else:
            ok("无重复函数定义")

    def _check_line_length(self, content):
        long_lines = [
            i + 1 for i, line in enumerate(content.split("\n")) if len(line) > 120
        ]
        if long_lines:
            self.warnings.append(f"kernel 有超过 120 字符的行: {long_lines[:5]}")
            warn(f"行长 >120: 行 {long_lines[:5]}{'...' if len(long_lines) > 5 else ''}")
        else:
            ok("行长均 ≤120")

    # -------------------------------------------------------------- ops __init__
    def check_ops_init(self):
        section("_mthreads/ops/__init__.py 注册检查")
        if not os.path.isfile(self.ops_init_path):
            self.errors.append(f"__init__.py 不存在: {self.ops_init_path}")
            fail(f"文件不存在: {self.ops_init_path}")
            return

        with open(self.ops_init_path, "r") as f:
            content = f.read()

        # import 行
        import_re = re.compile(rf"^from \.{re.escape(self.op_name)} import (.+)$", re.M)
        m = import_re.search(content)
        if not m:
            self.errors.append(f"__init__.py 缺少 from .{self.op_name} import ...")
            fail(f"缺少 import: from .{self.op_name} import <wrapper>")
            imported = []
        else:
            imported = [x.strip() for x in re.split(r"[,\s()]+", m.group(1)) if x.strip()]
            ok(f"import 存在: from .{self.op_name} import {', '.join(imported)}")

        # 不导出 triton kernel
        jit = getattr(self, "jit_funcs", [])
        leaked = [f for f in imported if f in jit]
        if leaked:
            self.errors.append(f"__init__.py 导出了 triton kernel: {leaked}")
            fail(f"不应导出 triton.jit kernel: {leaked}（只导出 wrapper）")
        elif imported:
            ok("未导出 triton kernel（只导出 wrapper）")

        # __all__
        for func in imported:
            if re.search(rf'["\']{re.escape(func)}["\']', content):
                ok(f'__all__ 含 "{func}"')
            else:
                self.errors.append(f'__all__ 缺少 "{func}"')
                fail(f'__all__ 缺少导出名: "{func}"')

        # import 字母序（在 from .xxx import 段内）
        mods = re.findall(r"^from \.(\w+) import", content, re.M)
        # 只检查连续段是否有序（allow capability 分区多段）
        unordered = [
            (mods[i], mods[i + 1]) for i in range(len(mods) - 1) if mods[i] > mods[i + 1]
        ]
        if len(unordered) > 1:
            self.warnings.append(f"__init__.py import 疑似非字母序: {unordered[:3]}")
            warn(f"import 顺序检查（注意 capability 分区会分多段）: {unordered[:3]}")
        else:
            ok("import 顺序检查通过（含 capability 分区）")

    # --------------------------------------------------------- mthreads specific
    def check_mthreads_specific(self):
        section("摩尔线程特化检查")
        content = getattr(self, "_kernel_content", "")
        if not content:
            return

        # musa 设备判定
        if 'device.type != "musa"' in content or 'device.type == "musa"' in content:
            ok("设备判定使用 \"musa\"")
        elif '"cuda"' in content and '"musa"' not in content:
            self.errors.append("设备判定使用了 \"cuda\" 而非 \"musa\"")
            fail("摩尔线程设备 device.type 为 \"musa\"，不是 \"cuda\"")
        else:
            self.warnings.append("未检测到 musa 设备判定（确认是否需要）")
            warn("未检测到 device.type == \"musa\" 判定")

        # 回退到通用实现
        default_import = re.search(
            rf"from flag_gems\.ops\.{re.escape(self.op_name)} import .*default_", content
        )
        if "default_" in content and default_import:
            ok("回退到通用实现 default_<op>")
        elif "default_" in content:
            ok("检测到 default_ 回退（确认 import 来自 flag_gems.ops）")
        else:
            self.errors.append("kernel 未回退到通用实现（缺少 default_<op>）")
            fail("wrapper 必须在不满足特化条件时回退 flag_gems.ops.<op>")

        # GEMS_MTHREADS logger
        if re.search(rf'GEMS_MTHREADS\s+{self.op_upper}', content):
            ok(f'logger 文案: "GEMS_MTHREADS {self.op_upper}"')
        elif "GEMS_MTHREADS" in content:
            self.warnings.append("GEMS_MTHREADS logger 文案算子名可能不匹配")
            warn(f'检测到 GEMS_MTHREADS，但未精确匹配 "{self.op_upper}"')
        else:
            self.errors.append("缺少 GEMS_MTHREADS logger")
            fail(f'wrapper 首条应为 logger.debug("GEMS_MTHREADS {self.op_upper}")')

        # tl_extra_shim / 禁止 libdevice
        if "tl.extra.cuda.libdevice" in content:
            self.errors.append("kernel 直接调用了 tl.extra.cuda.libdevice")
            fail("禁止 tl.extra.cuda.libdevice（MUSA 会崩溃）— 用 tl_extra_shim")
        else:
            ok("无 tl.extra.cuda.libdevice 直接调用")

        # fp64 / int64
        if "float64" in content or "torch.double" in content or "int64" in content or "torch.long" in content:
            if "_SUPPORTED_DTYPES" in content or ".to(tl.float32)" in content or "float32" in content:
                ok("检测到 fp64/int64 相关处理（白名单或转 fp32/int32）")
            else:
                self.warnings.append("kernel 涉及 fp64/int64 但未见白名单或转换")
                warn("摩尔线程不支持 fp64/int64，需白名单过滤或转 fp32/int32")
        else:
            ok("未直接使用 fp64/int64")

    # -------------------------------------------------------------- code quality
    def check_code_quality(self):
        section("代码质量检查")
        content = getattr(self, "_kernel_content", "")
        tree = getattr(self, "_tree", None)
        if not content or tree is None:
            return

        # 未使用 import torch
        has_torch = any(
            isinstance(n, ast.Import) and any(a.name == "torch" for a in n.names)
            for n in ast.walk(tree)
        )
        torch_used = any(
            (isinstance(n, ast.Attribute) and isinstance(n.value, ast.Name) and n.value.id == "torch")
            or (isinstance(n, ast.Name) and n.id == "torch")
            for n in ast.walk(tree)
        )
        if has_torch and not torch_used:
            self.warnings.append("import torch 但未使用（flake8 F401）")
            warn("import torch 未使用 — flake8 F401")
        else:
            ok("torch import 检查通过")

        # 未使用/未注册的顶层函数（dead code）
        called = set()
        for n in ast.walk(tree):
            if isinstance(n, ast.Call):
                if isinstance(n.func, ast.Name):
                    called.add(n.func.id)
                elif isinstance(n.func, ast.Attribute):
                    called.add(n.func.attr)
            if isinstance(n, ast.Subscript) and isinstance(n.value, ast.Name):
                called.add(n.value.id)  # grid launch: kernel[grid](...)
        top_funcs = [
            n.name for n in ast.iter_child_nodes(tree) if isinstance(n, ast.FunctionDef)
        ]
        exported = set(getattr(self, "exported", []))
        dead = [
            f for f in top_funcs
            if f not in called and f not in exported and not f.startswith("__")
        ]
        if dead:
            self.warnings.append(f"疑似未使用/未注册函数: {dead}")
            warn(f"疑似 dead code（未调用且未导出）: {dead}")
        else:
            ok("无明显 dead code")

    # ------------------------------------------------------------------ upstream
    def _git_show(self, ref_path):
        try:
            subprocess.run(
                ["git", "show", ref_path],
                cwd=self.repo_dir, capture_output=True, check=True,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def check_upstream(self):
        section("上游检查")
        # 通用算子必须存在上游
        generic_ref = f"upstream/infra-ci:{GENERIC_OPS}/{self.op_name}.py"
        if self._git_show(generic_ref):
            ok(f"通用算子存在上游: {GENERIC_OPS}/{self.op_name}.py")
        else:
            self.warnings.append(f"通用算子 {GENERIC_OPS}/{self.op_name}.py 不在 upstream/infra-ci")
            warn(f"通用算子未在上游找到（确认通用版已 merge，否则先提交通用版）")

        # 摩尔线程特化不能已存在上游
        mth_ref = f"upstream/infra-ci:{MTHREADS_OPS}/{self.op_name}.py"
        if self._git_show(mth_ref):
            self.errors.append(f"摩尔线程特化已存在上游: {MTHREADS_OPS}/{self.op_name}.py")
            fail(f"上游已有摩尔线程特化 — 不应重复提交")
        else:
            ok("摩尔线程特化不在上游（可以提交）")

    def check_single_operator_pr(self):
        section("单算子 PR 检查")
        try:
            out = subprocess.run(
                ["git", "diff", "--name-only", "upstream/infra-ci...HEAD"],
                cwd=self.repo_dir, capture_output=True, text=True, check=True,
            ).stdout
        except subprocess.CalledProcessError:
            self.warnings.append("无法运行 git diff（分支/upstream 未就绪）")
            warn("git diff 失败，跳过单算子检查")
            return

        changed = [f for f in out.strip().split("\n") if f]
        if not changed:
            warn("git diff 无改动（尚未 commit？）")
            return

        allowed_exact = {
            f"{MTHREADS_OPS}/{self.op_name}.py",
            f"{MTHREADS_OPS}/__init__.py",
            f"tests/test_{self.op_name}.py",
            f"benchmark/test_{self.op_name}.py",
        }
        forbidden = []
        for f in changed:
            if f in allowed_exact:
                continue
            if f.startswith(f"{GENERIC_OPS}/") or f == "conf/operators.yaml" or "src/flag_gems/__init__.py" in f:
                forbidden.append(f + "  (禁止改通用层/yaml)")
            elif "runtime/backend/_" in f and MTHREADS_OPS not in f:
                forbidden.append(f + "  (改了其他 backend)")
            else:
                forbidden.append(f)

        if forbidden:
            self.errors.append(f"PR 含非预期文件: {forbidden}")
            fail("PR 应只含摩尔线程特化文件:")
            for f in forbidden:
                print(f"      - {f}")
        else:
            ok(f"PR 只含预期文件（{len(changed)} 个）")

    # ------------------------------------------------------------------- summary
    def print_summary(self):
        section("检查结果")
        if self.errors:
            print(f"  {Colors.FAIL}{len(self.errors)} error(s):{Colors.END}")
            for e in self.errors:
                print(f"    - {e}")
        if self.warnings:
            print(f"  {Colors.WARN}{len(self.warnings)} warning(s):{Colors.END}")
            for w in self.warnings:
                print(f"    - {w}")
        if not self.errors and not self.warnings:
            print(f"  {Colors.OK}全部通过！{Colors.END}")
        elif not self.errors:
            print(f"  {Colors.OK}无 error（warning 需人工确认）{Colors.END}")

    def get_changed_files(self):
        files = [
            f"{MTHREADS_OPS}/{self.op_name}.py",
            f"{MTHREADS_OPS}/__init__.py",
            f"tests/test_{self.op_name}.py",
            f"benchmark/test_{self.op_name}.py",
        ]
        return [f for f in files if os.path.isfile(os.path.join(self.repo_dir, f))]


def main():
    parser = argparse.ArgumentParser(description="FlagGems 摩尔线程特化算子 PR 提交前检查")
    parser.add_argument("operator", help="算子名称（如 celu, log, addmm）")
    parser.add_argument(
        "--repo-dir",
        default=os.environ.get("FLAGGEMS_REPO", "/root/FlagGems"),
        help="FlagGems 仓库路径",
    )
    parser.add_argument("--list-files", action="store_true", help="仅输出涉及的文件列表")
    args = parser.parse_args()

    checker = OperatorChecker(args.operator, args.repo_dir)

    if args.list_files:
        for f in checker.get_changed_files():
            print(f)
        return

    print(f"{Colors.BOLD}FlagGems 摩尔线程特化算子 PR 检查: {args.operator}{Colors.END}")
    print(f"仓库路径: {args.repo_dir}")

    success = checker.run_all()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
