#!/usr/bin/env bash
set -euo pipefail

# prepare_kernel.sh <op> [--repo-dir DIR] [--funcs func1,func2]
# 从 worktree 复制摩尔线程特化 kernel + 确保 Apache License 文件头 + 注册 _mthreads/ops/__init__.py
#
# 摩尔线程特化文件不加 KernelGen 首行（与 _mthreads 现有算子风格一致）。
#
# --funcs: 要导出的 wrapper 函数名（逗号分隔）；不指定则自动检测顶层非下划线 def

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

OP="${1:?Usage: prepare_kernel.sh <op> [--repo-dir DIR] [--funcs func1,func2]}"
shift

REPO_DIR=""
FUNCS=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo-dir) REPO_DIR="$2"; shift 2 ;;
        --funcs) FUNCS="$2"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

REPO_DIR="${REPO_DIR:-/root/FlagGems}"
MTHREADS_OPS="${REPO_DIR}/src/flag_gems/runtime/backend/_mthreads/ops"
WORKTREE_KERNEL="${REPO_DIR}/.worktrees/gen-${OP}/src/flag_gems/runtime/backend/_mthreads/ops/${OP}.py"
TARGET_KERNEL="${MTHREADS_OPS}/${OP}.py"
INIT_PY="${MTHREADS_OPS}/__init__.py"

# 1. 复制 kernel
if [[ ! -f "$WORKTREE_KERNEL" ]]; then
    echo "ERROR: Worktree kernel 不存在: $WORKTREE_KERNEL" >&2
    echo "       如已手动准备 kernel，跳过复制，仅注册 __init__.py。" >&2
    if [[ ! -f "$TARGET_KERNEL" ]]; then
        echo "ERROR: 目标 kernel 也不存在: $TARGET_KERNEL" >&2
        exit 1
    fi
else
    cp "$WORKTREE_KERNEL" "$TARGET_KERNEL"
    echo "[✓] 复制 kernel: ${OP}.py"
fi

# 2. 确保 Apache License 文件头（摩尔线程特化不加 KernelGen 首行）
if head -15 "$TARGET_KERNEL" | grep -q "Licensed under the Apache License"; then
    echo "[✓] Apache License 文件头已存在"
else
    echo "[!] 缺少 Apache License 文件头 — 请手动从 _mthreads/ops/celu.py 复制文件头段" >&2
fi

if head -1 "$TARGET_KERNEL" | grep -q "Generated by KernelGen"; then
    echo "[!] 检测到 KernelGen 首行 — 摩尔线程特化文件不应有，请手动删除首行" >&2
fi

# 3. 检测要导出的函数
if [[ -z "$FUNCS" ]]; then
    FUNCS=$(python3 -c "
import ast
with open('$TARGET_KERNEL') as f:
    tree = ast.parse(f.read())
funcs = []
for node in ast.iter_child_nodes(tree):
    if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
        # 排除 triton.jit kernel（只导出 wrapper）
        is_jit = any('jit' in ast.dump(d) for d in node.decorator_list)
        if not is_jit:
            funcs.append(node.name)
print(','.join(funcs))
")
    if [[ -z "$FUNCS" ]]; then
        echo "ERROR: 未检测到可导出的 wrapper 函数（非 _ 开头、非 triton.jit）" >&2
        exit 1
    fi
    echo "[✓] 自动检测导出函数: $FUNCS"
fi

# 4. 注册 _mthreads/ops/__init__.py
python3 << PYEOF
import re, sys

op = "$OP"
funcs = [f for f in "$FUNCS".split(",") if f]
init_path = "$INIT_PY"

with open(init_path, "r") as f:
    content = f.read()

import_line = f"from .{op} import {', '.join(funcs)}"

if import_line in content:
    print(f"[✓] Import 已存在: {import_line}")
else:
    lines = content.split("\n")
    # 在第一段连续的 "from .xxx import" 中按字母序插入（capability 分区的第二段不动）
    insert_idx = None
    in_imports = False
    for i, line in enumerate(lines):
        m = re.match(r'^from \.(\w+) import', line)
        if m:
            in_imports = True
            if m.group(1) > op and insert_idx is None:
                insert_idx = i
        elif in_imports and line.strip() and not line.startswith("from .") \
                and not line.startswith("    ") and not line.startswith(")"):
            if insert_idx is None:
                insert_idx = i
            break
    if insert_idx is None:
        print("ERROR: 无法找到 import 插入位置", file=sys.stderr)
        sys.exit(1)
    lines.insert(insert_idx, import_line)
    content = "\n".join(lines)
    print(f"[✓] 添加 import: {import_line} (行 {insert_idx + 1})")

# __all__ 插入（第一个 __all__ = [ ... ] 块）
lines = content.split("\n")
for func in funcs:
    if re.search(rf'["\']{re.escape(func)}["\']', content):
        print(f'[✓] __all__ 已有: "{func}"')
        continue
    entry = f'    "{func}",'
    insert_idx = None
    in_all = False
    for i, line in enumerate(lines):
        if "__all__" in line and "=" in line:
            in_all = True
            continue
        if in_all:
            stripped = line.strip().rstrip(",").strip('"').strip("'")
            if line.strip() == "]":
                if insert_idx is None:
                    insert_idx = i
                break
            if stripped > func and insert_idx is None:
                insert_idx = i
    if insert_idx is not None:
        lines.insert(insert_idx, entry)
        content = "\n".join(lines)
        print(f'[✓] 添加 __all__: "{func}" (行 {insert_idx + 1})')
    else:
        print(f"ERROR: 无法找到 __all__ 插入位置 for {func}", file=sys.stderr)
        sys.exit(1)

with open(init_path, "w") as f:
    f.write(content)
PYEOF

echo ""
echo "=== prepare_kernel 完成 ==="
echo "Kernel: $TARGET_KERNEL"
echo "导出函数: $FUNCS"
echo "__init__.py 已更新"
echo ""
echo "[!] 注意: BLAS 类算子(addmm/bmm/mm/gelu 等)需在 capability[0]>=3 块内注册，请人工确认位置"
